-- V2: Seed culture data
-- Languages (50), Ethnic Groups (50), Festivals (40), Art Forms (30), Traditional Attires (25)

-- =============================================
-- LANGUAGES (IDs 1-50)
-- =============================================
INSERT INTO languages (slug, name, description, language_family, language_status, speakers_count, script, writing_system, dialects, is_official, is_lingua_franca, region_type, province, origin_history, cultural_significance, endangered_details, preservation_efforts, created_at) VALUES

('nepali', 'Nepali', 'Official language of Nepal and lingua franca of the nation. Belongs to the Indo-Aryan language family and is written in Devanagari script.', 'INDO_ARYAN', 'SAFE', 17000000, 'Devanagari', 'Devanagari', 'Khas, Palpa, Doteli, Baitadi, Dadeldhura, Jumli', true, true, 'HILL', 'All', 'Evolved from Sanskrit through Prakrit and Apabhramsha. Khas language became dominant during Shah dynasty unification in 18th century.', 'National language and primary medium of education, government, and media. Represents national identity.', NULL, 'Constitutional protection as national language. Used in education and governance.', NOW()),

('maithili', 'Maithili', 'Second most spoken language in Nepal, predominantly spoken in the Terai region. Has its own historical literary tradition.', 'INDO_ARYAN', 'SAFE', 11000000, 'Devanagari', 'Devanagari', 'Standard Maithili, Tharu-Maithili, Sadani', false, false, 'TERAI', 'Province 2', 'Originated in the Mithila region. Rich literary tradition dating to 14th century with poets like Vidyapati.', 'Bearer of Mithila cultural heritage including Madhubani painting tradition and Mithila cuisine.', NULL, 'Growing literary community. Maithili newspapers and radio programs exist.', NOW()),

('bhojpuri', 'Bhojpuri', 'Widely spoken language of the eastern Terai region with cultural connections to Bihar and Uttar Pradesh.', 'INDO_ARYAN', 'SAFE', 6000000, 'Devanagari', 'Devanagari', 'Standard Bhojpuri, Tharu-Bhojpuri', false, false, 'TERAI', 'Province 2', 'Part of the Eastern Hindi group. Significant diaspora community worldwide.', 'Associated with vibrant folk music and Chhath Puja celebrations.', NULL, 'Active media presence with Bhojpuri songs and films.', NOW()),

('tharu', 'Tharu', 'Language of the Tharu people indigenous to the Terai lowlands. Several distinct dialect groups exist.', 'INDO_ARYAN', 'SAFE', 1500000, 'Devanagari', 'Devanagari', 'Rana Tharu, Kathariya, Morangiya, Dangaura, Chitwaniya', false, false, 'TERAI', 'Lumbini', 'Ancient language of the Terai plains. Tharu people claim descent from Rajput warriors who migrated centuries ago.', 'Central to Tharu identity and their unique stick dance tradition.', NULL, 'Community-led language preservation programs in Dang and Banke.', NOW()),

('tamang', 'Tamang', 'Tibeto-Burman language spoken by the Tamang people across the middle hills of Nepal.', 'SINO_TIBETAN', 'SAFE', 1500000, 'Devanagari', 'Devanagari', 'Eastern Tamang, Western Tamang, Northeastern Tamang', false, false, 'HILL', 'Bagmati', 'Ancient Tibeto-Burman language. Tamang script was developed in 20th century but Devanagari is widely used.', 'Language of the largest hill indigenous group. Essential for oral history and Tamang Selo music.', NULL, 'Tamang language schools and cultural programs in Kavrepalanchok and Sindhupalchok.', NOW()),

('nepal-bhasa', 'Nepal Bhasa (Newari)', 'Historical language of the Kathmandu Valley with a rich literary and cultural tradition.', 'SINO_TIBETAN', 'SAFE', 1000000, 'Ranjana', 'Devanagari', 'Kathmandu, Bhaktapur, Patan dialects', false, false, 'URBAN', 'Bagmati', 'One of the oldest Tibeto-Burman languages. Has literature dating to 13th century. Used as court language of Malla kingdoms.', 'Language of Newar civilization. Used in Buddhist and Hindu rituals, festivals, and traditional governance.', NULL, 'Newar cultural organizations run language classes. Growing media presence.', NOW()),

('bajjika', 'Bajjika', 'Dialect of Maithili spoken in the western Terai and bordering Indian regions.', 'INDO_ARYAN', 'SAFE', 800000, 'Devanagari', 'Devanagari', 'Bajjika sub-dialects', false, false, 'TERAI', 'Province 2', 'Dialect cluster within the Mithila cultural zone.', 'Associated with rural Terai culture, folk songs, and agricultural festivals.', NULL, 'Spoken widely but limited institutional support.', NOW()),

('magar', 'Magar', 'Tibeto-Burman language of the Magar people, one of the largest indigenous groups.', 'SINO_TIBETAN', 'SAFE', 700000, 'Devanagari', 'Devanagari', 'Western Magar, Kham Magar', false, false, 'HILL', 'Gandaki', 'One of the oldest Tibeto-Burman languages in Nepal. Magars historically served as Gorkha soldiers.', 'Language carries oral epics, folk songs, and the Tamang/Magar cultural narrative.', NULL, 'Magar cultural associations promote the language through literature and events.', NOW()),

('awadhi', 'Awadhi', 'Language spoken in the western Terai with cultural ties to the Awadh region of India.', 'INDO_ARYAN', 'SAFE', 600000, 'Devanagari', 'Devanagari', 'Standard Awadhi', false, false, 'TERAI', 'Lumbini', 'Descended from Central Indo-Aryan. Rich tradition of bhakti literature.', 'Language of Tulsidas and the Ramcharitmanas tradition. Connected to Tharu and other Terai communities.', NULL, 'Maintained through oral tradition and cultural practices.', NOW()),

('rai-languages', 'Rai Languages', 'Collective term for numerous Kiranti languages spoken by Rai people across eastern hills.', 'SINO_TIBETAN', 'VULNERABLE', 600000, 'Devanagari', 'Devanagari', 'Bantawa, Chamling, Kulung, Saam, Rai, Nachhiring, and many more', false, false, 'HILL', 'Koshi', 'Ancient Kiranti languages predating Indo-Aryan migration. Each Rai sub-group has distinct language.', 'Central to Kiranti religion and Mundhum oral tradition. Language of Sakela festival rituals.', NULL, 'Rai literature development programs. Some endangerment from Nepali dominance.', NOW()),

('gurung', 'Gurung', 'Tibeto-Burman language of the Gurung people of central Nepal hills.', 'SINO_TIBETAN', 'SAFE', 500000, 'Devanagari', 'Devanagari', 'Standard Gurung, Tsamang', false, false, 'HILL', 'Gandaki', 'Ancient Tibeto-Burman language. Gurungs served as soldiers in British and Indian armies.', 'Language of Gurung oral tradition, folk songs, and Buddhist rituals.', NULL, 'Gurung cultural associations and diaspora communities maintain the language.', NOW()),

('limbu', 'Limbu', 'Kiranti language of the Limbu people in eastern Nepal with its own historical script.', 'SINO_TIBETAN', 'SAFE', 350000, 'Limbu', 'Devanagari', 'Standard Limbu, Phedape, Chhatthare', false, false, 'HILL', 'Koshi', 'Ancient Kiranti language. Limbu script (Sirijonga) was developed in 19th century.', 'Language of Kiranti Mundhum tradition and Chasok Tangnam festival.', NULL, 'Sirijonga script revival movement. Limbi language in schools in some districts.', NOW()),

('sherpa', 'Sherpa', 'Tibeto-Burman language of the Sherpa people in high Himalayan regions.', 'SINO_TIBETAN', 'VULNERABLE', 200000, 'Tibetan', 'Devanagari', 'Standard Sherpa, Solu Sherpa', false, false, 'HIMALAYAN', 'Province 1', 'Related to Tibetan languages. Sherpas migrated from eastern Tibet several centuries ago.', 'Language of Sherpa Buddhist culture and mountaineering heritage.', NULL, 'Threatened by tourism-driven Nepali and English influence. Schools use Nepali.', NOW()),

('hindi', 'Hindi', 'Indo-Aryan language spoken by Madheshi and other communities with cultural ties to India.', 'INDO_ARYAN', 'SAFE', 200000, 'Devanagari', 'Devanagari', 'Standard Hindi, Bhojpuri-Hindi', false, false, 'TERAI', 'Province 2', 'Standardized form of Hindustani. Widely understood through Indian media.', 'Medium of cultural exchange with India. Bollywood influence significant.', NULL, 'Widely understood through Indian media and education.', NOW()),

('urdu', 'Urdu', 'Language of the Muslim community in Nepal with Perso-Arabic script tradition.', 'INDO_ARYAN', 'SAFE', 200000, 'Perso-Arabic', 'Perso-Arabic', 'Standard Urdu', false, false, 'TERAI', 'Multiple', 'Developed in South Asian Muslim cultural centers. Closely related to Hindi in spoken form.', 'Language of Islamic scholarship and Muslim cultural identity in Nepal.', NULL, 'Madrasas and Muslim cultural organizations maintain the language.', NOW()),

('bengali', 'Bengali', 'Indo-Aryan language spoken in eastern Nepal Terai and by Bengali-origin communities.', 'INDO_ARYAN', 'SAFE', 200000, 'Bengali', 'Devanagari', 'Standard Bengali', false, false, 'TERAI', 'Province 1', 'Eastern Indo-Aryan language with rich literary tradition from Bengal.', 'Connected to Bengali cultural festivals and literary tradition.', NULL, 'Community schools and cultural organizations.', NOW()),

('santhali', 'Santhali', 'Austroasiatic language of the Santhal people in Nepal Terai.', 'OTHER', 'SAFE', 150000, 'Ol Chiki', 'Devanagari', 'Standard Santhali', false, false, 'TERAI', 'Province 1', 'Part of the Munda branch of Austroasiatic family. Ol Chiki script invented in 1925.', 'Language of Santhal folk music, dance (Chhau), and harvest festivals.', NULL, 'Growing use of Ol Chiki script. Cultural organizations active.', NOW()),

('chamling', 'Chamling', 'Kiranti language of the Chamling people in eastern Nepal hills.', 'SINO_TIBETAN', 'VULNERABLE', 100000, 'Devanagari', 'Devanagari', 'Standard Chamling', false, false, 'HILL', 'Koshi', 'Ancient Kiranti language with roots in eastern Nepal.', 'Language of Kirant religious practices and Chamling oral tradition.', NULL, 'Endangered by Nepali and Rai dominance. Limited written materials.', NOW()),

('sunuwar', 'Sunuwar', 'Kiranti language of the Sunuwar (Koche) people in eastern Nepal.', 'SINO_TIBETAN', 'VULNERABLE', 80000, 'Devanagari', 'Devanagari', 'Standard Sunuwar', false, false, 'HILL', 'Province 1', 'Kiranti language with distinct phonological features.', 'Connected to Sunuwar identity and Mundhum oral tradition.', NULL, 'Limited documentation. Community efforts underway.', NOW()),

('thakali', 'Thakali', 'Tibeto-Burman language of the Thakali people from the Kali Gandaki region.', 'SINO_TIBETAN', 'VULNERABLE', 70000, 'Devanagari', 'Devanagari', 'Standard Thakali', false, false, 'HIMALAYAN', 'Gandaki', 'Language of salt-trading Thakali merchants from the Kali Gandaki corridor.', 'Language of Thakali culinary and trade culture. Tiji festival language.', NULL, 'Declining due to Nepali and tourism influence in Mustang corridor.', NOW()),

('rajbanshi', 'Rajbanshi', 'Indo-Aryan language of the Rajbanshi people in eastern Terai and hills.', 'INDO_ARYAN', 'SAFE', 100000, 'Bengali', 'Devanagari', 'Standard Rajbanshi', false, false, 'TERAI', 'Province 1', 'Language of indigenous Rajbanshi communities with historical kingdoms.', 'Language of Bihu festivals and agricultural traditions.', NULL, 'Growing awareness through cultural revival movements.', NOW()),

('chepang', 'Chepang', 'Tibeto-Burman language of the semi-nomadic Chepang people.', 'SINO_TIBETAN', 'VULNERABLE', 50000, 'Devanagari', 'Devanagari', 'Standard Chepang', false, false, 'HILL', 'Bagmati', 'Language of the forest-dwelling Chepang people with minimal outside contact historically.', 'Central to Chepang identity and their unique animistic rituals.', NULL, 'Threatened by displacement and education in Nepali only.', NOW()),

('danuwar', 'Danuwar', 'Tibeto-Burman language of the Danuwar people in the Terai-Hill transition zone.', 'SINO_TIBETAN', 'VULNERABLE', 30000, 'Devanagari', 'Devanagari', 'Standard Danuwar', false, false, 'TERAI', 'Province 1', 'Minor Tibeto-Burman language with declining speaker base.', 'Language of Danuwar fishing and riverine culture.', NULL, 'Rapidly declining. Limited documentation available.', NOW()),

('majhi', 'Majhi', 'Tibeto-Burman language of the Majhi boatmen communities along major rivers.', 'SINO_TIBETAN', 'VULNERABLE', 25000, 'Devanagari', 'Devanagari', 'Standard Majhi', false, false, 'HILL', 'Bagmati', 'Language of river-dwelling Majhi communities traditionally engaged in ferry services.', 'Connected to riverine culture and traditional boat-making.', NULL, 'Declining as river transport diminishes.', NOW()),

('meche', 'Meche', 'Kiranti language of the Meche people in eastern Nepal.', 'SINO_TIBETAN', 'VULNERABLE', 20000, 'Devanagari', 'Devanagari', 'Standard Meche', false, false, 'HILL', 'Province 1', 'Small Kiranti language with close ties to other eastern Kiranti languages.', 'Language of Meche identity and traditional practices.', NULL, 'Endangered. Very limited written materials.', NOW()),

('bhote', 'Bhote', 'Tibeto-Burman language of Bhote communities in high Himalayan areas.', 'SINO_TIBETAN', 'VULNERABLE', 15000, 'Tibetan', 'Devanagari', 'Standard Bhote', false, false, 'HIMALAYAN', 'Bagmati', 'Related to Tibetan. Bhote communities are traditionally pastoral and trade-oriented.', 'Connected to Tibetan Buddhist culture and high-altitude pastoral life.', NULL, 'Declining due to modernization and low population.', NOW()),

('jirel', 'Jirel', 'Kiranti language of the Jirel people in eastern Nepal.', 'SINO_TIBETAN', 'VULNERABLE', 15000, 'Devanagari', 'Devanagari', 'Standard Jirel', false, false, 'HILL', 'Province 1', 'Kiranti language closely related to other eastern Nepal Tibeto-Burman languages.', 'Language of Jirel community identity and oral tradition.', NULL, 'Limited documentation. Community speakers declining.', NOW()),

('hayu', 'Hayu', 'Kiranti language of the Hayu people in central-eastern Nepal hills.', 'SINO_TIBETAN', 'DEFINITELY_ENDANGERED', 10000, 'Devanagari', 'Devanagari', 'Standard Hayu', false, false, 'HILL', 'Province 1', 'Ancient Kiranti language with limited geographic distribution.', 'Language of Hayu religious ceremonies and cultural practices.', NULL, 'Fewer than 10,000 speakers. Children increasingly speak Nepali.', NOW()),

('lepcha', 'Lepcha', 'Sino-Tibetan language with its own unique script, spoken near Nepal-India-Sikkim borders.', 'SINO_TIBETAN', 'DEFINITELY_ENDANGERED', 10000, 'Lepcha', 'Lepchabel', 'Standard Lepcha', false, false, 'HIMALAYAN', 'Province 1', 'Ancient language with the Lepcha script dating to 17th century or earlier.', 'Language of Lepcha cultural heritage and Buddhist traditions in the Kanchenjunga region.', NULL, 'Critically low number of fluent speakers. Script preservation efforts ongoing.', NOW()),

('kusunda', 'Kusunda', 'Language isolate with no known relatives. Spoken by fewer than 40 people in western Nepal.', 'KUSUNDA', 'CRITICALLY_ENDANGERED', 32, 'None', 'None', 'None', false, false, 'HILL', 'Gandaki', 'One of the world great mysteries - a language isolate with no known linguistic relatives. Possibly pre-Tibeto-Burman and pre-Indo-Aryan.', 'Irreplaceable linguistic heritage. Represents potential pre-Neolithic language layer of South Asia.', 'Fewer than 40 fluent speakers remain. Most are elderly. Language could die within a generation.', 'Documentation by linguists from Tribhuvan University. International academic interest.', NOW()),

('dumi', 'Dumi', 'Kiranti language of the Dumi people in eastern Nepal hills.', 'SINO_TIBETAN', 'SEVERELY_ENDANGERED', 8000, 'Devanagari', 'Devanagari', 'Standard Dumi', false, false, 'HILL', 'Province 1', 'Small Kiranti language with unique phonological features.', 'Language of Dumi oral tradition and Kirant rituals.', NULL, 'Under 8,000 speakers. Dominance of larger neighboring languages.', NOW()),

('kulung', 'Kulung', 'Kiranti language of the Kulung people in eastern Nepal.', 'SINO_TIBETAN', 'VULNERABLE', 25000, 'Devanagari', 'Devanagari', 'Standard Kulung', false, false, 'HILL', 'Province 1', 'Eastern Kiranti language with its own Mundhum oral literature.', 'Connected to Kirant religious practices and Kulung community identity.', NULL, 'Moderately stable but faces pressure from Nepali.', NOW()),

('chhintang', 'Chhintang', 'Kiranti language of the Chhintang people in eastern Nepal.', 'SINO_TIBETAN', 'SEVERELY_ENDANGERED', 2000, 'Devanagari', 'Devanagari', 'Standard Chhintang', false, false, 'HILL', 'Province 1', 'One of the smallest Kiranti languages by speaker population.', 'Language of Chhintang identity and rituals.', NULL, 'Severely endangered. Most speakers are elderly.', NOW()),

('vayu', 'Vayu', 'Kiranti language of the Vayu people in eastern Nepal.', 'SINO_TIBETAN', 'DEFINITELY_ENDANGERED', 2000, 'Devanagari', 'Devanagari', 'Standard Vayu', false, false, 'HILL', 'Province 1', 'Ancient Kiranti language with declining speaker base.', 'Connected to traditional Vayu religious practices.', NULL, 'Endangered. Younger generation shifting to Nepali.', NOW()),

('lhomi', 'Lhomi', 'Tibeto-Burman language of the Lhomi people in high-altitude regions.', 'SINO_TIBETAN', 'DEFINITELY_ENDANGERED', 2000, 'Tibetan', 'Devanagari', 'Standard Lhomi', false, false, 'HIMALAYAN', 'Province 1', 'Language of high-altitude communities with Tibetan cultural connections.', 'Connected to Buddhist rituals and pastoral life in high Himalayas.', NULL, 'Declining due to low population and modernization.', NOW()),

('nar-phu', 'Nar-Phu', 'Tibeto-Burman language of the Nar and Phu valley communities.', 'SINO_TIBETAN', 'DEFINITELY_ENDANGERED', 1000, 'Tibetan', 'Devanagari', 'Nar dialect, Phu dialect', false, false, 'HIMALAYAN', 'Gandaki', 'Language of isolated valleys in the Manang district. Highly conservative linguistically.', 'Language of unique high-altitude Buddhist culture.', NULL, 'Very small speaker population in remote valleys.', NOW()),

('gyalsumdo', 'Gyalsumdo', 'Tibeto-Burman language of the Gyalsumdo people in the Manaslu region.', 'SINO_TIBETAN', 'SEVERELY_ENDANGERED', 500, 'Tibetan', 'Devanagari', 'Standard Gyalsumdo', false, false, 'HIMALAYAN', 'Gandaki', 'Language of an extremely small community in the Manaslu Conservation Area.', 'Represents unique linguistic heritage of the Manaslu region.', NULL, 'Critically few speakers. Nearly extinct.', NOW()),

('kham-magar', 'Kham Magar', 'Western Magar dialect cluster spoken in remote hill areas of western Nepal.', 'SINO_TIBETAN', 'VULNERABLE', 40000, 'Devanagari', 'Devanagari', 'Kham dialects', false, false, 'HILL', 'Gandaki', 'Ancient dialect cluster distinct from standard Magar.', 'Language of Kham cultural traditions and oral literature.', NULL, 'Faces pressure from standard Magar and Nepali.', NOW()),

('kumhali', 'Kumhali', 'Indo-Aryan language of the Kumhali potter community.', 'INDO_ARYAN', 'VULNERABLE', 2000, 'Devanagari', 'Devanagari', 'Standard Kumhali', false, false, 'TERAI', 'Province 2', 'Language of the traditional potter caste in the Terai.', 'Connected to pottery traditions and craft heritage.', NULL, 'Very few speakers. Rapidly shifting to Maithili and Nepali.', NOW()),

('bankaria', 'Bankaria', 'Tibeto-Burman language of the Bankaria people in eastern hills.', 'SINO_TIBETAN', 'DEFINITELY_ENDANGERED', 5000, 'Devanagari', 'Devanagari', 'Standard Bankaria', false, false, 'HILL', 'Province 1', 'Small Tibeto-Burman language with limited distribution.', 'Language of Bankaria community identity.', NULL, 'Declining. Few young speakers.', NOW()),

('puma', 'Puma', 'Tibeto-Burman language of the Puma people in eastern Nepal.', 'SINO_TIBETAN', 'VULNERABLE', 5000, 'Devanagari', 'Devanagari', 'Standard Puma', false, false, 'HILL', 'Province 1', 'Tibeto-Burman language with Kiranti connections.', 'Language of Puma cultural identity and practices.', NULL, 'Moderately endangered. Community efforts to maintain.', NOW()),

('tilung', 'Tilung', 'Kiranti language of the Tilung people in eastern Nepal.', 'SINO_TIBETAN', 'SEVERELY_ENDANGERED', 500, 'Devanagari', 'Devanagari', 'Standard Tilung', false, false, 'HILL', 'Province 1', 'One of the smallest Kiranti languages.', 'Language of Tilung identity, nearly lost.', NULL, 'Critically endangered. Almost no young speakers.', NOW()),

('yakkha', 'Yakkha', 'Kiranti language of the Yakkha people in eastern Nepal hills.', 'SINO_TIBETAN', 'VULNERABLE', 15000, 'Devanagari', 'Devanagari', 'Standard Yakkha', false, false, 'HILL', 'Province 1', 'Kiranti language with close relationship to Chamling.', 'Language of Yakkha community and Kirant traditions.', NULL, 'Declining but community programs exist.', NOW()),

('dhimal', 'Dhimal', 'Tibeto-Burman language of the Dhimal people in eastern Terai-Hill transition.', 'SINO_TIBETAN', 'VULNERABLE', 30000, 'Devanagari', 'Devanagari', 'Standard Dhimal', false, false, 'TERAI', 'Province 1', 'Language of the Dhimal people with unique linguistic features.', 'Connected to Dhimal weaving traditions and folk culture.', NULL, 'Declining due to Maithili and Nepali influence.', NOW()),

('rabha', 'Rabha', 'Tibeto-Burman language of the Rabha people in eastern Nepal.', 'SINO_TIBETAN', 'VULNERABLE', 20000, 'Devanagari', 'Devanagari', 'Standard Rabha', false, false, 'TERAI', 'Province 1', 'Language of Rabha communities in Nepal and neighboring Indian states.', 'Connected to Baisagu festival and Rabha cultural traditions.', NULL, 'Pressure from larger neighboring languages.', NOW()),

('kisan', 'Kisan', 'Indo-Aryan language of the Kisan (Santal-related) communities in Nepal.', 'INDO_ARYAN', 'VULNERABLE', 10000, 'Devanagari', 'Devanagari', 'Standard Kisan', false, false, 'TERAI', 'Province 1', 'Language of small farming communities in the eastern Terai.', 'Connected to agricultural traditions and folk music.', NULL, 'Declining. Most speakers also speak Nepali.', NOW()),

('bhujel', 'Bhujel', 'Tibeto-Burman language of the Bhujel people in eastern Nepal.', 'SINO_TIBETAN', 'VULNERABLE', 15000, 'Devanagari', 'Devanagari', 'Standard Bhujel', false, false, 'HILL', 'Province 1', 'Tibeto-Burman language with limited geographic spread.', 'Language of Bhujel community identity.', NULL, 'Declining. Limited institutional support.', NOW()),

('waling', 'Waling', 'Kiranti language of the Waling people in eastern Nepal.', 'SINO_TIBETAN', 'DEFINITELY_ENDANGERED', 2000, 'Devanagari', 'Devanagari', 'Standard Waling', false, false, 'HILL', 'Province 1', 'Small Kiranti language with declining speakers.', 'Language of Waling cultural practices.', NULL, 'Endangered. Few speakers under 40.', NOW()),

('phangduwali', 'Phangduwali', 'Kiranti language of the Phangduwali people, one of the smallest language communities.', 'SINO_TIBETAN', 'CRITICALLY_ENDANGERED', 200, 'Devanagari', 'Devanagari', 'Standard Phangduwali', false, false, 'HILL', 'Province 1', 'One of the most critically endangered languages in Nepal.', 'Represents a unique linguistic lineage facing imminent extinction.', NULL, 'Fewer than 200 speakers. Urgent documentation needed.', NOW()),

('punjabi', 'Punjabi', 'Indo-Aryan language of Punjabi-origin communities in Nepal.', 'INDO_ARYAN', 'SAFE', 50000, 'Gurmukhi', 'Devanagari', 'Standard Punjabi', false, false, 'TERAI', 'Multiple', 'Language of Sikh and Punjabi diaspora communities in Nepal.', 'Connected to Punjabi cultural festivals and Bhangra music.', NULL, 'Maintained by diaspora communities and Indian media.', NOW());

-- =============================================
-- ETHNIC GROUPS (IDs 1-50, language_id references Languages above)
-- =============================================
INSERT INTO ethnic_groups (slug, name, description, population_estimate, language_id, region_type, province, sub_region, traditional_occupation, social_structure, religion, customs, rituals, festivals, is_indigenous, is_deprived, origin, migration_history, created_at) VALUES

('chhettri', 'Chhettri', 'Largest ethnic group in Nepal. Traditionally Kshatriya caste engaged in agriculture and military service.', 4398000, 1, 'HILL', 'Multiple', 'Pan-Nepal hills', 'Agriculture, Military service', 'Caste system - Kshatriya varna', 'Hindu', 'Dashain and Tihar are the most important festivals. Strong family bonds and patrilineal descent.', 'Navratri worship, Jamara growing, Tikka ceremony', 'Dashain, Tihar, Maghe Sankranti', true, false, 'Descended from Khas people of western Nepal hills. Rose to prominence during Gorkha unification.', 'Migrated across Nepal during Shah dynasty expansion. Now present in all hill districts.', NOW()),

('brahman-hill', 'Brahman (Hill)', 'Hill Brahmin community serving as priests and scholars. Second largest group in Nepal.', 3225000, 1, 'HILL', 'Multiple', 'Pan-Nepal hills', 'Priesthood, Agriculture, Teaching', 'Caste system - Brahmin varna', 'Hindu', 'Strict vegetarianism in many families. Sacred thread ceremony. Sandhya prayer rituals.', 'Hawan/puja rituals, Brahmin marriage ceremonies', 'Dashain, Tihar, Shivaratri, Janai Purnima', true, false, 'Descended from Vedic Brahmin lineage. Settled in Nepal hills for millennia.', 'Historically established in Kathmandu Valley and western hills. Spread across all hill regions.', NOW()),

('magar', 'Magar', 'One of the largest indigenous groups with a distinct Tibeto-Burman language and rich oral traditions.', 1622000, 8, 'HILL', 'Gandaki', 'Western and Central hills', 'Agriculture, Military service', 'Tribal system with village councils', 'Hindu/Buddhist syncretism', 'Strong community bonds through Guthi system. Traditional warrior culture.', ' ancestor worship, shamanic rituals', 'Maghe Sankranti, Dashain, Tihar', true, false, 'Ancient Tibeto-Burman people of central Nepal hills. Historically served as Gorkha soldiers.', 'Primarily inhabit Gandaki and Dhaulagiri regions. Migrated to urban areas in modern times.', NOW()),

('tharu', 'Tharu', 'Indigenous people of the Terai lowlands with unique cultural traditions and stick dance.', 1533000, 4, 'TERAI', 'Lumbini', 'Dang, Banke, Kailali, Rupandehi', 'Agriculture, Fishing, Forest collection', 'Clan-based tribal system', 'Hindu/Animist syncretism', 'Joint family system. Traditional Tharu houses with mud plaster art. Strong forest connection.', 'Jitiya ritual, Bhuiya puja (earth worship)', 'Jitiya, Maghi, Holi, Govardhan Puja', true, false, 'Claim descent from Rajput warriors who fled to Terai to escape Mughal invasions.', 'Ancient inhabitants of Terai. Various Tharu sub-groups across the Terai belt.', NOW()),

('tamang', 'Tamang', 'Largest indigenous hill group with a strong Buddhist cultural tradition and Tamang Selo music.', 1539000, 5, 'HILL', 'Bagmati', 'Central and Eastern hills', 'Agriculture, Porter service, Masonry', 'Tribal system with Lama religious leaders', 'Buddhist/Tengriism', 'Buddhist Lama ceremonies. Traditional Tamang settlements on hilltops.', 'Lama priest rituals, Buddhist prayer ceremonies', 'Tamang Lhosar, Dashain, Tihar', true, false, 'Ancient Tibeto-Burman people. Tamang means horse-people in their language.', 'Historically inhabited central Nepal hills around Kathmandu Valley rim.', NOW()),

('newar', 'Newar', 'Indigenous people of the Kathmandu Valley with a highly developed urban civilization and artisan traditions.', 1321000, 6, 'URBAN', 'Bagmati', 'Kathmandu Valley', 'Trade, Metalwork, Pottery, Weaving', 'Complex caste and clan system', 'Buddhist/Hindu dual tradition', 'Elaborate lifecycle rituals. Guthi land system for community festivals. Distinct architecture.', 'Ihi (bel marriage), Bara Tayegu, death rituals', 'Indra Jatra, Yomari Punhi, Bisket Jatra, Machhindranath Jatra', false, false, 'Descended from ancient Kathmandu Valley inhabitants. Developed Newar civilization over 2000+ years.', 'Indigenous to Kathmandu Valley. Never migrated en masse from elsewhere.', NOW()),

('kami', 'Kami', 'Dalit community traditionally engaged in blacksmithing. Part of the Hill Dalit population.', 825000, 1, 'HILL', 'Multiple', 'Pan-Nepal hills', 'Blacksmithing, Metalwork', 'Caste system - Dalit (Kami sub-caste)', 'Hindu', 'Traditional metalworking craft. Face social discrimination despite Hindu integration.', 'Dying rituals', 'Dashain, Tihar', true, true, 'Dalit community with traditional blacksmithing occupation.', 'Present across all hill districts as hereditary artisans.', NOW()),

('muslim', 'Muslim', 'Muslim community concentrated in the Terai region with cultural ties to broader Islamic world.', 1164000, 15, 'TERAI', 'Multiple', 'Pan-Terai', 'Agriculture, Trade, Textile', 'Religious community structure', 'Islam', 'Mosque-centered community life. Halal food practices. Strong family and community bonds.', 'Namaz (prayer), Quran recitation, Muharram processions', 'Eid al-Fitr, Eid al-Adha, Muharram, Shab-e-Barat', false, false, 'Descended from Muslim settlers, traders, and soldiers who came to Nepal over centuries.', 'Historical migration from India and Central Asia. Concentrated in Terai districts.', NOW()),

('yadav', 'Yadav', 'Major Terai caste group engaged in agriculture and dairy farming.', 1019000, 14, 'TERAI', 'Province 2', 'Central Terai', 'Agriculture, Dairy farming, Business', 'Caste system - Kshatriya varna', 'Hindu', 'Krishna-worshipping community. Strong caste identity and agricultural traditions.', 'Krishna Janmashtami rituals, cow worship', 'Chhath Puja, Krishna Janmashtami, Holi', false, false, 'Claim descent from Yadu dynasty of ancient India.', 'Migration from northern Indian plains to Nepal Terai over centuries.', NOW()),

('rai', 'Rai', 'Diverse Kiranti indigenous group with multiple sub-groups, each with distinct languages and traditions.', 620000, 10, 'HILL', 'Koshi', 'Eastern hills', 'Agriculture, Terrace farming', 'Tribal system with Mundhum priests', 'Kirat (Animist/Hindu)', 'Mundhum oral tradition. Strong connection to nature. Sakela dance tradition.', 'Nakchong (shaman) rituals, Mundhum recitation', 'Sakela/Sakewa, Ubhauli, Kirat festivals', true, false, 'Ancient Kiranti people predating Indo-Aryan migration. One of Nepal most ancient groups.', 'Inhabited eastern Nepal hills since pre-history. Multiple sub-groups in Koshi Province.', NOW()),

('gurung', 'Gurung', 'Indigenous hill people known for Gurung culture, Buddhism, and service in Gurkha regiments.', 522000, 11, 'HILL', 'Gandaki', 'Annapurna, Lamjung, Gorkha', 'Agriculture, Military service, Tourism', 'Tribal system with Lama priests', 'Buddhist', 'Strong Gurung community identity. Tuladhara and Ghale naming traditions.', 'Lama priest ceremonies, Buddhist prayers', 'Gurung Lhosar, Dashain, Tihar', true, false, 'Tibeto-Burman people with distinct cultural identity. Name derived from Gurung/Ghale.', 'Inhabited central Nepal hills around Annapurna and Manaslu regions.', NOW()),

('limbu', 'Limbu', 'Kiranti indigenous people of eastern Nepal with their own script and Mundhum tradition.', 408000, 12, 'HILL', 'Koshi', 'Eastern hills (Limbuwan)', 'Agriculture, Animal husbandry', 'Tribal system with Nakchong priests', 'Kirat/Animist', 'Mundhum oral tradition. Strong clan (Subba) system. Traditional Limbu script.', 'Mundhum recitation, Nakchong rituals, Dharma traditions', 'Chasok Tangnam, Ubhauli, Limbu festivals', true, false, 'Ancient Kiranti people. Limbuwan was a semi-independent kingdom before Gorkha annexation.', 'Inhabited eastern hills (historical Limbuwan) since ancient times.', NOW()),

('thakuri', 'Thakuri', 'Kshatriya community claiming descent from ruling dynasties of ancient Nepal.', 314000, 1, 'HILL', 'Multiple', 'Pan-Nepal hills', 'Agriculture, Government service, Military', 'Caste system - Kshatriya', 'Hindu', 'Royal lineage traditions. Strong emphasis on education and social status.', 'Royal ceremony re-enactments, ancestor worship', 'Dashain, Tihar, Dashami', true, false, 'Descended from Malla and other ruling dynasties of Nepal.', 'Scattered across Nepal hills as former ruling class families.', NOW()),

('damai-dholi', 'Damai/Dholi', 'Dalit community traditionally engaged in tailoring and music. Known for playing traditional instruments.', 307000, 1, 'HILL', 'Multiple', 'Pan-Nepal hills', 'Tailoring, Music (madal, sarangi)', 'Caste system - Dalit', 'Hindu', 'Traditional musicians at festivals and ceremonies. Tailoring as hereditary occupation.', 'Dashain, Tihar', 'Dashain, Tihar, wedding music performances', true, true, 'Dalit community with hereditary musician and tailor roles.', 'Present across all hill districts serving as traditional musicians.', NOW()),

('sarki', 'Sarki', 'Dalit community traditionally engaged in leather working.', 267000, 1, 'HILL', 'Multiple', 'Pan-Nepal hills', 'Leather work, Cobbling', 'Caste system - Dalit', 'Hindu', 'Face significant social discrimination. Traditional leather-working craft.', 'Limited festive participation due to caste restrictions', 'Dashain, Tihar', true, true, 'Dalit community with traditional leather-working occupation.', 'Present across hill districts as hereditary leather workers.', NOW()),

('tel', 'Teli', 'Caste group traditionally engaged in oil pressing and trading.', 239000, 1, 'HILL', 'Multiple', 'Pan-Nepal', 'Oil pressing, Trading', 'Caste system - Vaishya', 'Hindu', 'Traditional oil pressing craft. Trading community.', 'Dashain, Tihar', 'Dashain, Tihar, Maghe Sankranti', false, false, 'Traditional oil-pressing caste.', 'Present across Nepal.', NOW()),

('chamar', 'Chamar', 'Dalit community in the Terai region with significant population.', 214000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Leather work, Agriculture', 'Caste system - Dalit', 'Hindu', 'Face social discrimination. Traditional leather-working occupation.', 'Chhath Puja, Dashain', 'Chhath Puja, Dashain', true, true, 'Dalit community with traditional leather-working occupation.', 'Concentrated in central Terai districts.', NOW()),

('koiri', 'Koiri', 'Maithili-speaking caste group engaged in agriculture in the Terai.', 176000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Agriculture, Farming', 'Caste system - Vaishya', 'Hindu', 'Agricultural community with strong Maithili cultural ties.', 'Chhath Puja, Makar Sankranti', 'Chhath Puja, Holi, Diwali', false, false, 'Traditional agricultural caste of the Mithila region.', 'Concentrated in Province 2 Terai districts.', NOW()),

('musahar', 'Musahar', 'Dalit community in the Terai, historically among the most marginalized groups.', 172000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Agriculture, Labor', 'Caste system - Dalit (most marginalized)', 'Hindu', 'Historically extremely marginalized. Rising educational awareness.', 'Limited festive participation', 'Chhath Puja, Holi', true, true, 'Among the most marginalized Dalit groups in Nepal.', 'Concentrated in Province 2. Subject of numerous social upliftment programs.', NOW()),

('kewat', 'Kewat', 'Fishing community in the Terai region.', 166000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Fishing, Boat-making', 'Caste system - Other Backward Caste', 'Hindu', 'River-based culture and fishing traditions.', 'Chhath Puja (water-based rituals)', 'Chhath Puja, Holi', false, false, 'Traditional fishing community of the Terai.', 'Concentrated along river systems in Province 2.', NOW()),

('sonar', 'Sonar', 'Goldsmith community engaged in jewelry making.', 140000, 1, 'HILL', 'Multiple', 'Pan-Nepal', 'Goldsmithing, Jewelry making', 'Caste system - Vaishya', 'Hindu', 'Traditional gold and silver jewelry craft.', 'Dashain, Tihar', 'Dashain, Tihar, festival jewelry', false, false, 'Traditional goldsmith caste.', 'Present across Nepal in urban and semi-urban areas.', NOW()),

('lohar', 'Lohar', 'Blacksmith community traditionally engaged in iron and metal work.', 144000, 1, 'HILL', 'Multiple', 'Pan-Nepal', 'Blacksmithing, Iron work', 'Caste system - Dalit', 'Hindu', 'Traditional iron working. Face social discrimination.', 'Dashain', 'Dashain, Tihar', true, true, 'Dalit community with hereditary blacksmithing.', 'Present across hill districts.', NOW()),

('kurmi', 'Kurmi', 'Agricultural caste group in the Terai with ties to eastern India.', 137000, 14, 'TERAI', 'Province 2', 'Central Terai', 'Agriculture, Farming', 'Caste system - Other Backward Caste', 'Hindu', 'Agricultural community with strong farming traditions.', 'Chhath Puja, Makar Sankranti', 'Chhath Puja, Holi, Diwali', false, false, 'Agricultural caste from Mithila and Bihar traditions.', 'Concentrated in Province 2.', NOW()),

('kumhar', 'Kumhar', 'Potter community engaged in traditional pottery.', 134000, 1, 'HILL', 'Multiple', 'Pan-Nepal', 'Pottery, Clay work', 'Caste system - Other Backward Caste', 'Hindu', 'Traditional pottery craft. Many face declining demand.', 'Dashain, Tihar', 'Dashain, Tihar, Pottery festivals', false, false, 'Traditional pottery caste.', 'Present across Nepal.', NOW()),

('dhobi', 'Dhobi', 'Community traditionally engaged in laundry and washing.', 129000, 1, 'HILL', 'Multiple', 'Pan-Nepal', 'Laundry, Washing', 'Caste system - Dalit', 'Hindu', 'Traditional laundry occupation. Face social discrimination.', 'Dashain', 'Dashain, Tihar', true, true, 'Dalit community with traditional laundry occupation.', 'Present across hill districts.', NOW()),

('mallaha', 'Mallaha', 'Maithili-speaking agricultural community in the Terai.', 107000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Agriculture, Farming', 'Caste system - Other Backward Caste', 'Hindu', 'Agricultural community with Maithili cultural traditions.', 'Chhath Puja, Makar Sankranti', 'Chhath Puja, Holi', false, false, 'Traditional agricultural community.', 'Concentrated in Province 2.', NOW()),

('nuniya', 'Nuniya', 'Caste group engaged in salt trade and agriculture in the Terai.', 94000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Salt trade, Agriculture', 'Caste system - Other Backward Caste', 'Hindu', 'Historical salt traders.', 'Chhath Puja', 'Chhath Puja, Holi', false, false, 'Traditional salt-trading community.', 'Concentrated in Province 2.', NOW()),

('haluwai', 'Haluwai', 'Sweet-making community in the Terai.', 92000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Sweet making, Confectionery', 'Caste system - Other Backward Caste', 'Hindu', 'Traditional sweet-making craft.', 'Chhath Puja, festive sweets', 'Chhath Puja, Dashain', false, false, 'Traditional confectionery community.', 'Concentrated in Province 2.', NOW()),

('kanu', 'Kanu', 'Agricultural community in the Terai with strong caste identity.', 133000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Agriculture, Farming', 'Caste system - Other Backward Caste', 'Hindu', 'Strong agricultural traditions.', 'Chhath Puja, Makar Sankranti', 'Chhath Puja, Holi', false, false, 'Agricultural caste of the Terai.', 'Concentrated in Province 2.', NOW()),

('kashyap', 'Kashyap', 'Brahmin sub-group with historical priestly role.', 80000, 1, 'HILL', 'Multiple', 'Pan-Nepal', 'Priesthood, Agriculture', 'Caste system - Brahmin', 'Hindu', 'Vedic rituals and priestly traditions.', 'All Hindu festivals', 'Dashain, Tihar, Shivaratri', false, false, 'Brahmin lineage tracing to Kashyap gotra.', 'Present across Nepal hills.', NOW()),

('kalwar', 'Kalwar', 'Community traditionally engaged in liquor distillation.', 76000, 1, 'HILL', 'Multiple', 'Pan-Nepal', 'Liquor making, Distillation', 'Caste system - Other Backward Caste', 'Hindu', 'Traditional liquor-making craft.', 'Dashain, Tihar', 'Dashain, Tihar', false, false, 'Traditional liquor-distilling caste.', 'Present across Nepal.', NOW()),

('tatwa', 'Tatwa/Tat', 'Weaving community engaged in traditional textile production.', 71000, 1, 'HILL', 'Multiple', 'Pan-Nepal', 'Weaving, Textile production', 'Caste system - Other Backward Caste', 'Hindu', 'Traditional handloom weaving.', 'Dashain, Tihar', 'Dashain, Tihar, weaving festivals', false, false, 'Traditional weaving caste.', 'Present across Nepal.', NOW()),

('badhaee', 'Badhaee', 'Agricultural community in the Terai.', 58000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Agriculture', 'Caste system - Other Backward Caste', 'Hindu', 'Agricultural traditions.', 'Chhath Puja', 'Chhath Puja, Holi', false, false, 'Agricultural caste.', 'Concentrated in Province 2.', NOW()),

('chamaare', 'Chamaare', 'Dalit community engaged in leather work in the Terai.', 54000, 1, 'TERAI', 'Multiple', 'Pan-Terai', 'Leather work', 'Caste system - Dalit', 'Hindu', 'Traditional leather-working. Face significant discrimination.', 'Dashain', 'Dashain, Holi', true, true, 'Dalit community with leather-working heritage.', 'Present across Terai districts.', NOW()),

('gaine', 'Gaine/Gandarbhe', 'Dalit community of traditional traveling musicians and bards.', 50000, 1, 'HILL', 'Multiple', 'Pan-Nepal', 'Music (sarangi), Storytelling', 'Caste system - Dalit', 'Hindu', 'Traditional traveling minstrels. Keepers of folk histories through song.', 'Wedding performances, festival music', 'Dashain, Tihar, wedding ceremonies', true, true, 'Dalit community of hereditary musicians and storytellers.', 'Nomadic tradition across Nepal hills.', NOW()),

('badi', 'Badi', 'Dalit community traditionally engaged in music and entertainment.', 46000, 1, 'HILL', 'Multiple', 'Pan-Nepal', 'Music, Entertainment', 'Caste system - Dalit', 'Hindu', 'Traditional musicians. Face social marginalization.', 'Dashain', 'Dashain, Tihar', true, true, 'Dalit community of traditional performers.', 'Present across Nepal hills.', NOW()),

('dom', 'Dom', 'Dalit community in the Terai engaged in menial occupations.', 38000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Menial work, Labor', 'Caste system - Dalit', 'Hindu', 'Face extreme social discrimination.', 'Dashain', 'Dashain, Chhath Puja', true, true, 'Among the most marginalized communities.', 'Concentrated in Province 2.', NOW()),

('pode', 'Pode', 'Dalit community traditionally engaged in sweeping and sanitation.', 33000, 1, 'HILL', 'Multiple', 'Pan-Nepal', 'Sweeping, Sanitation', 'Caste system - Dalit', 'Hindu', 'Face severe social discrimination. Traditional sanitation role.', 'Dashain', 'Dashain, Tihar', true, true, 'Dalit community with traditional sanitation role.', 'Present across hill districts.', NOW()),

('chaure', 'Chaure', 'Agricultural community in the Terai.', 14000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Agriculture', 'Caste system - Other Backward Caste', 'Hindu', 'Agricultural traditions.', 'Chhath Puja', 'Chhath Puja', false, false, 'Small agricultural caste.', 'Concentrated in Province 2.', NOW()),

('halkhor', 'Halkhor', 'Dalit community in the Terai.', 12000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Menial work', 'Caste system - Dalit', 'Hindu', 'Face severe discrimination.', 'Dashain', 'Dashain', true, true, 'Marginalized Dalit community.', 'Concentrated in Province 2.', NOW()),

('dusadh', 'Dusadh', 'Dalit community in the Terai with growing political awareness.', 16000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Agriculture, Labor', 'Caste system - Dalit', 'Hindu', 'Rising political consciousness and social movements.', 'Chhath Puja, Dashain', 'Chhath Puja, Dashain', true, true, 'Dalit community with emerging political identity.', 'Concentrated in Province 2.', NOW()),

('nat', 'Nat', 'Itinerant entertainment community in the Terai.', 14000, 2, 'TERAI', 'Province 2', 'Central Terai', 'Entertainment, Circus, Acrobatics', 'Caste system - Nomadic', 'Hindu', 'Traditional entertainment and performance arts.', 'Festival performances', 'Chhath Puja, Dashain performances', false, false, 'Traditional itinerant entertainers.', 'Nomadic across Terai districts.', NOW()),

('jogi', 'Jogi', 'Dalit community traditionally engaged in fortune telling and snake charming.', 30000, 1, 'HILL', 'Multiple', 'Pan-Nepal', 'Fortune telling, Snake charming', 'Caste system - Dalit', 'Hindu', 'Traditional fortune-telling and healing practices.', 'Dashain', 'Dashain, Tihar', true, true, 'Dalit community of traditional healers and fortune tellers.', 'Present across Nepal.', NOW()),

('chepang', 'Chepang', 'Semi-nomadic indigenous people of the inner Terai hills. Among the most marginalized.', 68000, 22, 'HILL', 'Bagmati', 'Chitwan, Makwanpur', 'Shifting cultivation, Hunting, Gathering', 'Tribal system', 'Animist/Hindu syncretism', 'Forest-based lifestyle. Traditional mud house construction. Strong animistic beliefs.', 'Bhuiya puja (earth worship), shamanic rituals', 'Bhume Puja, Dashain', true, true, 'One of Nepal most marginalized indigenous groups. Historically forest-dwelling.', 'Inhabited inner Terai hills (Chitwan, Makwanpur) since ancient times.', NOW()),

('raute', 'Raute', 'Nomadic hunter-gatherer community. Smallest nomadic group in Nepal.', 1500, 1, 'HILL', 'Karnali', 'Surkhet, Dailekh', 'Hunting, Gathering, Wood carving', 'Nomadic tribal system', 'Animist', 'Fully nomadic lifestyle. Live in temporary shelters. Trade wooden goods for grain.', 'Shamanic rituals', 'Traditional seasonal festivals', true, false, 'Among the last nomadic peoples of South Asia.', 'Nomadic across Surkhet and Dailekh districts in Karnali Province.', NOW()),

('rajbanshi', 'Rajbanshi', 'Indigenous Terai community with historical kingdom traditions.', 293000, 21, 'TERAI', 'Province 1', 'Jhapa, Morang', 'Agriculture, Weaving', 'Tribal/Kshatriya system', 'Hindu/Animist', 'Strong community identity. Traditional Bihu dance and festivals.', 'Harvest rituals, fertility rites', 'Bihu, Baisagu, Maghi', true, true, 'Claim descent from ancient Terai kingdoms.', 'Historical inhabitants of eastern Nepal Terai.', NOW()),

('meche', 'Meche', 'Small Kiranti community in eastern Nepal with unique cultural practices.', 8000, 25, 'HILL', 'Province 1', 'Taplejung', 'Agriculture, Forest collection', 'Tribal system', 'Animist/Hindu', 'Traditional forest-based practices.', 'Shamanic rituals', 'Traditional festivals', true, false, 'Small Kiranti community in eastern Nepal.', 'Inhabited Taplejung district since ancient times.', NOW()),

('bhote', 'Bhote', 'Tibetan-origin communities in high Himalayan regions.', 13000, 26, 'HIMALAYAN', 'Bagmati', 'Sindhupalchok, Dolakha', 'Trade, Pastoralism, yak herding', 'Tribal/Clan system', 'Tibetan Buddhist', 'Tibetan Buddhist culture. Yak herding and trans-Himalayan trade.', 'Monastery rituals, Buddhist prayers', 'Lhosar, Buddhist festivals', true, false, 'Tibetan-origin people who migrated to Nepal high Himalayas.', 'Migrated from Tibet over several centuries.', NOW()),

('kumale', 'Kumale', 'Newar community of the Kathmandu Valley with distinct artisan traditions.', 5000, 6, 'URBAN', 'Bagmati', 'Patan/Lalitpur', 'Metalwork, Artisan work', 'Newar caste system', 'Buddhist/Hindu', 'Skilled metalworkers. Part of Newar urban civilization.', 'Newar lifecycle rituals', 'Newar festivals', false, false, 'Sub-group of Newar people specializing in metalwork.', 'Indigenous to Patan/Lalitpur in Kathmandu Valley.', NOW()),

('thakali', 'Thakali', 'Entrepreneurial community from the Kali Gandaki corridor. Known for hospitality industry.', 56000, 20, 'HIMALAYAN', 'Gandaki', 'Myagdi, Mustang, Parbat', 'Trade, Hotel industry, Tourism', 'Clan-based system', 'Buddhist/Hindu', 'Famous for Thakali cuisine. Strong business acumen. Trans-Himalayan trade heritage.', 'Buddhist prayer ceremonies', 'Tiji Festival, Dashain, Lhosar', true, false, 'Historically salt traders from the Kali Gandaki corridor.', 'Inhabited Kali Gandaki valley as trans-Himalayan traders.', NOW());

-- =============================================
-- FESTIVALS (IDs 1-40)
-- =============================================
INSERT INTO festivals (slug, name, description, festival_type, culture_season, month, day, duration_days, region_type, is_national_holiday, is_public_holiday, significance, rituals, modern_celebrations, ethnic_groups_involved, province, district, is_popular, is_featured, created_at) VALUES

('dashain', 'Dashain', 'The longest and most important Hindu festival in Nepal. Celebrates the victory of Goddess Durga over the demon Mahishasura.', 'HINDU', 'AUTUMN', 'Ashwin-Kartik', 'Shukla Pratipada to Purnima', 15, NULL, true, true, 'Symbolizes the triumph of good over evil. Major family reunion festival.', 'Jamara growing, Goddess worship, Tikka ceremony, Swing riding, Kite flying', 'Family gatherings, new clothes, feasts, government holidays, tika from elders', 'All Hindu communities, Chhettri, Brahman, Tamang, Newar', 'All', 'All', true, true, NOW()),

('tihar', 'Tihar', 'Five-day festival of lights honoring Yama, dogs, cows, and the bond between brothers and sisters.', 'HINDU', 'AUTUMN', 'Kartik', 'Kartik Krishna Pratipada to Panchami', 5, NULL, true, true, 'Celebrates the bond between humans and animals, and between brothers and sisters.', 'Deusi-Bhailo singing, Laxmi Puja, Govardhan Puja, Bhai Tika, Mha Puja', 'Lights and candles, gambling games, Rangoli, brother-sister tika ceremony', 'All Hindu communities, Newar (Swanti)', 'All', 'All', true, true, NOW()),

('holi', 'Holi', 'Festival of colors celebrating the arrival of spring and the triumph of good over evil.', 'HINDU', 'SPRING', 'Phalguna', 'Phalguna Purnima', 2, NULL, true, true, 'Celebrates spring, love, and the divine play of Krishna.', 'Color throwing, water balloons, bonfires (Holika Dahan)', 'Public color play, music, dance, street celebrations', 'All Hindu communities', 'All', 'All', true, true, NOW()),

('maha-shivaratri', 'Maha Shivaratri', 'Great night of Lord Shiva. One of the most important Hindu fasting festivals.', 'HINDU', 'WINTER', 'Phalguna', 'Chaturdashi', 1, NULL, true, true, 'Night-long worship of Lord Shiva. Major pilgrimage day.', 'Fasting, Shiva temple visits, bael leaf offerings, holy bath', 'Pashupatinath temple gatherings, Sadhu watching, meditation', 'All Hindu communities', 'Bagmati', 'Kathmandu', true, true, NOW()),

('janai-purnima', 'Janai Purnima', 'Sacred thread festival where Hindu men change their sacred thread. Also Raksha Bandhan.', 'HINDU', 'MONSOON', 'Shravan', 'Shravan Purnima', 1, NULL, true, true, 'Sacred thread renewal and brother-sister protection bond.', 'Sacred thread changing, holy bath in rivers, Rakhi tying', 'Family gatherings, Rakhi exchange, Gosaikunda pilgrimage', 'All Hindu communities', 'All', 'All', true, false, NOW()),

('gai-jatra', 'Gai-jatra', 'Festival of cows commemorating the departed. Known for satire and humor.', 'NEWAR', 'MONSOON', 'Bhadra', 'Bhadra Krishna Pratipada', 1, 'URBAN', false, false, 'Satirical festival commemorating death with humor and satire.', 'Cow procession, satirical performances, comedy shows', 'Comedy shows, satire performances, street theater', 'Newar', 'Bagmati', 'Kathmandu', true, true, NOW()),

('indra-jatra', 'Indra-jatra', 'Festival of King Indra with living goddess Kumari procession.', 'NEWAR', 'AUTUMN', 'Bhadra-Ashwin', 'Bhadra Krishna Pratipada to Ashwin Krishna Purnima', 8, 'URBAN', false, false, 'Honors Lord Indra and features the living goddess Kumari.', 'Kumari chariot procession, masked dances, Indra pole erection', 'Chariot procession, Lakhe dance, Bhairav mask display', 'Newar', 'Bagmati', 'Kathmandu', true, true, NOW()),

('teej', 'Teej', 'Festival of marital bliss where women fast for husbands long life.', 'HINDU', 'MONSOON', 'Shravan', 'Shravan Tritiya', 1, NULL, true, true, 'Women pray for marital fidelity and husbands longevity.', 'Fasting, temple visits, swings, red clothing, henna', 'Women gatherings, singing, dancing, Haritalika temple visits', 'Hindu women across all groups', 'All', 'All', true, false, NOW()),

('chhath-puja', 'Chhath Puja', 'Ancient Hindu festival dedicated to Sun God. Major festival in Terai region.', 'HINDU', 'AUTUMN', 'Kartik', 'Kartik Shukla Shashthi', 4, 'TERAI', false, true, 'Ancient sun worship festival. One of the few festivals with no idol worship.', 'Holy dipping, arghya to sun, 36-hour fast, banana plantation', 'Riverbank prayers, community gathering, traditional songs', 'Yadav, Maithili, Koiri, Terai communities', 'Province 2', 'Janakpur', true, true, NOW()),

('buddha-jayanti', 'Buddha Jayanti', 'Birthday of Gautama Buddha. Celebrated at Lumbini and Buddhist monasteries.', 'BUDDHIST', 'SPRING', 'Baisakh', 'Baisakh Purnima', 1, NULL, true, true, 'Celebrates the birth, enlightenment, and death of Buddha.', 'Prayer meetings, monastery visits, candle lighting, meditation', 'Lumbini pilgrimage, peace rallies, cultural programs', 'Buddhist communities, Tamang, Newar, Gurung', 'Lumbini', 'Lumbini', true, true, NOW()),

('tamang-lhosar', 'Tamang Lhosar', 'Tibetan New Year celebration of the Tamang community.', 'BUDDHIST', 'WINTER', 'Magh', 'Magh 1 (approx)', 15, 'HILL', true, true, 'New year celebration marking the end of winter and beginning of spring.', 'Lama prayer ceremonies, Cham dance, traditional food', 'Cultural programs, Tamang Selo music, feasts, community gatherings', 'Tamang', 'Bagmati', 'Kathmandu', true, true, NOW()),

('sherpa-lhosar', 'Sherpa Lhosar', 'Tibetan New Year of the Sherpa people in high Himalayan regions.', 'BUDDHIST', 'WINTER', 'Chaitra', 'Chaitra 1 (approx)', 3, 'HIMALAYAN', false, false, 'New year of Sherpa communities with Buddhist prayer ceremonies.', 'Monastery prayers, Cham dance, traditional food, prayer flags', 'Cultural performances, monastery visits, family feasts', 'Sherpa', 'Province 1', 'Solukhumbu', true, false, NOW()),

('newar-lhosar', 'Nava Warsha (Newar New Year)', 'Newar New Year celebration marking the start of the Nepal Sambat calendar.', 'NEWAR', 'SPRING', 'Chaitra', 'Chaitra 1 (Kwati)', 1, 'URBAN', false, false, 'Marks the beginning of the Nepal Sambat calendar year.', 'Kwati (nine-bean soup), house cleaning, family gatherings', 'Community feasts, cultural programs, processions', 'Newar', 'Bagmati', 'Kathmandu', true, false, NOW()),

('maghe-sankranti', 'Maghe Sankranti', 'Solar transition festival marking the beginning of the auspicious period.', 'HINDU', 'WINTER', 'Magh', 'Magh 1', 1, NULL, true, true, 'Marks the sun entry into Capricorn. Considered highly auspicious.', 'Holy bath in rivers, sesame seed eating, sweet potato, yam', 'River bathing, family feasts, charity', 'All Hindu communities', 'All', 'All', true, false, NOW()),

('basant-panchami', 'Basant Panchami', 'Celebration of spring and Saraswati goddess of knowledge.', 'HINDU', 'SPRING', 'Magh', 'Magh Shukla Panchami', 1, NULL, false, false, 'Celebrates arrival of spring and worships Goddess Saraswati.', 'Saraswati puja, yellow clothing, kite flying', 'Educational programs, kite festivals, cultural events', 'All Hindu communities', 'All', 'All', true, false, NOW()),

('nag-panchami', 'Nag Panchami', 'Festival honoring serpent deities with milk offerings.', 'HINDU', 'MONSOON', 'Shravan', 'Shravan Shukla Panchami', 1, NULL, false, false, 'Worship of snake gods for protection and prosperity.', 'Milk offerings at snake temples, cow worship', 'Temple visits, community gatherings', 'All Hindu communities', 'All', 'All', true, false, NOW()),

('eid-al-fitr', 'Eid al-Fitr', 'Celebration marking the end of Ramadan holy month of fasting.', 'MUSLIM', 'SPRING', 'Shawwal', 'Shawwal 1', 3, 'TERAI', true, true, 'Celebrates completion of Ramadan fasting. Major Muslim festival.', 'Special prayers, feasting, charity (Zakat al-Fitr), new clothes', 'Community prayers, feasts, family gatherings, shopping', 'Muslim', 'Multiple', 'Terai cities', true, true, NOW()),

('eid-al-adha', 'Eid al-Adha', 'Festival of sacrifice commemorating Ibrahim willingness to sacrifice his son.', 'MUSLIM', 'SUMMER', 'Dhul Hijjah', 'Dhul Hijjah 10', 4, 'TERAI', true, true, 'Commemorates Ibrahim faith. Festival of animal sacrifice.', 'Animal sacrifice (Qurbani), special prayers, feasting', 'Community prayers, meat distribution, family gatherings', 'Muslim', 'Multiple', 'Terai cities', true, false, NOW()),

('christmas', 'Christmas', 'Christian celebration of the birth of Jesus Christ.', 'CHRISTIAN', 'WINTER', 'December', 'December 25', 1, NULL, true, false, 'Celebrates the birth of Jesus Christ.', 'Church services, midnight mass, carol singing', 'Gift exchange, feasts, decorated Christmas trees, community events', 'Christian', 'Multiple', 'Various', true, false, NOW()),

('losar', 'Losar (Tibetan New Year)', 'Tibetan New Year celebrated by Sherpa, Bhote, and Tibetan-origin communities.', 'BUDDHIST', 'WINTER', 'February', 'February (approx)', 15, 'HIMALAYAN', false, false, 'Marks the Tibetan New Year with Buddhist ceremonies.', 'Monastery prayers, Cham dance, prayer flags, family feasts', 'Cultural performances, community feasts, prayer ceremonies', 'Sherpa, Bhote, Tibetan-origin', 'Multiple', 'High Himalayan districts', true, false, NOW()),

('yomari-punhi', 'Yomari Punhi', 'Newar festival of rice harvest and full moon with sweet Yomari dumplings.', 'NEWAR', 'AUTUMN', 'Margashirsha', 'Margashirsha Purnima', 2, 'URBAN', false, false, 'Celebrates rice harvest with the unique Yomari sweet dumpling.', 'Yomari preparation and offering, Mohani rituals', 'Community Yomari distribution, cultural programs', 'Newar', 'Bagmati', 'Kathmandu', true, true, NOW()),

('bisket-jatra', 'Bisket Jatra', 'Newar chariot festival in Bhaktapur celebrating the new year.', 'NEWAR', 'SPRING', 'Chaitra', 'Chaitra 1-9', 9, 'URBAN', false, false, 'Ancient Bhaktapur chariot festival with wrestling and pole pulling.', 'Chariot procession, pole erecting, wrestling, Bhairav chariot pulling', 'Public gatherings, cultural performances, processions', 'Newar', 'Bagmati', 'Bhaktapur', true, true, NOW()),

('machhindranath-jatra', 'Rato Machhindranath Jatra', 'Famous chariot festival in Patan honoring the rain deity.', 'NEWAR', 'SPRING', 'Jestha', 'Jestha Shukla to Ashad Shukla', 45, 'URBAN', false, false, 'One of the longest chariot festivals. Honors the deity of rain and compassion.', 'Chariot pulling, bhoto display, deity procession', 'Community participation in chariot pulling, cultural events', 'Newar', 'Bagmati', 'Lalitpur', true, true, NOW()),

('sakela', 'Sakela/Sakewa', 'Major Kirant festival of Rai and Limbu communities celebrating nature.', 'KIRAT', 'SPRING', 'Baisakh', 'Baisakh (Ubhauli to Sakewa)', 1, 'HILL', true, false, 'Major Kirant festival celebrating nature and earth mother.', 'Sakela dance (Sili),Ubhauli and Sakewa phases, nature worship', 'Community Sakela dance, traditional attire, music', 'Rai, Limbu', 'Koshi', 'Eastern hills', true, true, NOW()),

('deuda', 'Deuda', 'Traditional folk song and dance festival of western Nepal.', 'OTHER', 'WINTER', 'Kartik', 'Kartik (various)', 1, 'HILL', false, false, 'Folk singing tradition of far-western Nepal with call-and-response format.', 'Deuda singing in circles, traditional instruments', 'Community singing gatherings, cultural programs', 'Various western hill communities', 'Sudurpashchim', 'Far-western hills', true, true, NOW()),

('gaura-parva', 'Gaura Parva', 'Festival celebrating the goddess Gauri and marital harmony.', 'HINDU', 'AUTUMN', 'Bhadra', 'Bhadra Krishna Ashtami', 3, 'HILL', false, false, 'Women worship Goddess Gauri for marital bliss and family welfare.', 'Fasting, Gauri worship, swings, traditional songs', 'Women gatherings, swings, cultural programs', 'Chhettri, Brahman, western hill communities', 'Gandaki', 'Myagdi, Parbat', true, false, NOW()),

('sirijonga', 'Sirijonga Jatra', 'Festival of the Sirijonga script and Limbu cultural heritage.', 'KIRAT', 'AUTUMN', 'Ashwin', 'Ashwin (various)', 1, 'HILL', false, false, 'Celebrates the Sirijonga script and Limbu cultural heritage.', 'Script writing competitions, cultural programs', 'Cultural events, community gatherings, traditional dance', 'Limbu', 'Koshi', 'Eastern hills', true, false, NOW()),

('chhath', 'Chhath Parva', 'Major sun worship festival of the Terai with rigorous fasting.', 'HINDU', 'AUTUMN', 'Kartik', 'Kartik Shukla Shashthi to Saptami', 4, 'TERAI', false, true, 'Ancient sun worship with strict 36-hour fasting and riverbank prayers.', 'Evening and morning arghya to sun, river dipping, banana plantation', 'Riverbank gatherings, traditional songs, community preparation', 'Terai communities, Yadav, Koiri, Maithili', 'Province 2', 'Janakpur, Birgunj', true, true, NOW()),

('lumbini-festival', 'Lumbini Festival', 'Celebration at the birthplace of Buddha promoting peace and heritage.', 'BUDDHIST', 'SPRING', 'Baisakh', 'Baisakh Purnima', 3, 'TERAI', false, false, 'International Buddhist celebration at Buddha birthplace.', 'Peace prayers, meditation, cultural programs', 'International Buddhist gathering, cultural performances', 'Buddhist communities worldwide', 'Lumbini', 'Lumbini', true, false, NOW()),

('seto-machhindranath', 'Seto Machhindranath Jatra', 'Chariot festival of the white Machhindranath deity in Kathmandu.', 'HINDU', 'SPRING', 'Chaitra', 'Chaitra Shukla 1 to Shukla Purnima', 1, 'URBAN', false, false, 'Kathmandu chariot procession of the compassion deity.', 'Chariot pulling, deity procession, prayers', 'Public procession, community participation', 'Newar, Hindu', 'Bagmati', 'Kathmandu', true, false, NOW()),

('krishna-janmashtami', 'Krishna Janmashtami', 'Birthday of Lord Krishna celebrated across Nepal.', 'HINDU', 'MONSOON', 'Bhadra', 'Bhadra Krishna Ashtami', 1, NULL, false, true, 'Celebrates the birth of Lord Krishna.', 'Temple visits, fasting, night-long vigil, Dahi Handi', 'Temple gatherings, Dahi Handi, cultural programs', 'All Hindu communities', 'All', 'All', true, false, NOW()),

('madhav-narayan', 'Madhav Narayan', 'Month-long fasting festival observed by women for family welfare.', 'HINDU', 'WINTER', 'Magh', 'Magh 1 to Falgun 1', 30, NULL, false, false, 'Women observe month-long ritual fasting and cold water bathing.', 'Daily holy bathing, fasting, Swasthani scripture reading', 'Women at riverside, religious gatherings', 'Hindu women', 'Bagmati', 'Various', false, false, NOW()),

('pharping-festival', 'Pharping Buddhist Festival', 'Celebration at the sacred Buddhist site of Pharping.', 'BUDDHIST', 'SPRING', 'Baisakh', 'Baisakh (various)', 3, 'URBAN', false, false, 'Buddhist celebration at important tantric site.', 'Meditation, prayers, monastery visits', 'Pilgrimage, cultural programs', 'Buddhist communities', 'Bagmati', 'Pharping', false, false, NOW()),

('raato-machhindranath-rain-festival', 'Rato Machhindranath Rain Festival', 'Rain prayer celebration in Patan with chariot procession.', 'NEWAR', 'MONSOON', 'Ashad', 'Ashad (various)', 10, 'URBAN', false, false, 'Prayers for rain through the beloved Machhindranath deity.', 'Chariot pulling, rain prayers, bhoto display', 'Community participation, processions', 'Newar', 'Bagmati', 'Lalitpur', true, false, NOW());

-- =============================================
-- ART FORMS (IDs 1-30, ethnic_group_id references Ethnic Groups)
-- =============================================
INSERT INTO art_forms (slug, name, description, art_type, ethnic_group_id, region_type, province, historical_significance, techniques, materials, significance, contemporary_relevance, is_intangible_heritage, created_at) VALUES

('lakhe-dance', 'Lakhe Dance', 'Masked demon dance of the Newar people performed during Indra Jatra.', 'FOLK', 6, 'URBAN', 'Bagmati', 'Ancient Newar dance form performed for centuries during Indra Jatra festival. Lakhe is a demon who protects Kathmandu.', 'Masked dance with acrobatic movements, accompanied by traditional drums', 'Wooden mask, traditional Newar costume, dhime drums', 'Protective dance of Kathmandu Valley. Symbolizes the subduing of evil spirits.', 'Performed during cultural festivals and tourism events. UNESCO heritage candidate.', true, NOW()),

('kumari-dance', 'Kumari Dance', 'Sacred dance performed by the Living Goddess Kumari tradition.', 'RELIGIOUS', 6, 'URBAN', 'Bagmati', 'Living goddess tradition dating to Malla period. Kumari is worshipped as manifestation of divine feminine.', 'Chariot procession, eye movements, sacred gestures', 'Traditional Kumari costume, golden chariot', 'Living embodiment of divine power. One of the unique religious traditions of the world.', 'Living goddess tradition continues. International cultural significance.', true, NOW()),

('peacock-dance', 'Peacock Dance (Mayur Nritya)', 'Tharu dance form imitating the peacock movements during festivals.', 'FOLK', 4, 'TERAI', 'Lumbini', 'Ancient Tharu dance performed during Maghi and harvest celebrations.', 'Mimicking peacock movements, graceful hand gestures, colorful costumes', 'Peacock feather headdress, colorful Tharu costume', 'Celebration of nature and beauty. Core of Tharu cultural identity.', 'Performed at cultural festivals and tourism events across Terai.', true, NOW()),

('tharu-stick-dance', 'Tharu Stick Dance (Sakia)', 'Martial-arts-inspired stick dance of the Tharu people.', 'FOLK', 4, 'TERAI', 'Lumbini', 'Ancient Tharu dance combining martial skills with rhythmic movements.', 'Coordinated stick fighting choreography, circular formations', 'Wooden sticks, traditional Tharu attire', 'Demonstrates Tharu warrior heritage and community unity.', 'Popular cultural attraction. Performed at festivals and tourism events.', true, NOW()),

('maruni-dance', 'Maruni Dance', 'Popular dance-drama form of eastern Nepal hills.', 'FOLK', 10, 'HILL', 'Koshi', 'Traditional Rai and Limbu performance combining dance and drama.', 'Dramatic performance with角色-play, accompanied by music', 'Traditional costume, musical instruments', 'Entertainment and cultural education. Preserves oral traditions.', 'Performed during festivals and cultural programs.', true, NOW()),

('deuda-song', 'Deuda Song', 'Traditional call-and-response folk singing tradition of far-western Nepal.', 'FOLK', 1, 'HILL', 'Sudurpashchim', 'Ancient folk singing tradition of Karnali and far-western regions.', 'Circle formation, call-and-response singing, rhythmic clapping', 'Traditional dress, musical instruments', 'Oral literature tradition. Preserves history and social commentary through song.', 'Active tradition with annual Deuda competitions and cultural programs.', true, NOW()),

('chhokara-dance', 'Chhokara Dance', 'Tharu harvest dance celebrating agricultural abundance.', 'FOLK', 4, 'TERAI', 'Lumbini', 'Harvest celebration dance unique to Tharu culture.', 'Energetic group dance with agricultural movement mimicking', 'Traditional Tharu attire, musical instruments', 'Celebration of harvest and agricultural cycle.', 'Performed during harvest festivals in Terai.', true, NOW()),

('kaura-dance', 'Kaura Dance', 'Traditional dance of western Nepal performed during Dashain.', 'FOLK', 1, 'HILL', 'Lumbini', 'Traditional western hill dance performed during Dashain celebrations.', 'Sword and shield dance with martial movements', 'Swords, shields, traditional costume', 'Celebration of warrior heritage during Dashain.', 'Performed in western districts during Dashain.', false, NOW()),

('sarangi-playing', 'Sarangi Playing', 'Traditional fiddle music of the Gaine (Gandarbhe) people.', 'CLASSICAL', 35, 'HILL', 'Multiple', 'Traditional instrument of traveling minstrels who kept oral histories alive.', 'Bowing technique with vocal accompaniment, storytelling', 'Sarangi (wooden fiddle), bow', 'Preserves folk histories and cultural memory through music.', 'Reviving tradition through music festivals and documentation.', true, NOW()),

('madal-playing', 'Madal Playing', 'Nepal national drum tradition played across all communities.', 'FOLK', 1, 'HILL', 'Multiple', 'The madal is the national drum of Nepal, used in virtually every celebration.', 'Hand drumming technique with complex rhythms', 'Madal (double-headed hand drum)', 'Central to Nepali music identity. Accompanies virtually all celebrations.', 'Popular instrument. Used in modern Nepali music fusion.', true, NOW()),

('damphu-playing', 'Damphu Playing', 'Tamang frame drum tradition central to Tamang Selo music.', 'FOLK', 5, 'HILL', 'Bagmati', 'Traditional Tamang instrument used in religious and social occasions.', 'Frame drum technique with rhythmic patterns and singing', 'Damphu (circular frame drum)', 'Core of Tamang musical identity. Accompanies Tamang Selo songs.', 'Popular in Nepali music. Tamang Selo is a major music genre.', true, NOW()),

('dholki-playing', 'Dholki Playing', 'Traditional drum ensemble music of Newar festivals.', 'FOLK', 6, 'URBAN', 'Bagmati', 'Integral to Newar festival processions and celebrations.', 'Complex rhythmic patterns in ensemble playing', 'Dholki drums, metal instruments', 'Essential to Newar festival atmosphere.', 'Active during all Newar festivals and processions.', false, NOW()),

('paubha-painting', 'Paubha Painting', 'Traditional Newar Buddhist scroll painting tradition.', 'RELIGIOUS', 6, 'URBAN', 'Bagmati', 'Ancient Newar painting tradition predating Tibetan Thangka. Dates to Malla period.', 'Fine brushwork with mineral pigments on cotton canvas', 'Cotton canvas, mineral pigments, gold leaf', 'Sacred Buddhist art used in temples and private worship.', 'Reviving tradition with modern artists preserving techniques.', true, NOW()),

('thangka-painting', 'Thangka Painting', 'Tibetan Buddhist scroll painting tradition practiced in Nepal.', 'RELIGIOUS', 48, 'HIMALAYAN', 'Bagmati', 'Buddhist painting tradition with roots in Tibetan monastic art.', 'Detailed iconographic painting following strict religious guidelines', 'Cotton/silk canvas, mineral pigments, gold', 'Sacred art for meditation and temple decoration.', 'Thriving tradition with international demand. Major art export.', true, NOW()),

('wood-carving', 'Wood Carving (Newar)', 'Intricate wood carving tradition of Newar architecture.', 'CLASSICAL', 6, 'URBAN', 'Bagmati', 'Essential element of Newar pagoda architecture dating back centuries.', 'Chisel and hammer techniques, geometric and floral patterns', 'Wood (sal, hardwood), traditional chisels', 'Creates the distinctive carved windows and doors of Newar architecture.', 'Active tradition maintaining heritage buildings and creating new works.', true, NOW()),

('metalwork', 'Metalwork (Newar)', 'Traditional repoussé and lost-wax metal casting of Newar artisans.', 'CLASSICAL', 49, 'URBAN', 'Bagmati', 'Newar metalworking tradition producing Buddhist and Hindu statues for centuries.', 'Repoussé, lost-wax casting, engraving', 'Copper, brass, bronze, gold', 'Creates sacred Buddhist and Hindu icons. Major art export of Nepal.', 'Thriving craft with international collectors and temple commissions.', true, NOW()),

('pottery', 'Pottery (Newar)', 'Traditional wheel-thrown and hand-built pottery of Newar potters.', 'FOLK', 6, 'URBAN', 'Bagmati', 'Pottery tradition of the Kumale and Pode communities in Kathmandu Valley.', 'Wheel throwing and hand building with open kiln firing', 'Clay, traditional pottery wheel, open kiln', 'Produces daily-use and ritual pottery. Traditional skill being preserved.', 'Declining but preserved by dedicated families and cultural programs.', false, NOW()),

('dhaka-weaving', 'Dhaka Weaving', 'Traditional handloom weaving of colorful Dhaka fabric for topi and shawls.', 'FOLK', 1, 'HILL', 'Gandaki', 'Traditional weaving producing the iconic Dhaka topi fabric.', 'Handloom weaving with colorful geometric patterns', 'Cotton thread, traditional handloom', 'Produces the iconic Nepali Dhaka topi and shawls.', 'Active tradition with cooperatives in Tehrathum and surrounding districts.', true, NOW()),

('mask-making', 'Mask Making', 'Traditional mask crafting for Lakhe and Cham dances.', 'FOLK', 6, 'URBAN', 'Bagmati', 'Craft of creating sacred and theatrical masks for Newar dances.', 'Wood carving and painting with traditional designs', 'Wood, natural pigments, fabric', 'Essential for ritual dances like Lakhe and Cham.', 'Maintained by traditional craftspeople. Cultural tourism demand.', false, NOW()),

('stone-carving', 'Stone Carving', 'Traditional stone sculpture tradition of Nepal temples and monuments.', 'CLASSICAL', 6, 'URBAN', 'Bagmati', 'Stone carving tradition creating temple sculptures and architectural elements.', 'Chisel and hammer technique on stone blocks', 'Stone (sandstone, granite, marble)', 'Creates sacred sculptures and architectural decoration.', 'Active tradition maintaining heritage sites and creating new works.', false, NOW()),

('bamboo-craft', 'Bamboo Craft', 'Traditional bamboo weaving and construction across Nepal hills.', 'FOLK', 44, 'HILL', 'Bagmati', 'Ancient craft of bamboo construction and weaving used in daily life.', 'Weaving, splitting, and binding techniques', 'Bamboo, natural fibers', 'Produces baskets, mats, houses, and ceremonial items.', 'Reviving as eco-friendly craft. Used in sustainable architecture.', false, NOW()),

('silver-jewelry', 'Silver Jewelry Making', 'Traditional Newar silver filigree jewelry craftsmanship.', 'CLASSICAL', 6, 'URBAN', 'Bagmati', 'Newar silversmith tradition of creating intricate filigree jewelry.', 'Filigree wire work, stone setting, engraving', 'Silver, precious stones, traditional tools', 'Creates traditional Nepali jewelry designs.', 'Active market with traditional and contemporary designs.', false, NOW()),

('leather-craft', 'Leather Craft', 'Traditional leather work of Damai and other artisan communities.', 'FOLK', 14, 'HILL', 'Multiple', 'Traditional leather processing and crafting.', 'Tanning, cutting, stitching techniques', 'Leather, traditional tools', 'Produces shoes, bags, and ritual items.', 'Declining due to synthetic materials. Preserved by traditional families.', false, NOW()),

('rope-making', 'Rope Making (Gaine)', 'Traditional rope making and musical instrument crafting.', 'FOLK', 35, 'HILL', 'Multiple', 'Traditional skill of the Gaine traveling musician community.', 'Hand-twisting and braiding plant fibers', 'Plant fibers, hemp', 'Produces ropes and stringed instruments.', 'Limited but preserved by traditional practitioners.', false, NOW()),

('jute-textile', 'Jute Textile', 'Traditional jute and cotton textile production of the Terai.', 'FOLK', 4, 'TERAI', 'Lumbini', 'Traditional weaving of jute and cotton fabrics in the Terai.', 'Handloom weaving with natural fibers', 'Jute, cotton, natural dyes', 'Produces daily-wear and ceremonial textiles.', 'Active in rural Terai communities.', false, NOW()),

('nepali-classical-music', 'Nepali Classical Music (Ragini)', 'Traditional classical music tradition blending Indian ragas with Nepali folk.', 'CLASSICAL', 1, 'HILL', 'Multiple', 'Classical music tradition influenced by Indian classical and local folk forms.', 'Raga-based composition with traditional instruments', 'Sarangi, bansuri (flute), tabla, harmonium', 'High art form preserving musical traditions.', 'Active classical music scene with annual festivals.', false, NOW()),

('charya-nritya', 'Charya Nritya', 'Newar Buddhist tantric dance form used in meditation and worship.', 'RELIGIOUS', 6, 'URBAN', 'Bagmati', 'Sacred Buddhist dance form performed as meditative worship.', 'Precise mudras and movements following Buddhist iconography', 'Traditional tantric costume, Buddhist ritual implements', 'Sacred dance meditation connecting practitioners to Buddhist deities.', 'Preserved in Newar Buddhist monasteries. UNESCO heritage candidate.', true, NOW()),

('dhime-bhajan', 'Dhime Bhajan', 'Traditional Newar devotional singing accompanied by dhime drum.', 'FOLK', 6, 'URBAN', 'Bagmati', 'Devotional singing tradition of Newar Buddhist and Hindu temples.', 'Call-and-response singing with dhime drum accompaniment', 'Dhime drum, traditional vocal technique', 'Essential devotional practice in Newar temples.', 'Active in all major Newar temples and festivals.', false, NOW());

-- =============================================
-- TRADITIONAL ATTIRES (IDs 1-25, ethnic_group_id references Ethnic Groups)
-- =============================================
INSERT INTO traditional_attires (slug, name, description, gender_type, attire_occasion, ethnic_group_id, region_type, province, fabric_material, colors, patterns, significance, wearing_occasion, historical_origin, regional_variations, created_at) VALUES

('daura-surwal', 'Daura Suruwal', 'National dress of Nepali men. A double-breasted shirt tied with seven points (onta) and tapered trousers.', 'MALE', 'CEREMONIAL', 1, 'HILL', 'Multiple', 'Cotton, Dhaka fabric', 'White, cream, Dhaka colors', 'Dhaka topi pattern for headwear', 'Symbol of Nepali national identity. Seven ties represent seven chakra points.', 'Government offices, festivals, formal occasions, weddings', 'Evolved from Khas kingdom attire. Standardized during Shah dynasty.', 'Varies by region. Dhaka topi patterns differ by ethnic group.', NOW()),

('gunyo-cholo', 'Gunyo Cholo', 'Traditional Nepali women dress consisting of a wrap-around skirt and blouse.', 'FEMALE', 'CEREMONIAL', 2, 'HILL', 'Multiple', 'Cotton, silk', 'Red, green, maroon, vibrant colors', 'Border patterns, brocade', 'Marks the transition from girlhood to womanhood. Essential wedding attire.', 'Weddings, festivals, ceremonial occasions, religious events', 'Ancient dress tradition of hill Brahmin and Chhettri women.', 'Color and fabric vary by community and occasion.', NOW()),

('dhaka-topi', 'Dhaka Topi', 'Iconic Nepali cap made from Dhaka fabric with distinctive geometric patterns.', 'MALE', 'CEREMONIAL', 1, 'HILL', 'Multiple', 'Dhaka woven fabric', 'Red, black, white geometric patterns', 'Geometric Dhaka patterns specific to regions', 'National symbol of Nepali identity. Worn with Daura Suruwal.', 'National celebrations, formal events, government functions, Dashain', 'Originated in eastern hills. Now national headwear.', 'Patterns vary by region. Tehrathum Dhaka is most famous.', NOW()),

('haku-patasi', 'Haku Patasi', 'Traditional Newar women black sari with distinctive red border.', 'FEMALE', 'DAILY', 6, 'URBAN', 'Bagmati', 'Cotton', 'Black with red border', 'Plain black with red border', 'Traditional everyday wear of Newar women. Symbol of Newar identity.', 'Daily wear, market visits, community gatherings', 'Ancient Newar dress tradition. Distinctive black and red combination.', 'Consistent across Kathmandu Valley Newar communities.', NOW()),

('tapalan-surwal', 'Tapalan Suruwal', 'Traditional Newar men upper garment with suruwal trousers.', 'MALE', 'FESTIVAL', 6, 'URBAN', 'Bagmati', 'Cotton, Dhaka fabric', 'White, cream', 'Dhaka border', 'Traditional Newar men formal attire.', 'Newar festivals, ceremonies, Indra Jatra', 'Newar adaptation of Nepali formal wear.', 'Specific to Newar communities of Kathmandu Valley.', NOW()),

('bakhu', 'Bakhu', 'Traditional Tamang woolen coat worn during cold weather and festivals.', 'UNISEX', 'FESTIVAL', 5, 'HILL', 'Bagmati', 'Wool, yak wool', 'Dark colors, brown, black', 'Geometric patterns, woven designs', 'Warm garment for high-altitude living. Symbol of Tamang identity.', 'Tamang Lhosar, winter festivals, cold weather', 'Adapted from Tibetan-influenced garment traditions.', 'Variations exist between eastern and western Tamang communities.', NOW()),

('gurung-bhoto', 'Gurung Bhoto/Lungi', 'Traditional Gurung men garment with distinctive patterns.', 'MALE', 'FESTIVAL', 11, 'HILL', 'Gandaki', 'Cotton, Dhaka fabric', 'White, red, Dhaka colors', 'Gurung-specific patterns', 'Traditional Gurung identity garment.', 'Gurung Lhosar, festivals, cultural events', 'Distinctive Gurung clothing reflecting their Tibeto-Burman heritage.', 'Variations between lowland and highland Gurung communities.', NOW()),

('tharu-gamcha', 'Tharu Gamcha/Lungi', 'Traditional Tharu woven garment for daily and ceremonial wear.', 'MALE', 'DAILY', 4, 'TERAI', 'Lumbini', 'Cotton, handwoven', 'White, colored borders', 'Handwoven stripes and borders', 'Essential Tharu daily wear. Demonstrates weaving skill.', 'Daily wear, agricultural work, festivals', 'Ancient weaving tradition of the Terai Tharu.', 'Patterns differ between Dangaura, Kathariya, and Rana Tharu groups.', NOW()),

('rai-mundhum-attire', 'Rai Traditional Attire', 'Traditional Rai clothing worn during Sakela and other Kirant ceremonies.', 'UNISEX', 'FESTIVAL', 10, 'HILL', 'Koshi', 'Cotton, woven fabric', 'Red, white, black', 'Kirant geometric patterns', 'Worn during Sakela dance and Kirant religious ceremonies.', 'Sakela/Sakewa, Kirant festivals, weddings', 'Ancient Kirant clothing tradition.', 'Different Rai sub-groups have distinct attire variations.', NOW()),

('limbu-dhaka-attire', 'Limbu Dhaka Attire', 'Traditional Limbu woven clothing with distinctive patterns.', 'UNISEX', 'FESTIVAL', 12, 'HILL', 'Koshi', 'Cotton, handwoven', 'Red, white, black', 'Limbu-specific woven patterns', 'Traditional Limbu identity garment.', 'Chasok Tangnam, Limbu festivals, weddings', 'Ancient Kirant weaving tradition.', 'Varies between different Limbu sub-groups.', NOW()),

('sherpa-chuba', 'Sherpa Chuba', 'Traditional long-sleeved robe of the Sherpa people adapted from Tibetan dress.', 'UNISEX', 'DAILY', 13, 'HIMALAYAN', 'Province 1', 'Wool, yak wool, silk', 'Dark colors, maroon, black', 'Tibetan-influenced patterns', 'Adapted to extreme cold of high Himalayas. Symbol of Sherpa identity.', 'Daily wear in high altitudes, monastery visits, festivals', 'Brought from Tibet during Sherpa migration.', 'Similar to Tibetan chuba with Sherpa-specific modifications.', NOW()),

('magar-bhoto', 'Magar Bhoto', 'Traditional Magar men upper garment.', 'MALE', 'FESTIVAL', 3, 'HILL', 'Gandaki', 'Cotton, woven fabric', 'White, dark colors', 'Magar-specific patterns', 'Traditional Magar identity garment.', 'Maghe Sankranti, Dashain, festivals', 'Ancient Magar clothing tradition.', 'Western Magar have distinct patterns from central Magar.', NOW()),

('kami-attire', 'Kami Traditional Attire', 'Everyday clothing of the Kami blacksmith community.', 'MALE', 'DAILY', 7, 'HILL', 'Multiple', 'Cotton', 'Dark colors', 'Simple woven patterns', 'Reflects the working nature of blacksmith occupation.', 'Daily work, festivals', 'Traditional working attire of blacksmith community.', 'Similar across hill regions.', NOW()),

('damai-tailoring', 'Damai Traditional Attire', 'Clothing of the Damai tailor and musician community.', 'MALE', 'FESTIVAL', 14, 'HILL', 'Multiple', 'Cotton, Dhaka', 'White, Dhaka patterns', 'Dhaka elements', 'Reflects the musician and tailor role in society.', 'Festival music performances, weddings', 'Adapted from broader hill attire traditions.', 'Similar across communities.', NOW()),

('muslim-thawb', 'Muslim Thawb/Kurta', 'Traditional Islamic clothing worn by Muslim men and women in Nepal.', 'UNISEX', 'RELIGIOUS', 8, 'TERAI', 'Multiple', 'Cotton, silk', 'White (men), colorful (women)', 'Minimal patterns, embroidery for women', 'Reflects Islamic modesty requirements.', 'Eid prayers, Friday prayers, religious occasions', 'Brought with Islamic cultural influence to Nepal.', 'Similar to broader South Asian Islamic attire.', NOW()),

('madheshi-dhoti', 'Madheshi Dhoti', 'Traditional Terai men garment wrapped around the waist.', 'MALE', 'DAILY', 9, 'TERAI', 'Province 2', 'Cotton', 'White', 'Simple white dhoti', 'Essential Terai men garment for daily wear and ceremonies.', 'Daily wear, festivals, religious ceremonies', 'Ancient Indian-origin garment adopted across the Terai.', 'Similar to North Indian dhoti tradition.', NOW()),

('chepang-bark-attire', 'Chepang Forest Attire', 'Minimal clothing made from bark and forest materials by Chepang people.', 'UNISEX', 'DAILY', 44, 'HILL', 'Bagmati', 'Bark, forest materials, cotton', 'Natural brown, earth tones', 'Minimal woven patterns', 'Reflects the forest-dwelling lifestyle of the Chepang.', 'Daily wear, forest activities', 'Ancient forest-dwelling garment tradition.', 'Being replaced by cotton clothing.', NOW()),

('raute-minimal', 'Raute Traditional Attire', 'Simple clothing of the nomadic Raute people.', 'UNISEX', 'DAILY', 45, 'HILL', 'Karnali', 'Cotton, bark', 'Dark colors, earth tones', 'Minimal patterns', 'Reflects the nomadic hunter-gatherer lifestyle.', 'Daily wear, traveling', 'Ancient nomadic clothing tradition.', 'Minimal and practical for mobile lifestyle.', NOW()),

('rajbanshi-attire', 'Rajbanshi Traditional Attire', 'Distinctive Rajbanshi woven clothing with cultural patterns.', 'UNISEX', 'FESTIVAL', 46, 'TERAI', 'Province 1', 'Cotton, handwoven', 'Red, white, colorful', 'Rajbanshi woven patterns', 'Reflects Rajbanshi tribal identity.', 'Bihu festival, harvest celebrations, weddings', 'Ancient Terai tribal clothing tradition.', 'Distinct from other Terai communities.', NOW()),

('thakali-attire', 'Thakali Traditional Attire', 'Traditional Thakali clothing reflecting Himalayan cultural influences.', 'UNISEX', 'FESTIVAL', 50, 'HIMALAYAN', 'Gandaki', 'Wool, cotton', 'Dark colors, colorful accents', 'Himalayan patterns', 'Reflects Thakali trade culture and Himalayan lifestyle.', 'Tiji Festival, Dashain, cultural events', 'Influenced by both Tibetan and Nepali traditions.', 'Distinct from other hill communities.', NOW()),

('bahun-gunyo', 'Bahun (Brahmin) Gunyo Cholo', 'Specific Brahmin variant of the traditional women dress.', 'FEMALE', 'RELIGIOUS', 2, 'HILL', 'Multiple', 'Cotton, silk', 'Red, white, green', 'Religious border patterns', 'Worn during religious ceremonies and pujas.', 'Religious ceremonies, temple visits, pujas', 'Religious attire specific to Brahmin women.', 'Similar across Brahmin communities but with religious-specific variations.', NOW()),

('chhettri-daura', 'Chhettri Daura Suruwal', 'Specific Chhettri variant of the national men dress.', 'MALE', 'FESTIVAL', 1, 'HILL', 'Multiple', 'Cotton, Dhaka fabric', 'White, cream, Dhaka', 'Dhaka patterns', 'Worn during Dashain and other festivals.', 'Dashain, festivals, formal occasions', 'Part of the broader Kshatriya attire tradition.', 'Similar to general Daura Suruwal with Chhettri-specific elements.', NOW()),

('madheshi-sari', 'Madheshi Women Sari', 'Traditional sari worn by women in the Terai region.', 'FEMALE', 'DAILY', 9, 'TERAI', 'Province 2', 'Cotton, silk', 'Vibrant colors, red, green', 'Border patterns, pallu designs', 'Essential Terai women garment.', 'Daily wear, festivals, weddings', 'Connected to broader Indian sari tradition.', 'Similar to North Indian sari styles.', NOW()),

('chepang-bamboo-ornament', 'Chepang Bamboo Ornaments', 'Traditional bamboo jewelry and ornaments worn by Chepang women.', 'FEMALE', 'FESTIVAL', 44, 'HILL', 'Bagmati', 'Bamboo, forest materials', 'Natural colors', 'Woven bamboo patterns', 'Unique forest-crafted ornaments reflecting Chepang lifestyle.', 'Festivals, ceremonies', 'Ancient forest craft tradition.', 'Unique to Chepang culture. Replaced by modern jewelry in some areas.', NOW()),

('newar-women-festival', 'Newar Women Festival Attire', 'Elaborate Newar women dress worn during major festivals.', 'FEMALE', 'FESTIVAL', 6, 'URBAN', 'Bagmati', 'Silk, brocade, golden fabric', 'Red, gold, vibrant colors', 'Brocade borders, golden embroidery', 'Elaborate festive wear showcasing Newar textile arts.', 'Indra Jatra, Yomari Punhi, weddings, festivals', 'Traditional Malla-period textile traditions.', 'Varies between Kathmandu, Bhaktapur, and Patan Newars.', NOW());
