INSERT INTO destination_tags (slug, name, tag_type, created_at) VALUES
('mountain-views', 'Mountain Views', 'THEME', NOW()),
('unesco-site', 'UNESCO Site', 'THEME', NOW()),
('pilgrimage', 'Pilgrimage', 'THEME', NOW()),
('photography', 'Photography', 'ACTIVITY', NOW()),
('family-friendly', 'Family Friendly', 'ACCESSIBILITY', NOW()),
('budget-friendly', 'Budget Friendly', 'ACCESSIBILITY', NOW()),
('luxury', 'Luxury', 'ACCESSIBILITY', NOW()),
('off-the-beaten-path', 'Off the Beaten Path', 'THEME', NOW()),
('beginner-friendly', 'Beginner Friendly', 'ACCESSIBILITY', NOW()),
('solo-travel', 'Solo Travel', 'ACCESSIBILITY', NOW()),
('couples', 'Couples', 'ACCESSIBILITY', NOW()),
('spring-season', 'Best in Spring', 'SEASON', NOW()),
('autumn-season', 'Best in Autumn', 'SEASON', NOW()),
('monsoon-avoid', 'Avoid Monsoon', 'SEASON', NOW()),
('winter-destination', 'Winter Destination', 'SEASON', NOW()),
('tea-gardens', 'Tea Gardens', 'THEME', NOW()),
('river-lake', 'Rivers & Lakes', 'THEME', NOW()),
('historical-architecture', 'Historical Architecture', 'THEME', NOW()),
('buddhist-heritage', 'Buddhist Heritage', 'THEME', NOW()),
('hindu-heritage', 'Hindu Heritage', 'THEME', NOW()),
('sunset-spot', 'Sunset Spot', 'ACTIVITY', NOW()),
('sunrise-spot', 'Sunrise Spot', 'ACTIVITY', NOW()),
('wildlife-spotting', 'Wildlife Spotting', 'ACTIVITY', NOW()),
('rafting', 'Rafting', 'ACTIVITY', NOW()),
('paragliding', 'Paragliding', 'ACTIVITY', NOW()),
('cultural-experience', 'Cultural Experience', 'ACTIVITY', NOW()),
('local-food', 'Local Food', 'ACTIVITY', NOW()),
('meditation', 'Meditation & Yoga', 'ACTIVITY', NOW()),
('bungee', 'Bungee Jumping', 'ACTIVITY', NOW()),
('camping', 'Camping', 'ACTIVITY', NOW());
