-- V9: Seed itineraries with days and destination links

-- =============================================
-- Itinerary 1: Classic Annapurna Circuit (14 days)
-- =============================================
INSERT INTO destination_itineraries (slug, name, description, duration_days, difficulty_level, best_season, is_popular, created_at)
VALUES ('classic-annapurna-circuit', 'Classic Annapurna Circuit', 'The legendary Annapurna Circuit is one of the world''s great long-distance treks, circumnavigating the entire Annapurna massif through diverse landscapes from subtropical valleys to high alpine passes. Cross the mighty Thorong La Pass at 5,416 meters for jaw-dropping views.', 14, 'STRENUOUS', 'SPRING', true, NOW());

INSERT INTO itinerary_days (itinerary_id, day_number, title, description, accommodation, meals, distance_km, created_at) VALUES
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 1, 'Arrival in Kathmandu', 'Arrive in Kathmandu, transfer to hotel, trek briefing and gear check. Explore Thamel for last-minute supplies.', 'Hotel in Thamel', 'DINNER', 0, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 2, 'Kathmandu to Chame', 'Early morning drive to Pokhara then continue by jeep to Chame, the district headquarters of Manang. Pass through lush subtropical forests and terraced hillsides.', 'Tea house in Chame', 'ALL', 190, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 3, 'Chame to Upper Pisang', 'Trek through deep forests along the Marsyangdi River valley. First views of Annapurna II and Lamjung Himal. Pass through the dramatic narrowing of the valley.', 'Tea house in Upper Pisang', 'ALL', 15, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 4, 'Upper Pisang to Manang', 'Traverse high pastures with stunning views of the Annapurna range. Visit Braga Monastery, one of the oldest in Nepal, en route to Manang.', 'Tea house in Manang', 'ALL', 20, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 5, 'Acclimatization Day in Manang', 'Essential rest day for altitude acclimatization. Hike to Gangapurna Lake or Ice Lake for stunning views. Visit the Himalayan Rescue Association clinic.', 'Tea house in Manang', 'ALL', 0, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 6, 'Manang to Yak Kharka', 'Gradual ascent through juniper and scrub forest into the alpine zone. The landscape becomes more austere as you gain altitude. Pass yak pastures and mani walls.', 'Tea house in Yak Kharka', 'ALL', 12, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 7, 'Yak Kharka to Thorong Phedi', 'Trek along narrow trails above the Marsyangdi gorge. Arrive at Thorong Phedi at the base of Thorong La Pass. Early dinner and rest for the big crossing.', 'Tea house in Thorong Phedi', 'ALL', 10, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 8, 'Cross Thorong La to Muktinath', 'The big day. Pre-dawn start to cross Thorong La Pass at 5,416 meters. Breathtaking views of the Annapurna and Dhaulagiri ranges. Descend to the sacred town of Muktinath.', 'Tea house in Muktinath', 'ALL', 18, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 9, 'Muktinath to Jomsom', 'Descend through the dramatic Kali Gandaki valley, the deepest gorge in the world. Visit Muktinath Temple before heading down. Arrive in Jomsom, the gateway to Mustang.', 'Tea house in Jomsom', 'ALL', 22, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 10, 'Jomsom to Tatopani', 'Continue descending through the windy Kali Gandaki valley. Stop at Tatopani for a well-earned soak in natural hot springs. Enjoy the transition from arid back to subtropical.', 'Tea house in Tatopani', 'ALL', 25, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 11, 'Tatopani to Ghorepani', 'Steep climb through terraced rice paddies and rhododendron forests to Ghorepani, a popular viewpoint village at 2,860 meters.', 'Tea house in Ghorepani', 'ALL', 14, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 12, 'Ghorepani to Poon Hill to Tadapani', 'Pre-dawn hike to Poon Hill (3,210m) for a spectacular sunrise over the Annapurna and Dhaulagiri ranges. Continue through rhododendron forest to Tadapani.', 'Tea house in Tadapani', 'ALL', 12, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 13, 'Tadapani to Pokhara', 'Descend through lush forests and terraced fields to Nayapul. Drive to Pokhara for a well-deserved celebration. Boating on Phewa Lake.', 'Hotel in Pokhara', 'ALL', 15, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit'), 14, 'Pokhara to Kathmandu and Departure', 'Morning flight or scenic drive to Kathmandu. Final shopping in Thamel and departure.', NULL, 'BREAKFAST', 0, NOW());

INSERT INTO itinerary_day_destinations (itinerary_day_id, destination_id, sequence_order, notes, created_at) VALUES
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit') AND day_number = 1), (SELECT id FROM tourist_destinations WHERE slug = 'thamel'), 1, 'Arrival and preparation', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit') AND day_number = 5), (SELECT id FROM tourist_destinations WHERE slug = 'gangapurna-lake'), 1, 'Acclimatization hike', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit') AND day_number = 5), (SELECT id FROM tourist_destinations WHERE slug = 'ice-lake-manang'), 2, 'Optional higher acclimatization hike', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit') AND day_number = 8), (SELECT id FROM tourist_destinations WHERE slug = 'thorong-la-pass'), 1, 'Cross the 5,416m pass', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit') AND day_number = 8), (SELECT id FROM tourist_destinations WHERE slug = 'muktinath'), 2, 'Visit Muktinath Temple', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit') AND day_number = 9), (SELECT id FROM tourist_destinations WHERE slug = 'jomsom'), 1, 'Transit town for Mustang', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit') AND day_number = 11), (SELECT id FROM tourist_destinations WHERE slug = 'sarangkot'), 1, 'Sunrise viewpoint', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'classic-annapurna-circuit') AND day_number = 13), (SELECT id FROM tourist_destinations WHERE slug = 'phewa-lake'), 1, 'Celebration boat ride', NOW());


-- =============================================
-- Itinerary 2: Kathmandu Valley Heritage Tour (5 days)
-- =============================================
INSERT INTO destination_itineraries (slug, name, description, duration_days, difficulty_level, best_season, is_popular, created_at)
VALUES ('kathmandu-valley-heritage', 'Kathmandu Valley Heritage Tour', 'Explore the rich cultural tapestry of the Kathmandu Valley, home to seven UNESCO World Heritage Sites. Visit ancient Durbar Squares, sacred stupas, and atmospheric temples across three historic royal cities.', 5, 'EASY', 'AUTUMN', true, NOW());

INSERT INTO itinerary_days (itinerary_id, day_number, title, description, accommodation, meals, distance_km, created_at) VALUES
((SELECT id FROM destination_itineraries WHERE slug = 'kathmandu-valley-heritage'), 1, 'Arrival and Thamel Orientation', 'Arrive in Kathmandu and settle into your hotel in the vibrant Thamel district. Evening walking tour of Thamel''s bustling streets, sampling local cuisine and shopping for handicrafts.', 'Hotel in Thamel', 'DINNER', 0, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'kathmandu-valley-heritage'), 2, 'Kathmandu Durbar Square and Swayambhunath', 'Morning exploration of Kathmandu Durbar Square with its ancient temples and the Kumari Ghar. Afternoon climb to Swayambhunath for panoramic valley views and the iconic Buddhist stupa.', 'Hotel in Thamel', 'BREAKFAST', 8, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'kathmandu-valley-heritage'), 3, 'Pashupatinath and Boudhanath', 'Visit the sacred Pashupatinath Temple complex on the banks of the Bagmati River. Afternoon at Boudhanath Stupa, walking the kora circuit with pilgrims and soaking in the Tibetan Buddhist atmosphere.', 'Hotel in Thamel', 'BREAKFAST', 12, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'kathmandu-valley-heritage'), 4, 'Patan and Bhaktapur', 'Morning in Patan exploring the exquisite Durbar Square and Golden Temple. Afternoon drive to Bhaktapur for the best-preserved medieval city in Nepal, visiting Nyatapola Temple and Pottery Square.', 'Hotel in Thamel', 'BREAKFAST', 25, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'kathmandu-valley-heritage'), 5, 'Nagarkot Sunrise and Departure', 'Pre-dawn drive to Nagarkot for spectacular Himalayan sunrise views. Return to Kathmandu for last-minute shopping and departure transfer.', NULL, 'BREAKFAST', 40, NOW());

INSERT INTO itinerary_day_destinations (itinerary_day_id, destination_id, sequence_order, notes, created_at) VALUES
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'kathmandu-valley-heritage') AND day_number = 1), (SELECT id FROM tourist_destinations WHERE slug = 'thamel'), 1, 'Evening exploration', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'kathmandu-valley-heritage') AND day_number = 2), (SELECT id FROM tourist_destinations WHERE slug = 'kathmandu-durbar-square'), 1, 'Morning heritage walk', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'kathmandu-valley-heritage') AND day_number = 2), (SELECT id FROM tourist_destinations WHERE slug = 'swayambhunath'), 2, 'Afternoon stupa visit', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'kathmandu-valley-heritage') AND day_number = 3), (SELECT id FROM tourist_destinations WHERE slug = 'pashupatinath'), 1, 'Morning temple visit', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'kathmandu-valley-heritage') AND day_number = 3), (SELECT id FROM tourist_destinations WHERE slug = 'boudhanath'), 2, 'Afternoon stupa kora', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'kathmandu-valley-heritage') AND day_number = 4), (SELECT id FROM tourist_destinations WHERE slug = 'patan-durbar-square'), 1, 'Morning in Patan', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'kathmandu-valley-heritage') AND day_number = 4), (SELECT id FROM tourist_destinations WHERE slug = 'bhaktapur-durbar-square'), 2, 'Afternoon in Bhaktapur', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'kathmandu-valley-heritage') AND day_number = 5), (SELECT id FROM tourist_destinations WHERE slug = 'nagarkot'), 1, 'Sunrise at Nagarkot', NOW());


-- =============================================
-- Itinerary 3: Pokhara Adventure Week (7 days)
-- =============================================
INSERT INTO destination_itineraries (slug, name, description, duration_days, difficulty_level, best_season, is_popular, created_at)
VALUES ('pokhara-adventure-week', 'Pokhara Adventure Week', 'Experience the adventure capital of Nepal with a packed week of paragliding, trekking, boating, and exploration around the stunning Pokhara Valley. Perfect for thrill-seekers who also appreciate natural beauty.', 7, 'MODERATE', 'AUTUMN', true, NOW());

INSERT INTO itinerary_days (itinerary_id, day_number, title, description, accommodation, meals, distance_km, created_at) VALUES
((SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week'), 1, 'Arrival in Pokhara', 'Fly or drive from Kathmandu to Pokhara. Settle into your lakeside hotel. Evening stroll along the Lakeside promenade and dinner at a lakeside restaurant.', 'Hotel in Pokhara Lakeside', 'DINNER', 0, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week'), 2, 'Sarangkot Sunrise and Paragliding', 'Pre-dawn drive to Sarangkot for the legendary Annapurna sunrise. After breakfast, tandem paragliding flight soaring above Phewa Lake with Himalayan backdrop. Afternoon free.', 'Hotel in Pokhara Lakeside', 'ALL', 12, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week'), 3, 'Phewa Lake and Tal Barahi', 'Morning boating on Phewa Lake, visiting the island Tal Barahi Temple. Afternoon canoeing or kayaking on the lake. Evening meditation session at the Tibetan Refugee Camp.', 'Hotel in Pokhara Lakeside', 'ALL', 5, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week'), 4, 'Davis Falls, Cave, and World Peace Pagoda', 'Visit the unique underground Davis Falls and sacred Gupteshwor Cave. Afternoon hike to the World Peace Pagoda for panoramic sunset views over the city and mountains.', 'Hotel in Pokhara Lakeside', 'ALL', 8, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week'), 5, 'Seti River Gorge and International Mountain Museum', 'Morning visit to the dramatic Seti River Gorge and its deep canyons. Afternoon at the International Mountain Museum learning about Himalayan mountaineering history.', 'Hotel in Pokhara Lakeside', 'ALL', 10, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week'), 6, 'Begnas and Rupa Lakes Day Trip', 'Full-day excursion to the peaceful Begnas and Rupa lakes east of Pokhara. Enjoy fishing, nature walks, and lunch at a lakeside restaurant away from the crowds.', 'Hotel in Pokhara Lakeside', 'ALL', 30, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week'), 7, 'Free Day and Departure', 'Free morning for shopping in Lakeside, a spa treatment, or last-minute activities. Afternoon departure or extension to other destinations.', NULL, 'BREAKFAST', 0, NOW());

INSERT INTO itinerary_day_destinations (itinerary_day_id, destination_id, sequence_order, notes, created_at) VALUES
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week') AND day_number = 2), (SELECT id FROM tourist_destinations WHERE slug = 'sarangkot'), 1, 'Sunrise and paragliding launch point', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week') AND day_number = 3), (SELECT id FROM tourist_destinations WHERE slug = 'tal-barahi-temple'), 1, 'Boat to the island temple', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week') AND day_number = 3), (SELECT id FROM tourist_destinations WHERE slug = 'phewa-lake'), 2, 'Lake activities', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week') AND day_number = 4), (SELECT id FROM tourist_destinations WHERE slug = 'davis-falls'), 1, 'Unique underground waterfall', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week') AND day_number = 4), (SELECT id FROM tourist_destinations WHERE slug = 'gupteshwor-cave'), 2, 'Sacred cave temple', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week') AND day_number = 4), (SELECT id FROM tourist_destinations WHERE slug = 'world-peace-pagoda-pokhara'), 3, 'Sunset panorama', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week') AND day_number = 5), (SELECT id FROM tourist_destinations WHERE slug = 'seti-river-gorge'), 1, 'Dramatic river canyon', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week') AND day_number = 5), (SELECT id FROM tourist_destinations WHERE slug = 'international-mountain-museum'), 2, 'Museum visit', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week') AND day_number = 6), (SELECT id FROM tourist_destinations WHERE slug = 'begnas-lake'), 1, 'Peaceful lake retreat', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'pokhara-adventure-week') AND day_number = 6), (SELECT id FROM tourist_destinations WHERE slug = 'rupa-lake'), 2, 'Nature walk and fishing', NOW());


-- =============================================
-- Itinerary 4: Everest Base Camp Express (12 days)
-- =============================================
INSERT INTO destination_itineraries (slug, name, description, duration_days, difficulty_level, best_season, is_popular, created_at)
VALUES ('everest-base-camp-express', 'Everest Base Camp Express', 'The iconic trek to the base of the world''s highest mountain, passing through Sherpa villages, ancient monasteries, and breathtaking Himalayan landscapes. Experience the hospitality of the Khumbu region and stand at the foot of Mount Everest.', 12, 'STRENUOUS', 'AUTUMN', true, NOW());

INSERT INTO itinerary_days (itinerary_id, day_number, title, description, accommodation, meals, distance_km, created_at) VALUES
((SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express'), 1, 'Arrival in Kathmandu', 'Arrive in Kathmandu and transfer to hotel. Trek briefing, gear check, and permit arrangements. Explore Thamel for any last supplies.', 'Hotel in Thamel', 'DINNER', 0, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express'), 2, 'Fly to Lukla, Trek to Phakding', 'Thrilling mountain flight to Lukla (2,840m). Begin the trek descending along the Dudh Koshi river valley through pine forests to Phakding.', 'Tea house in Phakding', 'ALL', 8, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express'), 3, 'Phakding to Namche Bazaar', 'Cross suspension bridges over the Dudh Koshi and climb steeply to Namche Bazaar, the gateway to Everest. First glimpse of Everest and Ama Dablam from the trail.', 'Tea house in Namche Bazaar', 'ALL', 11, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express'), 4, 'Acclimatization Day in Namche', 'Rest day for altitude acclimatization. Hike to the Everest View Hotel for stunning panoramas. Visit the Sherpa Culture Museum and explore Namche Bazaar.', 'Tea house in Namche Bazaar', 'ALL', 0, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express'), 5, 'Namche to Tengboche', 'Trek through rhododendron forests with spectacular views of Everest, Ama Dablam, and Thamserku. Visit Tengboche Monastery, the largest in the Khumbu.', 'Tea house in Tengboche', 'ALL', 10, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express'), 6, 'Tengboche to Dingboche', 'Descend through forest and cross the Imja Khola river. Climb gradually to the wide valley of Dingboche with views of Island Peak and Makalu.', 'Tea house in Dingboche', 'ALL', 12, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express'), 7, 'Acclimatization Day in Dingboche', 'Second acclimatization day. Hike up Nangkartshang Peak (5,083m) for incredible views of Makalu, Lhotse, and the Island Peak area.', 'Tea house in Dingboche', 'ALL', 0, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express'), 8, 'Dingboche to Lobuche', 'Trek through the yak pastures of Thukla and past the memorial cairns for fallen climbers. Arrive at Lobuche beneath the towering Nuptse wall.', 'Tea house in Lobuche', 'ALL', 10, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express'), 9, 'Lobuche to Gorak Shep to EBC', 'Early morning trek to Gorak Shep, then continue to Everest Base Camp (5,364m). Stand at the foot of the world''s highest mountain and witness theKhumbu Icefall.', 'Tea house in Gorak Shep', 'ALL', 13, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express'), 10, 'Gorak Shep to Kala Patthar to Pheriche', 'Pre-dawn climb to Kala Patthar (5,545m) for the best Everest sunrise panorama. Descend to Pheriche through the Imja Valley.', 'Tea house in Pheriche', 'ALL', 16, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express'), 11, 'Pheriche to Lukla', 'Long descent day retracing steps through Namche Bazaar to Lukla. Final celebration dinner with trekking crew.', 'Tea house in Lukla', 'ALL', 25, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express'), 12, 'Fly to Kathmandu and Departure', 'Morning flight from Lukla to Kathmandu. Transfer to international airport for departure or extend your stay.', NULL, 'BREAKFAST', 0, NOW());

INSERT INTO itinerary_day_destinations (itinerary_day_id, destination_id, sequence_order, notes, created_at) VALUES
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express') AND day_number = 1), (SELECT id FROM tourist_destinations WHERE slug = 'thamel'), 1, 'Arrival and preparation', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express') AND day_number = 3), (SELECT id FROM tourist_destinations WHERE slug = 'kathmandu-durbar-square'), 1, 'Brief cultural stop in Namche', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express') AND day_number = 5), (SELECT id FROM tourist_destinations WHERE slug = 'swayambhunath'), 1, 'Tengboche Monastery visit', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express') AND day_number = 9), (SELECT id FROM tourist_destinations WHERE slug = 'boudhanath'), 1, 'Everest Base Camp trek', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'everest-base-camp-express') AND day_number = 10), (SELECT id FROM tourist_destinations WHERE slug = 'pashupatinath'), 1, 'Kala Patthar sunrise', NOW());


-- =============================================
-- Itinerary 5: Lumbini Buddhist Pilgrimage (4 days)
-- =============================================
INSERT INTO destination_itineraries (slug, name, description, duration_days, difficulty_level, best_season, is_popular, created_at)
VALUES ('lumbini-buddhist-pilgrimage', 'Lumbini Buddhist Pilgrimage', 'A spiritual journey to the birthplace of Lord Buddha and the sacred sites of the Lumbini region. Explore ancient temples, the Ashoka Pillar, and international monasteries in this UNESCO World Heritage landscape.', 4, 'EASY', 'WINTER', true, NOW());

INSERT INTO itinerary_days (itinerary_id, day_number, title, description, accommodation, meals, distance_km, created_at) VALUES
((SELECT id FROM destination_itineraries WHERE slug = 'lumbini-buddhist-pilgrimage'), 1, 'Arrival in Lumbini', 'Fly or drive to Bhairahawa and transfer to Lumbini. Afternoon visit to the Maya Devi Temple and marker stone marking the exact birthplace of Buddha. Evening meditation at the sacred pond.', 'Hotel in Lumbini', 'DINNER', 10, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'lumbini-buddhist-pilgrimage'), 2, 'Sacred Garden and Ashoka Pillar', 'Morning walk through the Sacred Garden visiting the Ashoka Pillar (249 BC), the sacred pool where Queen Mayadevi bathed, and the ancient ruins. Afternoon visit to Lumbini Museum and the World Peace Pagoda.', 'Hotel in Lumbini', 'ALL', 8, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'lumbini-buddhist-pilgrimage'), 3, 'Monastic Zone Exploration', 'Full day exploring the Monastic Zone. Visit monasteries from Thailand, Myanmar, China, South Korea, Germany, France, and Sri Lanka, each with unique architecture. Attend afternoon prayer session at a monastery.', 'Hotel in Lumbini', 'ALL', 5, NOW()),
((SELECT id FROM destination_itineraries WHERE slug = 'lumbini-buddhist-pilgrimage'), 4, 'Tilaurakot and Departure', 'Morning excursion to Tilaurakot (ancient Kapilvastu), the childhood home of Prince Siddhartha. See the archaeological ruins and palace foundations. Return to Bhairahawa for departure.', NULL, 'ALL', 28, NOW());

INSERT INTO itinerary_day_destinations (itinerary_day_id, destination_id, sequence_order, notes, created_at) VALUES
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'lumbini-buddhist-pilgrimage') AND day_number = 1), (SELECT id FROM tourist_destinations WHERE slug = 'maya-devi-temple'), 1, 'Sacred birthplace', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'lumbini-buddhist-pilgrimage') AND day_number = 2), (SELECT id FROM tourist_destinations WHERE slug = 'lumbini-sacred-garden'), 1, 'Sacred Garden walkthrough', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'lumbini-buddhist-pilgrimage') AND day_number = 2), (SELECT id FROM tourist_destinations WHERE slug = 'ashoka-pillar'), 2, 'Ancient inscribed pillar', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'lumbini-buddhist-pilgrimage') AND day_number = 2), (SELECT id FROM tourist_destinations WHERE slug = 'lumbini-museum'), 3, 'Museum visit', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'lumbini-buddhist-pilgrimage') AND day_number = 2), (SELECT id FROM tourist_destinations WHERE slug = 'world-peace-pagoda-lumbini'), 4, 'Japanese peace stupa', NOW()),
((SELECT id FROM itinerary_days WHERE itinerary_id = (SELECT id FROM destination_itineraries WHERE slug = 'lumbini-buddhist-pilgrimage') AND day_number = 3), (SELECT id FROM tourist_destinations WHERE slug = 'monastic-zone-lumbini'), 1, 'International monasteries tour', NOW());
