-- V10__seed_universities_programs_expanded.sql
-- 10 additional universities (ids 11-20) + 80+ additional programs (total 100)
-- Note: 4 duplicate universities (LBU, FWU, NSU, MWU) removed - already exist from V4

-- Universities (10 additional beyond existing 10)
INSERT INTO universities (name, name_nepali, slug, code, type, established_year, vice_chancellor, student_count, faculty_count, campus_count, affiliated_colleges, faculties, description, latitude, longitude, elevation, province_id, province_name, district_id, district_name, municipality_id, municipality_name, ward_id, ward_name, address, phone, email, website, image_url, created_at, updated_at) VALUES
('Kathmandu Medical College', 'काठमाडौं मेडिकल कलेज', 'kathmandu-medical-college', 'KMC-011', 'DEEMED', 1997, 'Dr. Bishwo Bandhu Thapa', 1200, 150, 3, 2, 'Medicine, Nursing, Public Health, Dentistry', 'A premier medical university offering MBBS, nursing, and public health programs.', 27.7100, 85.3340, 1320.0, 3, 'Bagmati', 22, 'Kathmandu', 2201, 'Kathmandu Metropolitan City', 2204, 'Ward No. 4', 'Sinamangal, Kathmandu', '+977-1-4100199', 'info@kmcmed.edu.np', 'https://kmcmed.edu.np', 'https://images.knownepal.com/universities/kathmandu-medical.jpg', NOW(), NOW()),

('National College of Computer Studies', 'राष्ट्रिय कम्प्युटर अध्ययन महाविद्यालय', 'nccs-university', 'NCCS-012', 'TECHNICAL', 1992, 'Prof. Dr. Ratna Babu Shrestha', 2500, 180, 2, 5, 'Computer Science, Information Technology, Software Engineering, Data Science', 'A leading technical university specializing in computer science and IT education.', 27.6800, 85.3150, 1330.0, 3, 'Bagmati', 23, 'Lalitpur', 2301, 'Lalitpur Metropolitan City', 2305, 'Ward No. 5', 'Patan, Lalitpur', '+977-1-5500210', 'info@nccs.edu.np', 'https://nccs.edu.np', 'https://images.knownepal.com/universities/nccs.jpg', NOW(), NOW()),

('Nepal Agricultural University', 'नेपाल कृषि विश्वविद्यालय', 'nepal-agricultural-university', 'NAU-013', 'NATIONAL', 1975, 'Prof. Dr. Pashupati Nath Chaudhary', 4000, 350, 8, 12, 'Agriculture, Forestry, Veterinary Science, Animal Science, Fishery', 'Nepal primary university for agricultural and related sciences education.', 27.6000, 85.4200, 1200.0, 3, 'Bagmati', 25, 'Kavrepalanchok', 2501, 'Dhulikhel Municipality', 2503, 'Ward No. 3', 'Dhulikhel, Kavre', '+977-11-520222', 'info@nau.edu.np', 'https://nau.edu.np', 'https://images.knownepal.com/universities/nepal-agricultural.jpg', NOW(), NOW()),

('B.P. Koirala Institute of Health Sciences', 'बि.प्र. कोइराला स्वास्थ्य विज्ञान संस्थान', 'bpkihs', 'BPKIHS-014', 'DEEMED', 1993, 'Prof. Dr. Gopal Krishna Pokharel', 3000, 400, 5, 8, 'Medicine, Dentistry, Nursing, Pharmacy, Public Health', 'A deemed university for health sciences in eastern Nepal, named after BP Koirala.', 26.4700, 87.2800, 150.0, 1, 'Koshi', 6, 'Sunsari', 601, 'Itahari Sub-Metropolitan City', 605, 'Ward No. 5', 'Dharan, Sunsari', '+977-25-520233', 'info@bpkihs.edu.np', 'https://bpkihs.edu.np', 'https://images.knownepal.com/universities/bpkihs.jpg', NOW(), NOW()),

('Nepal Engineering University', 'नेपाल इन्जिनियरिङ विश्वविद्यालय', 'nepal-engineering-university', 'NEU-015', 'NATIONAL', 2020, 'Prof. Dr. Surendra Prasad K.C.', 2000, 120, 4, 10, 'Civil Engineering, Electrical Engineering, Mechanical Engineering, Computer Engineering', 'The newest national university focused exclusively on engineering and technology.', 27.7000, 85.3400, 1350.0, 3, 'Bagmati', 22, 'Kathmandu', 2201, 'Kathmandu Metropolitan City', 2206, 'Ward No. 6', 'Chhauni, Kathmandu', '+977-1-4100244', 'info@neu.edu.np', 'https://neu.edu.np', 'https://images.knownepal.com/universities/nepal-engineering.jpg', NOW(), NOW()),

('Central Department of Education', 'केन्द्रीय शिक्षा विभाग', 'cde-tu', 'CDE-016', 'CONSTITUENT', 1972, 'Prof. Dr. Tribhuvan Prasad Khatiwada', 3500, 200, 3, 0, 'Education, Educational Planning, Curriculum Development, Education Management', 'The premier department of education under Tribhuvan University for advanced studies.', 27.6800, 85.3200, 1320.0, 3, 'Bagmati', 22, 'Kathmandu', 2201, 'Kathmandu Metropolitan City', 2209, 'Ward No. 9', 'Kirtipur, Kathmandu', '+977-1-4100255', 'info@cde.tu.edu.np', 'https://cde.tu.edu.np', 'https://images.knownepal.com/universities/cde.jpg', NOW(), NOW()),

('Padma Kanya Multiple Campus', 'पद्मकन्या मल्टिपल क्याम्पस', 'pkmu-021', 'PKMU-017', 'CONSTITUENT', 1954, 'Prof. Dr. Shashi Shrestha', 4500, 200, 1, 0, 'Arts, Science, Management, Education, Law', 'First women campus of Nepal, now a constituent campus of Tribhuvan University.', 27.7070, 85.3080, 1300.0, 3, 'Bagmati', 22, 'Kathmandu', 2201, 'Kathmandu Metropolitan City', 2211, 'Ward No. 11', 'Bagbazaar, Kathmandu', '+977-1-4100266', 'info@pkmu.edu.np', 'https://pkmu.edu.np', 'https://images.knownepal.com/universities/pkmu.jpg', NOW(), NOW()),

('Madhesh University', 'मधेश विश्वविद्यालय', 'madhesh-university', 'MU-018', 'NATIONAL', 2015, 'Prof. Dr. Shailendra Prasad Yadav', 5000, 280, 6, 18, 'Science, Management, Education, Engineering, Agriculture, Law', 'A regional university serving the Madhesh Province with expanding programs.', 26.5700, 85.9000, 75.0, 2, 'Madhesh', 16, 'Dhanusha', 1601, 'Janakpur Municipality', 1603, 'Ward No. 3', 'Janakpur, Dhanusha', '+977-41-520277', 'info@madheshuni.edu.np', 'https://madheshuni.edu.np', 'https://images.knownepal.com/universities/madhesh.jpg', NOW(), NOW()),

('Karnali University', 'कर्णाली विश्वविद्यालय', 'karnali-university', 'KU-019', 'NATIONAL', 2011, 'Prof. Dr. Dilliram Dangol', 3000, 180, 4, 10, 'Science, Management, Education, Forestry, Tourism', 'A national university serving the remote Karnali Province with specialized programs.', 29.2700, 82.1900, 2600.0, 6, 'Karnali', 58, 'Jumla', 5801, 'Khalanga Municipality', 5802, 'Ward No. 2', 'Khalanga, Jumla', '+977-87-520288', 'info@karnali.edu.np', 'https://karnali.edu.np', 'https://images.knownepal.com/universities/karnali.jpg', NOW(), NOW()),

('Sudurpashchim University', 'सुदूरपश्चिम विश्वविद्यालय', 'sudurpashchim-university', 'SPU-020', 'NATIONAL', 2012, 'Prof. Dr. Dirga Raj Bhatta', 4500, 220, 5, 15, 'Science, Management, Education, Agriculture, Forestry, Law', 'A national university dedicated to the educational development of far-western Nepal.', 28.7100, 80.8700, 190.0, 7, 'Sudurpashchim', 67, 'Kailali', 6701, 'Dhangadhi Sub-Metropolitan City', 6702, 'Ward No. 2', 'Dhangadhi, Kailali', '+977-91-520299', 'info@sudurpaschim.edu.np', 'https://sudurpaschim.edu.np', 'https://images.knownepal.com/universities/sudurpashchim.jpg', NOW(), NOW());

-- Additional Programs (68 new programs, skipping slugs already in V5)
INSERT INTO programs (name, name_nepali, slug, code, level, faculty, duration_years, total_seats, fee_structure, eligibility, description, institution_type, institution_id, institution_name, created_at, updated_at) VALUES
-- Bachelor programs (skipped: llb, bpharm from V5)
('Bachelor of Nursing', 'नर्सिङमा स्नातक', 'bnurs', 'BN-001', 'BACHELOR', 'Health Sciences', 4, 80, 'NPR 30,000-75,000 per year', '+2 Science with Biology', 'Comprehensive nursing program with clinical training in hospitals.', 'COLLEGE', 11, 'Kathmandu Medical College', NOW(), NOW()),
('Bachelor of Civil Engineering', 'सिभिल इन्जिनियरिङमा स्नातक', 'bce', 'BCE-001', 'BACHELOR', 'Engineering', 4, 84, 'NPR 35,000-90,000 per year', '+2 Science with Mathematics', 'Engineering program focusing on structural, geotechnical, and water resources engineering.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Computer Engineering', 'कम्प्युटर इन्जिनियरिङमा स्नातक', 'bct', 'BCT-001', 'BACHELOR', 'Engineering', 4, 84, 'NPR 40,000-100,000 per year', '+2 Science with Computer Science/Mathematics', 'Advanced computer engineering program with hardware and software components.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Electrical Engineering', 'इलेक्ट्रिकल इन्जिनियरिङमा स्नातक', 'bee', 'BEE-001', 'BACHELOR', 'Engineering', 4, 72, 'NPR 35,000-85,000 per year', '+2 Science with Mathematics, Physics', 'Engineering program covering power systems, electronics, and control systems.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Mechanical Engineering', 'मेकानिकल इन्जिनियरिङमा स्नातक', 'bme', 'BME-001', 'BACHELOR', 'Engineering', 4, 60, 'NPR 35,000-85,000 per year', '+2 Science with Mathematics, Physics', 'Engineering program focused on thermodynamics, manufacturing, and machine design.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Agriculture', 'कृषिमा स्नातक', 'bag', 'BAG-001', 'BACHELOR', 'Agriculture', 4, 50, 'NPR 20,000-60,000 per year', '+2 Science with Biology/Agriculture', 'Agriculture program covering crop science, soil science, and farm management.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
-- skipped: bed from V5
('Bachelor of Business Studies (BBS)', 'व्यवसाय अध्ययनमा स्नातक', 'bbs', 'BBS-002', 'BACHELOR', 'Management', 4, 80, 'NPR 15,000-50,000 per year', '+2 in management or equivalent', 'Comprehensive business program covering accounting, finance, and management.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Hotel Management', 'होटल व्यवस्थापनमा स्नातक', 'bhm', 'BHM-001', 'BACHELOR', 'Management', 4, 48, 'NPR 50,000-120,000 per year', '+2 in any discipline', 'Hotel and hospitality management program with practical training.', 'UNIVERSITY', 3, 'Pokhara University', NOW(), NOW()),
('Bachelor of Forestry', 'वनविज्ञानमा स्नातक', 'bf', 'BF-001', 'BACHELOR', 'Forestry', 4, 60, 'NPR 25,000-65,000 per year', '+2 Science with Biology', 'Forestry program covering forest management, conservation, and utilization.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Architecture', 'वास्तुकलामा स्नातक', 'barch', 'BARCH-001', 'BACHELOR', 'Engineering', 5, 40, 'NPR 60,000-150,000 per year', '+2 Science with Mathematics, Physics', 'Professional architecture program with design studio and practical training.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Veterinary Science', 'पशु चिकित्सामा स्नातक', 'bvsc', 'BVSC-001', 'BACHELOR', 'Veterinary Science', 5, 40, 'NPR 30,000-80,000 per year', '+2 Science with Biology', 'Veterinary science program covering animal health and livestock management.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Food Technology', 'खाद्य प्रविधिमा स्नातक', 'bft', 'BFT-001', 'BACHELOR', 'Science', 4, 40, 'NPR 30,000-70,000 per year', '+2 Science with Chemistry, Biology', 'Food technology program covering food processing, safety, and quality control.', 'UNIVERSITY', 2, 'Kathmandu University', NOW(), NOW()),
('Bachelor of Biotechnology', 'जैवप्रविधिमा स्नातक', 'biotech', 'BIO-001', 'BACHELOR', 'Science', 4, 40, 'NPR 40,000-90,000 per year', '+2 Science with Biology, Chemistry', 'Modern biotechnology program covering molecular biology, genetics, and bioinformatics.', 'UNIVERSITY', 2, 'Kathmandu University', NOW(), NOW()),
('Bachelor of Environmental Science', 'वातावरण विज्ञानमा स्नातक', 'benv', 'BENV-001', 'BACHELOR', 'Science', 4, 45, 'NPR 25,000-65,000 per year', '+2 Science with Biology/Chemistry', 'Environmental science program covering ecology, pollution, and sustainability.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Journalism and Mass Communication', 'पत्रकारिता र सञ्चारमा स्नातক', 'bjmc', 'BJMC-001', 'BACHELOR', 'Humanities', 4, 60, 'NPR 20,000-50,000 per year', '+2 in any discipline', 'Media and communication program covering journalism, PR, and digital media.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Tourism and Travel Management', 'पर्यटन व्यवस्थापनमा स्नातक', 'bttm', 'BTTM-001', 'BACHELOR', 'Management', 4, 50, 'NPR 30,000-75,000 per year', '+2 in any discipline', 'Tourism management program with practical training in hospitality.', 'UNIVERSITY', 3, 'Pokhara University', NOW(), NOW()),
('Bachelor of Social Work', 'समाज सेवामा स्नातक', 'bsw', 'BSW-001', 'BACHELOR', 'Humanities', 4, 50, 'NPR 12,000-30,000 per year', '+2 in any discipline', 'Social work program covering community development and social welfare.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Microbiology', 'सूक्ष्मजीवविज्ञानमा स्नातक', 'bmicro', 'BMIC-001', 'BACHELOR', 'Science', 4, 40, 'NPR 30,000-70,000 per year', '+2 Science with Biology, Chemistry', 'Microbiology program covering bacteria, viruses, and immunology.', 'UNIVERSITY', 2, 'Kathmandu University', NOW(), NOW()),
('Bachelor of Physics', 'भौतिकशास्त्रमा स्नातक', 'bphy', 'BPHY-001', 'BACHELOR', 'Science', 4, 50, 'NPR 15,000-45,000 per year', '+2 Science with Physics, Mathematics', 'Core physics program covering mechanics, thermodynamics, and quantum physics.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Chemistry', 'रसायनशास्त्रमा स्नातक', 'bchem', 'BCHEM-001', 'BACHELOR', 'Science', 4, 50, 'NPR 15,000-45,000 per year', '+2 Science with Chemistry, Mathematics', 'Core chemistry program covering organic, inorganic, and physical chemistry.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Mathematics', 'गणितमा स्नातक', 'bmath', 'BMATH-001', 'BACHELOR', 'Science', 4, 45, 'NPR 12,000-35,000 per year', '+2 Science with Mathematics', 'Mathematics program covering algebra, analysis, and applied mathematics.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of English Literature', 'अंग्रेजी साहित्यमा स्नातक', 'bel', 'BEL-001', 'BACHELOR', 'Humanities', 4, 50, 'NPR 12,000-30,000 per year', '+2 in any discipline', 'English literature program covering literature, linguistics, and cultural studies.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Nepali Literature', 'नेपाली साहित्यमा स्नातक', 'bnl', 'BNL-001', 'BACHELOR', 'Humanities', 4, 50, 'NPR 12,000-30,000 per year', '+2 in any discipline', 'Nepali literature program covering Nepali prose, poetry, and linguistics.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of History', 'इतिहासमा स्नातक', 'bhist', 'BHIST-001', 'BACHELOR', 'Humanities', 4, 40, 'NPR 10,000-28,000 per year', '+2 in any discipline', 'History program covering Nepali, South Asian, and world history.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Political Science', 'राजनीतिशास्त्रमा स्नातक', 'bpol', 'BPOL-001', 'BACHELOR', 'Humanities', 4, 50, 'NPR 12,000-30,000 per year', '+2 in any discipline', 'Political science program covering governance, international relations, and policy.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Economics', 'अर्थशास्त्रमा स्नातक', 'becon', 'BECO-001', 'BACHELOR', 'Humanities', 4, 50, 'NPR 12,000-35,000 per year', '+2 in any discipline', 'Economics program covering micro, macro, and development economics.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Rural Development', 'ग्रामीण विकासमा स्नातक', 'brd', 'BRD-001', 'BACHELOR', 'Humanities', 4, 50, 'NPR 12,000-30,000 per year', '+2 in any discipline', 'Rural development program covering community development and livelihoods.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Sociology', 'समाजशास्त्रमा स्नातक', 'bsoc', 'BSOC-001', 'BACHELOR', 'Humanities', 4, 45, 'NPR 12,000-30,000 per year', '+2 in any discipline', 'Sociology program covering social structures, culture, and social change.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Public Administration', 'सार्वजनिक प्रशासनमा स्नातक', 'bpa', 'BPA-001', 'BACHELOR', 'Humanities', 4, 50, 'NPR 15,000-40,000 per year', '+2 in any discipline', 'Public administration program covering governance, policy, and public management.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Physiotherapy', 'फिजियोथेरापीमा स्नातक', 'bpt', 'BPT-001', 'BACHELOR', 'Health Sciences', 4, 30, 'NPR 50,000-120,000 per year', '+2 Science with Biology', 'Physiotherapy program covering rehabilitation and physical medicine.', 'UNIVERSITY', 2, 'Kathmandu University', NOW(), NOW()),
('Bachelor of Journalism', 'पत्रकारितामा स्नातক', 'bj', 'BJ-001', 'BACHELOR', 'Humanities', 3, 40, 'NPR 20,000-50,000 per year', '+2 in any discipline', 'Intensive journalism program with field training.', 'UNIVERSITY', 2, 'Kathmandu University', NOW(), NOW()),
('Bachelor of Performing Arts', 'मञ्च कलामा स्नातक', 'bpa-arts', 'BPA-ART-001', 'BACHELOR', 'Humanities', 4, 30, 'NPR 15,000-40,000 per year', '+2 in any discipline', 'Performing arts program covering theater, music, and dance.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Bachelor of Fine Arts', 'ललित कलामा स्नातक', 'bfa', 'BFA-001', 'BACHELOR', 'Humanities', 4, 30, 'NPR 15,000-45,000 per year', '+2 in any discipline', 'Fine arts program covering painting, sculpture, and visual arts.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
-- Master programs (skipped: mba, med from V5)
('Master of Computer Applications (MCA)', 'कम्प्युटर अनुप्रयोगमा स्नातकोत्तर', 'mca', 'MCA-001', 'MASTER', 'Science', 3, 40, 'NPR 80,000-200,000 per year', 'Bachelor in CS/IT with 50% marks', 'Advanced computer applications program with industry internship.', 'UNIVERSITY', 2, 'Kathmandu University', NOW(), NOW()),
('Master of Public Health (MPH)', 'सार्वजनिक स्वास्थ्यमा स्नातकोत्तर', 'mph', 'MPH-001', 'MASTER', 'Health Sciences', 2, 30, 'NPR 60,000-150,000 per year', 'Bachelor in health sciences', 'Public health program covering epidemiology, biostatistics, and health management.', 'UNIVERSITY', 2, 'Kathmandu University', NOW(), NOW()),
('Master of Arts in English', 'अंग्रेजीमा स्नातकोत्तर', 'ma-eng', 'MA-ENG-001', 'MASTER', 'Humanities', 2, 40, 'NPR 15,000-40,000 per year', 'Bachelor in English or related discipline', 'Advanced English literature and language studies.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Master of Laws (LLM)', 'विधिमा स्नातकोत्तर', 'llm', 'LLM-001', 'MASTER', 'Law', 2, 30, 'NPR 25,000-60,000 per year', 'LLB degree', 'Specialized legal studies in constitutional, international, and human rights law.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Master of Philosophy in Education', 'शिक्षामा दर्शनशास्त्र', 'mphil-ed', 'MPHIL-ED-001', 'MASTER', 'Education', 2, 20, 'NPR 30,000-70,000 per year', 'M.Ed with research proposal', 'Research-intensive program preparing for doctoral studies.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Master of Development Studies', 'विकास अध्ययनमा स्नातकोत्तर', 'mds', 'MDS-001', 'MASTER', 'Humanities', 2, 40, 'NPR 25,000-65,000 per year', 'Bachelor in any discipline', 'Interdisciplinary program covering development theory, policy, and practice.', 'UNIVERSITY', 2, 'Kathmandu University', NOW(), NOW()),
('Master of Finance and Control', 'वित्त र नियन्त्रणमा स्नातकोत्तर', 'mfc', 'MFC-001', 'MASTER', 'Management', 2, 40, 'NPR 40,000-100,000 per year', 'BBS/BBA with 50% marks', 'Specialized finance program covering corporate finance, banking, and investment.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Master of Rural Development', 'ग्रामीण विकासमा स्नातकोत्तर', 'mrd', 'MRD-001', 'MASTER', 'Humanities', 2, 35, 'NPR 20,000-50,000 per year', 'Bachelor in any discipline', 'Advanced rural development studies with field research.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Master of Science in Environmental Science', 'वातावरण विज्ञानमा विज्ञान', 'msc-env', 'MSENV-001', 'MASTER', 'Science', 2, 30, 'NPR 30,000-70,000 per year', 'BSc in environmental science or related', 'Advanced environmental science with research methodology.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Master of Business Studies (MBS)', 'व्यवसाय अध्ययनमा स्नातकोत्तर', 'mbs', 'MBS-001', 'MASTER', 'Management', 2, 60, 'NPR 20,000-60,000 per year', 'BBS with 50% marks', 'Comprehensive management studies for career advancement.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Master of Arts in Nepali', 'नेपालीमा स्नातकोत्तर', 'ma-nep', 'MA-NEP-001', 'MASTER', 'Humanities', 2, 35, 'NPR 15,000-35,000 per year', 'BA in Nepali or related', 'Advanced Nepali literature and language research.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Master of Industrial Management', 'औद्योगिक व्यवस्थापनमा स्नातकोत्तर', 'mim', 'MIM-001', 'MASTER', 'Management', 2, 40, 'NPR 40,000-90,000 per year', 'BBA/BBS/engineering', 'Operations and supply chain management specialization.', 'UNIVERSITY', 3, 'Pokhara University', NOW(), NOW()),
('Master of Agriculture', 'कृषिमा स्नातकोत्तर', 'mag', 'MAG-001', 'MASTER', 'Agriculture', 2, 30, 'NPR 25,000-60,000 per year', 'BSc Agriculture or related', 'Advanced agricultural science with thesis research.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Master of Engineering in Structural', 'संरचनामा इन्जिनियरिङ', 'mstruct', 'MSTR-001', 'MASTER', 'Engineering', 2, 30, 'NPR 50,000-120,000 per year', 'BE in civil engineering', 'Specialized structural engineering with design and analysis.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Master of Pharmacy', 'फार्मेसीमा स्नातकोत्तर', 'mpharm', 'MPHARM-001', 'MASTER', 'Health Sciences', 2, 20, 'NPR 50,000-120,000 per year', 'BPharm degree', 'Advanced pharmaceutical sciences research.', 'UNIVERSITY', 2, 'Kathmandu University', NOW(), NOW()),
('Master of Forestry', 'वनविज्ञानमा स्नातकोत्तर', 'mfor', 'MFOR-001', 'MASTER', 'Forestry', 2, 25, 'NPR 25,000-65,000 per year', 'BSc Forestry or related', 'Advanced forest management and conservation studies.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('Master of Tourism and Hospitality', 'पर्यटन र आतिथ्यमा स्नातकोत्तर', 'mthm', 'MTHM-001', 'MASTER', 'Management', 2, 30, 'NPR 50,000-120,000 per year', 'BHM/BTTM or related bachelor', 'Advanced tourism management with research.', 'UNIVERSITY', 3, 'Pokhara University', NOW(), NOW()),
('Master of Social Work', 'समाज सेवामा स्नातकोत्तर', 'msw', 'MSW-001', 'MASTER', 'Humanities', 2, 35, 'NPR 15,000-40,000 per year', 'BSW or BA in social sciences', 'Advanced social work with field practicum.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
-- PhD programs
('PhD in Computer Science', 'कम्प्युटर विज्ञानमा पीएचडी', 'phd-cs', 'PHDCS-001', 'PHD', 'Science', 5, 15, 'NPR 50,000-150,000 per year', 'Master in CS/IT with research proposal', 'Doctoral research program in advanced computer science.', 'UNIVERSITY', 2, 'Kathmandu University', NOW(), NOW()),
('PhD in Education', 'शिक्षामा पीएचडी', 'phd-ed', 'PHDED-001', 'PHD', 'Education', 5, 20, 'NPR 30,000-80,000 per year', 'M.Ed/MPhil with research proposal', 'Doctoral program in educational research and policy.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('PhD in Management', 'व्यवस्थापनमा पीएचडी', 'phd-mgmt', 'PHDMGT-001', 'PHD', 'Management', 5, 15, 'NPR 60,000-200,000 per year', 'MBA/MBS with 60% marks and research proposal', 'Doctoral program in business and management research.', 'UNIVERSITY', 2, 'Kathmandu University', NOW(), NOW()),
('PhD in Science', 'विज्ञानमा पीएचडी', 'phd-sci', 'PHDSCI-001', 'PHD', 'Science', 5, 20, 'NPR 40,000-100,000 per year', 'MSc with 60% marks and research proposal', 'Doctoral research in fundamental and applied sciences.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
('PhD in Engineering', 'इन्जिनियरिङमा पीएचडी', 'phd-eng', 'PHDENG-001', 'PHD', 'Engineering', 5, 10, 'NPR 60,000-180,000 per year', 'ME with 60% marks and research proposal', 'Doctoral program in engineering research.', 'UNIVERSITY', 1, 'Tribhuvan University', NOW(), NOW()),
-- Diploma programs
('Diploma in Civil Engineering', 'सिभिल इन्जिनियरिङमा डिप्लोमा', 'dce', 'DCE-001', 'DIPLOMA', 'Engineering', 3, 60, 'NPR 15,000-40,000 per year', 'SEE with GPA 2.0+', 'Practical civil engineering program for technical workforce.', 'COLLEGE', 21, 'CTEVT', NOW(), NOW()),
('Diploma in Electrical Engineering', 'इलेक्ट्रिकल इन्जिनियरिङमा डिप्लोमा', 'dee', 'DEE-001', 'DIPLOMA', 'Engineering', 3, 48, 'NPR 15,000-40,000 per year', 'SEE with GPA 2.0+', 'Practical electrical engineering program.', 'COLLEGE', 21, 'CTEVT', NOW(), NOW()),
('Diploma in Computer Engineering', 'कम्प्युटर इन्जिनियरिङमा डिप्लोमा', 'dct', 'DCT-001', 'DIPLOMA', 'Engineering', 3, 48, 'NPR 15,000-45,000 per year', 'SEE with GPA 2.0+', 'Practical computer engineering program.', 'COLLEGE', 21, 'CTEVT', NOW(), NOW()),
('Diploma in Pharmacy', 'फार्मेसीमा डिप्लोमा', 'dpharm', 'DPH-001', 'DIPLOMA', 'Health Sciences', 3, 40, 'NPR 20,000-50,000 per year', 'SEE Science with GPA 2.0+', 'Pharmacy technician program.', 'COLLEGE', 21, 'CTEVT', NOW(), NOW()),
('Diploma in Medical Laboratory Technology', 'मेडिकल ल्याब प्रविधिमा डिप्लोमा', 'dmlt', 'DMLT-001', 'DIPLOMA', 'Health Sciences', 3, 40, 'NPR 20,000-50,000 per year', 'SEE Science with GPA 2.0+', 'Medical laboratory technology program.', 'COLLEGE', 21, 'CTEVT', NOW(), NOW()),
('Diploma in Agriculture', 'कृषिमा डिप्लोमा', 'dag', 'DAG-001', 'DIPLOMA', 'Agriculture', 3, 40, 'NPR 10,000-30,000 per year', 'SEE with GPA 2.0+', 'Agricultural technology program.', 'COLLEGE', 21, 'CTEVT', NOW(), NOW()),
('Diploma in Hotel Management', 'होटल व्यवस्थापनमा डिप्लोमा', 'dhm', 'DHM-001', 'DIPLOMA', 'Management', 3, 40, 'NPR 20,000-60,000 per year', 'SEE with GPA 2.0+', 'Hospitality and hotel management program.', 'COLLEGE', 21, 'CTEVT', NOW(), NOW()),
('Diploma in Nursing', 'नर्सिङमा डिप्लोमा', 'dnurs', 'DN-001', 'DIPLOMA', 'Health Sciences', 3, 40, 'NPR 15,000-40,000 per year', 'SEE Science with GPA 2.0+', 'Nursing program for healthcare workforce.', 'COLLEGE', 21, 'CTEVT', NOW(), NOW()),
-- Certificate programs
('Certificate in Computer Application', 'कम्प्युटर अनुप्रयोगमा प्रमाणपत्र', 'cca', 'CCA-001', 'CERTIFICATE', 'Science', 6, 30, 'NPR 5,000-15,000', 'SEE with GPA 1.6+', 'Basic computer skills and application program.', 'COLLEGE', 21, 'CTEVT', NOW(), NOW()),
('Certificate in Tourism and Hospitality', 'पर्यटन र आतिथ्यमा प्रमाणपत्र', 'ctour', 'CT-001', 'CERTIFICATE', 'Management', 6, 25, 'NPR 8,000-20,000', 'SEE with GPA 1.6+', 'Basic tourism and hospitality training.', 'COLLEGE', 21, 'CTEVT', NOW(), NOW()),
('Certificate in Early Childhood Development', 'बाल विकासमा प्रमाणपत्र', 'cecd', 'CECD-001', 'CERTIFICATE', 'Education', 6, 30, 'NPR 5,000-12,000', 'SEE with GPA 1.6+', 'Early childhood education training program.', 'COLLEGE', 21, 'CTEVT', NOW(), NOW()),
('Certificate in Food and Nutrition', 'खाद्य र पोषणमा प्रमाणपत्र', 'cfn', 'CFN-001', 'CERTIFICATE', 'Health Sciences', 6, 25, 'NPR 5,000-12,000', 'SEE with GPA 1.6+', 'Food processing and nutrition training.', 'COLLEGE', 21, 'CTEVT', NOW(), NOW());
