-- V3__seed_colleges.sql
-- 20 real Nepali colleges

INSERT INTO colleges (name, name_nepali, slug, code, type, level, established_year, affiliation, student_count, teacher_count, facilities, description, province_id, province_name, district_id, district_name, municipality_id, municipality_name, address, phone, email, website, created_at, updated_at) VALUES
('St. Xavier''s College', 'सेन्ट जेभियर्स कलेज', 'st-xaviers-college', 'SXC-001', 'PRIVATE', 'HIGHER_SECONDARY', 1988, 'NEB / Tribhuvan University', 3500, 150, 'Science labs, computer lab, library, sports ground, auditorium', 'One of the most prestigious colleges in Nepal offering +2 and bachelor programs in science, management, and humanities.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Maharajgunj, Kathmandu', '+977-1-4100101', 'info@stxaviers.edu.np', 'https://stxaviers.edu.np', NOW(), NOW()),

('Padma Kanya Multiple Campus', 'पद्मकन्या मल्टिपल क्याम्पस', 'padma-kanya-campus', 'PKC-002', 'GOVERNMENT', 'BACHELOR', 1954, 'Tribhuvan University', 4000, 180, 'Central library, science labs, auditorium, computer center', 'The first women''s college in Nepal, offering undergraduate programs in arts, science, and management.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Bagbazaar, Kathmandu', '+977-1-4100102', 'info@padmakanya.edu.np', 'https://padmakanya.edu.np', NOW(), NOW()),

('Birendra Sainik Awashiya Mahavidyalaya', 'बीरेन्द्र सैनिक आवासीय महाविद्यालय', 'birendra-sainik-college', 'BSA-003', 'GOVERNMENT', 'HIGHER_SECONDARY', 1981, 'NEB / Tribhuvan University', 2800, 120, 'Hostels, sports complex, science labs, library', 'A residential college established for children of Nepal Army personnel, also open to general public.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Kathmandu Cantonment', '+977-1-4100103', 'info@birendrasainik.edu.np', 'https://birendrasainik.edu.np', NOW(), NOW()),

('National School of Science', 'राष्ट्रिय विज्ञान विद्यालय', 'national-school-of-science', 'NSS-004', 'GOVERNMENT', 'HIGHER_SECONDARY', 1985, 'NEB', 2200, 100, 'Advanced science labs, robotics lab, astronomy observatory, library', 'A government-funded institution dedicated to producing top science graduates in Nepal.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Dillibazar, Kathmandu', '+977-1-4100104', 'info@nss.edu.np', 'https://nss.edu.np', NOW(), NOW()),

('Amrit Science Campus', 'अमृत विज्ञान क्याम्पस', 'amrit-science-campus', 'ASC-005', 'GOVERNMENT', 'BACHELOR', 1961, 'Tribhuvan University', 3000, 140, 'Science labs, central library, research center', 'One of the oldest science campuses in Nepal offering BSc programs in physics, chemistry, math, and biology.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Lainchaur, Kathmandu', '+977-1-4100105', 'info@amritscience.edu.np', 'https://amritscience.edu.np', NOW(), NOW()),

('Kathmandu Model College', 'काठमाडौं मोडेल कलेज', 'kathmandu-model-college', 'KMC-006', 'PRIVATE', 'BACHELOR', 2000, 'Tribhuvan University', 3200, 130, 'Computer lab, library, cafeteria, auditorium', 'A popular private college offering BBA, BBS, and MBS programs with industry-oriented curriculum.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Baneshwor, Kathmandu', '+977-1-4100106', 'info@kathmandumodelcollege.edu.np', 'https://kathmandumodelcollege.edu.np', NOW(), NOW()),

('Lumbini Buddha College', 'लुम्बिनी बुद्ध कलेज', 'lumbini-buddha-college', 'LBC-007', 'PRIVATE', 'BACHELOR', 1995, 'Tribhuvan University', 2500, 110, 'Meditation hall, library, computer lab, cultural center', 'A college combining Buddhist philosophical education with modern academic programs.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Swayambhu, Kathmandu', '+977-1-4100107', 'info@lumbinibuddha.edu.np', 'https://lumbinibuddha.edu.np', NOW(), NOW()),

('Paschimanchal Campus', 'पश्चिमाञ्चल क्याम्पस', 'paschimanchal-campus', 'PWC-008', 'GOVERNMENT', 'BACHELOR', 1972, 'Mid-Western University', 2000, 90, 'Science labs, library, computer center, sports facilities', 'A major government campus in the mid-western region offering diverse academic programs.', 6, 'Karnali', 54, 'Surkhet', 577, 'Birendranagar', 'Birendranagar, Surkhet', '+977-81-520108', 'info@paschimanchal.edu.np', 'https://paschimanchal.edu.np', NOW(), NOW()),

('Far Western University Campus', 'सुदूरपश्चिम विश्वविद्यालय क्याम्पस', 'far-western-campus', 'FWC-009', 'GOVERNMENT', 'BACHELOR', 2010, 'Far-Western University', 1500, 70, 'Library, science labs, computer center', 'The main campus of Far-Western University offering bachelor programs in multiple disciplines.', 7, 'Sudurpashchim', 73, 'Kailali', 727, 'Dhangadhi', 'Dhangadhi, Kailali', '+977-91-520109', 'info@farwestern.edu.np', 'https://farwestern.edu.np', NOW(), NOW()),

('Nepal Law Campus', 'नेपाल विधि क्याम्पस', 'nepal-law-campus', 'NLC-010', 'GOVERNMENT', 'BACHELOR', 1956, 'Tribhuvan University', 1800, 80, 'Law library, moot court, legal aid clinic', 'The premier law education institution in Nepal offering LLB and BA LLB programs.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Trichandra College Road, Kathmandu', '+977-1-4100110', 'info@nepallaw.edu.np', 'https://nepallaw.edu.np', NOW(), NOW()),

('Kathmandu College of Management', 'काठमाडौं कलेज अफ म्यानेजमेन्ट', 'kathmandu-college-of-management', 'KCM-011', 'PRIVATE', 'BACHELOR', 1997, 'Tribhuvan University', 2800, 120, 'Business lab, seminar hall, library, IT center', 'A top-tier management college offering BBA and MBA programs with international collaboration.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Baluwatar, Kathmandu', '+977-1-4100111', 'info@kcm.edu.np', 'https://kcm.edu.np', NOW(), NOW()),

('B.P. Koirala Institute of Health Sciences', 'बी.पी. कोइराला स्वास्थ्य विज्ञान संस्थान', 'bpkihs-college', 'BPK-012', 'GOVERNMENT', 'BACHELOR', 1993, 'BP Koirala University', 3000, 200, 'Teaching hospital, medical labs, simulation center, library', 'A leading medical education institution offering MBBS, BDS, BSc Nursing, and other health science programs.', 2, 'Madhesh', 17, 'Dhanusha', 161, 'Janakpur', 'Dharan, Sunsari', '+977-25-520112', 'info@bpkihs.edu.np', 'https://bpkihs.edu.np', NOW(), NOW()),

('Pokhara University School of Management', 'पोखरा विश्वविद्यालय स्कुल अफ म्यानेजमेन्ट', 'pokhara-school-of-management', 'PSM-013', 'PRIVATE', 'BACHELOR', 2002, 'Pokhara University', 1500, 70, 'Case study rooms, IT lab, library, auditorium', 'A constituent school of Pokhara University offering modern management education.', 3, 'Bagmati', 36, 'Kaski', 400, 'Pokhara', 'Lumle Road, Pokhara', '+977-61-520113', 'info@psm.edu.np', 'https://psm.edu.np', NOW(), NOW()),

('National College of Computer Studies', 'राष्ट्रिय कम्प्युटर अध्ययन कलेज', 'nccs', 'NCC-014', 'PRIVATE', 'BACHELOR', 1999, 'Tribhuvan University', 1200, 60, 'Computer labs, networking lab, server room, digital library', 'A specialized IT college offering BCA, BSc CSIT, and computing programs.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Putalisadak, Kathmandu', '+977-1-4100114', 'info@nccs.edu.np', 'https://nccs.edu.np', NOW(), NOW()),

('Saraswati Multiple Campus', 'सरस्वती मल्टिपल क्याम्पस', 'saraswati-campus', 'SMC-015', 'GOVERNMENT', 'BACHELOR', 1968, 'Tribhuvan University', 3500, 150, 'Central library, arts hall, science labs', 'One of the largest government campuses in Kathmandu offering BA, BSc, and BBS programs.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Thamel, Kathmandu', '+977-1-4100115', 'info@saraswati.edu.np', 'https://saraswati.edu.np', NOW(), NOW()),

('Tribhuvan University Institute of Engineering', 'त्रिभुवन विश्वविद्यालय इन्जिनियरिङ संस्थान', 'tu-ioe', 'IOE-016', 'GOVERNMENT', 'BACHELOR', 1972, 'Tribhuvan University', 4500, 250, 'Engineering workshops, research labs, computing center, library', 'The premier engineering education institution in Nepal offering BE/BTech in various engineering disciplines.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Pulchowk, Lalitpur', '+977-1-5500116', 'info@ioe.edu.np', 'https://ioe.edu.np', NOW(), NOW()),

('Nepal Commerce Campus', 'नेपाल वाणिज्य क्याम्पस', 'nepal-commerce-campus', 'NCC-017', 'GOVERNMENT', 'BACHELOR', 1960, 'Tribhuvan University', 3800, 160, 'Commerce lab, library, banking simulation center', 'The largest commerce education campus in Nepal offering BBS, MBS, and BBA programs.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Minbhawan, Kathmandu', '+977-1-4100117', 'info@nepalcommerce.edu.np', 'https://nepalcommerce.edu.np', NOW(), NOW()),

('KIST Medical College', 'किस्ट मेडिकल कलेज', 'kist-medical-college', 'KMC-018', 'PRIVATE', 'BACHELOR', 2001, 'Kathmandu University', 1000, 80, 'Teaching hospital, medical labs, simulation center', 'A private medical college offering MBBS and nursing programs affiliated with Kathmandu University.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Gongabu, Kathmandu', '+977-1-4100118', 'info@kistmedical.edu.np', 'https://kistmedical.edu.np', NOW(), NOW()),

('Chitwan Medical College', 'चितवन मेडिकल कलेज', 'chitwan-medical-college', 'CMC-019', 'PRIVATE', 'BACHELOR', 2006, 'Tribhuvan University', 1200, 90, 'Teaching hospital, research center, medical labs', 'A leading medical college in central Nepal offering MBBS, BDS, and paramedical programs.', 3, 'Bagmati', 25, 'Chitwan', 284, 'Bharatpur', 'Bharatpur, Chitwan', '+977-56-520119', 'info@chitwanmedical.edu.np', 'https://chitwanmedical.edu.np', NOW(), NOW()),

('Thames International College', 'थेम्स इन्टरनेसनल कलेज', 'thames-college', 'TIC-020', 'PRIVATE', 'HIGHER_SECONDARY', 2008, 'NEB / Cambridge', 800, 40, 'Modern labs, library, creative studio, sports facility', 'An international college offering A-Levels, +2, and foundation programs with global standards.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Sanepa, Lalitpur', '+977-1-5500120', 'info@thames.edu.np', 'https://thames.edu.np', NOW(), NOW());
