-- V4__seed_universities.sql
-- 10 real Nepali universities

INSERT INTO universities (name, name_nepali, slug, code, type, established_year, student_count, faculty_count, campus_count, affiliated_colleges, faculties, description, province_id, province_name, district_id, district_name, municipality_id, municipality_name, address, phone, email, website, created_at, updated_at) VALUES
('Tribhuvan University', 'त्रिभुवन विश्वविद्यालय', 'tribhuvan-university', 'TU-001', 'NATIONAL', 1959, 500000, 7000, 60, 1200, 'Humanities, Science, Management, Education, Law, Engineering, Medical Science, Agriculture, Forestry, Veterinary Science', 'The oldest and largest university in Nepal, serving over half a million students across 60 campuses nationwide.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Kirtipur, Kathmandu', '+977-1-4100131', 'info@tu.edu.np', 'https://tu.edu.np', NOW(), NOW()),

('Kathmandu University', 'काठमाडौं विश्वविद्यालय', 'kathmandu-university', 'KU-002', 'COMMUNITY', 1991, 15000, 800, 12, 50, 'Engineering, Science, Management, Humanities, Education, Health Sciences, Law', 'A prestigious private university known for quality education and research, affiliated with top international institutions.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Dhulikhel, Kavre', '+977-1-6610132', 'info@ku.edu.np', 'https://ku.edu.np', NOW(), NOW()),

('Pokhara University', 'पोखरा विश्वविद्यालय', 'pokhara-university', 'PU-003', 'COMMUNITY', 1997, 25000, 600, 8, 80, 'Engineering, Management, Health Sciences, Science and Technology, Humanities', 'A leading university in western Nepal offering innovative programs with industry collaboration.', 3, 'Bagmati', 36, 'Kaski', 400, 'Pokhara', 'Lumle, Pokhara', '+977-61-520133', 'info@pu.edu.np', 'https://pu.edu.np', NOW(), NOW()),

('Purbanchal University', 'पूर्वाञ्चल विश्वविद्यालय', 'purbanchal-university', 'PrU-004', 'COMMUNITY', 1993, 30000, 500, 6, 60, 'Engineering, Health Sciences, Management, Science, Education, Forestry', 'Serving the eastern region of Nepal with diverse academic programs and research initiatives.', 4, 'Koshi', 5, 'Morang', 39, 'Biratnagar', 'Biratnagar, Morang', '+977-21-520134', 'info@purbanchal.edu.np', 'https://purbanchal.edu.np', NOW(), NOW()),

('Mid-Western University', 'मध्यपश्चिमाञ्चल विश्वविद्यालय', 'mid-western-university', 'MWU-005', 'NATIONAL', 2010, 15000, 350, 5, 40, 'Science, Education, Management, Humanities, Health Sciences', 'A newly established national university serving the mid-western region of Nepal.', 6, 'Karnali', 54, 'Surkhet', 577, 'Birendranagar', 'Birendranagar, Surkhet', '+977-81-520135', 'info@mwu.edu.np', 'https://mwu.edu.np', NOW(), NOW()),

('Far-Western University', 'सुदूरपश्चिमाञ्चल विश्वविद्यालय', 'far-western-university', 'FWU-006', 'NATIONAL', 2010, 10000, 250, 4, 30, 'Science, Education, Management, Humanities', 'The youngest national university serving the far-western development region of Nepal.', 7, 'Sudurpashchim', 73, 'Kailali', 727, 'Dhangadhi', 'Dhangadhi, Kailali', '+977-91-520136', 'info@fwu.edu.np', 'https://fwu.edu.np', NOW(), NOW()),

('Nepal Sanskrit University', 'नेपाल संस्कृत विश्वविद्यालय', 'nepal-sanskrit-university', 'NSU-007', 'NATIONAL', 1986, 5000, 200, 5, 25, 'Sanskrit Language, Vedic Studies, Buddhist Studies, Nepali Literature, Philosophy', 'The only university in Nepal dedicated to Sanskrit education and traditional Vedic learning.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Beljhundi, Dang', '+977-82-520137', 'info@nsu.edu.np', 'https://nsu.edu.np', NOW(), NOW()),

('Agriculture and Forestry University', 'कृषि तथा वन विश्वविद्यालय', 'afu', 'AFU-008', 'NATIONAL', 2009, 8000, 300, 3, 20, 'Agriculture, Forestry, Veterinary Science, Agricultural Engineering, Fishery', 'A specialized national university focusing on agricultural education and research for Nepal''s rural development.', 3, 'Bagmati', 25, 'Chitwan', 284, 'Bharatpur', 'Rampur, Chitwan', '+977-56-520138', 'info@afu.edu.np', 'https://afu.edu.np', NOW(), NOW()),

('Nepal Open University', 'नेपाल खुला विश्वविद्यालय', 'nepal-open-university', 'NOU-009', 'NATIONAL', 2017, 20000, 150, 2, 15, 'Education, Management, Law, Computer Science, Health Sciences', 'Nepal''s distance learning university offering flexible education through online and blended modes.', 3, 'Bagmati', 26, 'Kathmandu', 299, 'Kathmandu', 'Sanothimi, Bhaktapur', '+977-1-6610139', 'info@nou.edu.np', 'https://nou.edu.np', NOW(), NOW()),

('Lumbini Buddhist University', 'लुम्बिनी बौद्ध विश्वविद्यालय', 'lumbini-buddhist-university', 'LBU-010', 'NATIONAL', 2004, 3000, 120, 3, 15, 'Buddhist Studies, Philosophy, Peace Studies, Nepal Studies, English Literature', 'A unique university dedicated to Buddhist education and peace studies, located in the birthplace of Lord Buddha.', 5, 'Lumbini', 46, 'Rupandehi', 491, 'Siddharthanagar', 'Siddharthanagar, Lumbini', '+977-71-520140', 'info@lumbini.edu.np', 'https://lumbini.edu.np', NOW(), NOW());
