-- V6__enrich_education_data.sql
-- Enrich existing records with coordinates, ward info, viceChancellors, images, areaSqKm

-- === SCHOOLS: Add coordinates, ward info, areaSqKm, images ===
UPDATE schools SET latitude = 27.8125, longitude = 85.3620, elevation = 1350, ward_id = 301, ward_name = 'Ward 16', area_sq_km = 12.5, image_url = 'https://images.knownepal.com/schools/budhanilkantha.jpg' WHERE slug = 'budhanilkantha-school';
UPDATE schools SET latitude = 27.7105, longitude = 85.3340, elevation = 1320, ward_id = 302, ward_name = 'Ward 32', area_sq_km = 2.1, image_url = 'https://images.knownepal.com/schools/kathmandu-model.jpg' WHERE slug = 'kathmandu-model-school';
UPDATE schools SET latitude = 27.6780, longitude = 85.3260, elevation = 1280, ward_id = 303, ward_name = 'Ward 10', area_sq_km = 3.0, image_url = 'https://images.knownepal.com/schools/sos-hermann.jpg' WHERE slug = 'sos-hermann-gmeiner-school';
UPDATE schools SET latitude = 27.7100, longitude = 85.3130, elevation = 1310, ward_id = 304, ward_name = 'Ward 27', area_sq_km = 1.8, image_url = 'https://images.knownepal.com/schools/mahatma-gandhi.jpg' WHERE slug = 'mahatma-gandhi-school';
UPDATE schools SET latitude = 27.7160, longitude = 85.3240, elevation = 1330, ward_id = 305, ward_name = 'Ward 29', area_sq_km = 2.5, image_url = 'https://images.knownepal.com/schools/golden-gate.jpg' WHERE slug = 'golden-gate-international-school';
UPDATE schools SET latitude = 27.7070, longitude = 85.3080, elevation = 1300, ward_id = 306, ward_name = 'Ward 11', area_sq_km = 2.0, image_url = 'https://images.knownepal.com/schools/padma-kanya.jpg' WHERE slug = 'padma-kanya-school';
UPDATE schools SET latitude = 27.7350, longitude = 85.2890, elevation = 1340, ward_id = 307, ward_name = 'Ward 21', area_sq_km = 1.5, image_url = 'https://images.knownepal.com/schools/white-house.jpg' WHERE slug = 'white-house-academy';
UPDATE schools SET latitude = 27.6840, longitude = 85.2960, elevation = 1290, ward_id = 308, ward_name = 'Ward 15', area_sq_km = 2.2, image_url = 'https://images.knownepal.com/schools/trinity.jpg' WHERE slug = 'trinity-international-school';
UPDATE schools SET latitude = 28.2096, longitude = 83.9856, elevation = 827, ward_id = 401, ward_name = 'Ward 17', area_sq_km = 4.0, image_url = 'https://images.knownepal.com/schools/sunrise-pokhara.jpg' WHERE slug = 'sunrise-boarding-school';
UPDATE schools SET latitude = 27.7050, longitude = 85.3180, elevation = 1315, ward_id = 309, ward_name = 'Ward 14', area_sq_km = 1.8, image_url = 'https://images.knownepal.com/schools/kantipur.jpg' WHERE slug = 'kantipur-school';
UPDATE schools SET latitude = 27.6850, longitude = 85.2830, elevation = 1300, ward_id = 310, ward_name = 'Ward 18', area_sq_km = 1.2, image_url = 'https://images.knownepal.com/schools/little-angel.jpg' WHERE slug = 'little-angel-school';
UPDATE schools SET latitude = 27.6680, longitude = 85.3280, elevation = 1250, ward_id = 311, ward_name = 'Ward 12', area_sq_km = 3.5, image_url = 'https://images.knownepal.com/schools/gyanodaya.jpg' WHERE slug = 'gyanodaya-school';
UPDATE schools SET latitude = 27.6960, longitude = 85.3130, elevation = 1310, ward_id = 312, ward_name = 'Ward 8', area_sq_km = 2.8, image_url = 'https://images.knownepal.com/schools/himalaya-hss.jpg' WHERE slug = 'himalaya-hss';
UPDATE schools SET latitude = 27.7120, longitude = 85.3050, elevation = 1305, ward_id = 313, ward_name = 'Ward 24', area_sq_km = 1.6, image_url = 'https://images.knownepal.com/schools/gurukul.jpg' WHERE slug = 'gurukul-school';
UPDATE schools SET latitude = 27.7130, longitude = 85.2870, elevation = 1340, ward_id = 314, ward_name = 'Ward 5', area_sq_km = 2.0, image_url = 'https://images.knownepal.com/schools/deerwalk.jpg' WHERE slug = 'deerwalk-school';
UPDATE schools SET latitude = 28.2070, longitude = 83.9780, elevation = 835, ward_id = 402, ward_name = 'Ward 22', area_sq_km = 3.2, image_url = 'https://images.knownepal.com/schools/adarsha.jpg' WHERE slug = 'adarsha-school';
UPDATE schools SET latitude = 27.7250, longitude = 85.3350, elevation = 1290, ward_id = 315, ward_name = 'Ward 26', area_sq_km = 4.5, image_url = 'https://images.knownepal.com/schools/nepal-police.jpg' WHERE slug = 'nepal-police-school';
UPDATE schools SET latitude = 27.7190, longitude = 85.3170, elevation = 1325, ward_id = 316, ward_name = 'Ward 30', area_sq_km = 2.3, image_url = 'https://images.knownepal.com/schools/malpi.jpg' WHERE slug = 'malpi-international-school';
UPDATE schools SET latitude = 27.6720, longitude = 85.4280, elevation = 1380, ward_id = 501, ward_name = 'Ward 3', area_sq_km = 3.8, image_url = 'https://images.knownepal.com/schools/shree-krishna.jpg' WHERE slug = 'shree-krishna-hss';
UPDATE schools SET latitude = 27.6740, longitude = 85.3240, elevation = 1270, ward_id = 317, ward_name = 'Ward 13', area_sq_km = 1.9, image_url = 'https://images.knownepal.com/schools/vikram-memorial.jpg' WHERE slug = 'vikram-memorial-school';

-- === COLLEGES: Add coordinates, ward info, images ===
UPDATE colleges SET latitude = 27.6860, longitude = 85.3150, elevation = 1310, ward_id = 320, ward_name = 'Ward 35', image_url = 'https://images.knownepal.com/colleges/kathmandu-university-kuso.jpg' WHERE slug = 'kathmandu-university-school-of-management';
UPDATE colleges SET latitude = 27.7020, longitude = 85.3070, elevation = 1300, ward_id = 321, ward_name = 'Ward 28', image_url = 'https://images.knownepal.com/colleges/tribhuvan-college.jpg' WHERE slug = 'tribhuvan-university-college-of-management';
UPDATE colleges SET latitude = 27.6780, longitude = 85.3340, elevation = 1290, ward_id = 322, ward_name = 'Ward 9', image_url = 'https://images.knownepal.com/colleges/st-xaviers.jpg' WHERE slug = 'st-xaviers-college';
UPDATE colleges SET latitude = 27.7130, longitude = 85.3220, elevation = 1320, ward_id = 323, ward_name = 'Ward 31', image_url = 'https://images.knownepal.com/colleges/national-school-of-sciences.jpg' WHERE slug = 'national-school-of-sciences';
UPDATE colleges SET latitude = 27.7060, longitude = 85.3190, elevation = 1315, ward_id = 324, ward_name = 'Ward 7', image_url = 'https://images.knownepal.com/colleges/annapurna-college.jpg' WHERE slug = 'annapurna-college-of-management';
UPDATE colleges SET latitude = 27.6950, longitude = 85.3010, elevation = 1305, ward_id = 325, ward_name = 'Ward 22', image_url = 'https://images.knownepal.com/colleges/cosmos-college.jpg' WHERE slug = 'cosmos-college-of-management';
UPDATE colleges SET latitude = 27.7180, longitude = 85.3390, elevation = 1330, ward_id = 326, ward_name = 'Ward 33', image_url = 'https://images.knownepal.com/colleges/kathmandu-college.jpg' WHERE slug = 'kathmandu-college-of-management';
UPDATE colleges SET latitude = 27.6800, longitude = 85.3120, elevation = 1285, ward_id = 327, ward_name = 'Ward 6', image_url = 'https://images.knownepal.com/colleges/lakeside-college.jpg' WHERE slug = 'lakeside-college';
UPDATE colleges SET latitude = 27.6710, longitude = 85.4290, elevation = 1375, ward_id = 502, ward_name = 'Ward 5', image_url = 'https://images.knownepal.com/colleges/bhaktapur-college.jpg' WHERE slug = 'bhaktapur-college-of-management';
UPDATE colleges SET latitude = 27.6890, longitude = 85.3250, elevation = 1300, ward_id = 328, ward_name = 'Ward 19', image_url = 'https://images.knownepal.com/colleges/sunrise-college.jpg' WHERE slug = 'sunrise-college-of-management';
UPDATE colleges SET latitude = 27.7140, longitude = 85.3280, elevation = 1325, ward_id = 329, ward_name = 'Ward 25', image_url = 'https://images.knownepal.com/colleges/gandaki-college.jpg' WHERE slug = 'gandaki-college';
UPDATE colleges SET latitude = 27.6970, longitude = 85.3110, elevation = 1310, ward_id = 330, ward_name = 'Ward 2', image_url = 'https://images.knownepal.com/colleges/himalayan-college.jpg' WHERE slug = 'himalayan-college-of-management';
UPDATE colleges SET latitude = 28.2100, longitude = 83.9830, elevation = 830, ward_id = 403, ward_name = 'Ward 15', image_url = 'https://images.knownepal.com/colleges/pokhara-college.jpg' WHERE slug = 'pokhara-college-of-management';
UPDATE colleges SET latitude = 27.6820, longitude = 85.3090, elevation = 1295, ward_id = 331, ward_name = 'Ward 4', image_url = 'https://images.knownepal.com/colleges/ambition-college.jpg' WHERE slug = 'ambition-college';
UPDATE colleges SET latitude = 27.7000, longitude = 85.3320, elevation = 1318, ward_id = 332, ward_name = 'Ward 20', image_url = 'https://images.knownepal.com/colleges/apex-college.jpg' WHERE slug = 'apex-college-of-management';
UPDATE colleges SET latitude = 27.6750, longitude = 85.3370, elevation = 1288, ward_id = 333, ward_name = 'Ward 16', image_url = 'https://images.knownepal.com/colleges/sagarmatha-college.jpg' WHERE slug = 'sagarmatha-college-of-management';
UPDATE colleges SET latitude = 27.7080, longitude = 85.3150, elevation = 1312, ward_id = 334, ward_name = 'Ward 11', image_url = 'https://images.knownepal.com/colleges/international-college.jpg' WHERE slug = 'international-college-of-management';
UPDATE colleges SET latitude = 27.6910, longitude = 85.3200, elevation = 1303, ward_id = 335, ward_name = 'Ward 8', image_url = 'https://images.knownepal.com/colleges/pinnacle-college.jpg' WHERE slug = 'pinnacle-college-of-management';
UPDATE colleges SET latitude = 27.6830, longitude = 85.3400, elevation = 1292, ward_id = 336, ward_name = 'Ward 14', image_url = 'https://images.knownepal.com/colleges/lord-buddha-college.jpg' WHERE slug = 'lord-buddha-college';
UPDATE colleges SET latitude = 27.7100, longitude = 85.3260, elevation = 1322, ward_id = 337, ward_name = 'Ward 23', image_url = 'https://images.knownepal.com/colleges/nepal-college.jpg' WHERE slug = 'nepal-college-of-management';

-- === UNIVERSITIES: Add coordinates, ward info, viceChancellors, images ===
UPDATE universities SET latitude = 27.6815, longitude = 85.3115, elevation = 1320, vice_chancellor = 'Prof. Dr. Kailash Nath Kandel', ward_id = 340, ward_name = 'Ward 1', image_url = 'https://images.knownepal.com/universities/tribhuvan.jpg' WHERE slug = 'tribhuvan-university';
UPDATE universities SET latitude = 27.6230, longitude = 85.5380, elevation = 1550, vice_chancellor = 'Prof. Dr. Bhola Thapa', ward_id = 601, ward_name = 'Ward 3', image_url = 'https://images.knownepal.com/universities/kathmandu.jpg' WHERE slug = 'kathmandu-university';
UPDATE universities SET latitude = 28.2088, longitude = 83.9850, elevation = 830, vice_chancellor = 'Prof. Dr. Padma Bahadur Gurung', ward_id = 404, ward_name = 'Ward 1', image_url = 'https://images.knownepal.com/universities/pokhara.jpg' WHERE slug = 'pokhara-university';
UPDATE universities SET latitude = 26.4525, longitude = 87.2640, elevation = 76, vice_chancellor = 'Prof. Dr. Govardhan Duwadi', ward_id = 701, ward_name = 'Ward 2', image_url = 'https://images.knownepal.com/universities/purbanchal.jpg' WHERE slug = 'purbanchal-university';
UPDATE universities SET latitude = 27.4689, longitude = 83.2769, elevation = 105, vice_chancellor = 'Prof. Dr. Dawa Tshering Sherpa', ward_id = 801, ward_name = 'Ward 5', image_url = 'https://images.knownepal.com/universities/lumbini-buddhist.jpg' WHERE slug = 'lumbini-buddhist-university';
UPDATE universities SET latitude = 28.5170, longitude = 81.6320, elevation = 598, vice_chancellor = 'Prof. Dr. Khagendra Prasad Bhattarai', ward_id = 901, ward_name = 'Ward 1', image_url = 'https://images.knownepal.com/universities/madhya-paschimanchal.jpg' WHERE slug = 'madhya-paschimanchal-university';
UPDATE universities SET latitude = 27.9310, longitude = 82.7390, elevation = 573, vice_chancellor = 'Prof. Dr. Shaligram Parajuli', ward_id = 1001, ward_name = 'Ward 4', image_url = 'https://images.knownepal.com/universities/nepal-sanskrit.jpg' WHERE slug = 'nepal-sanskrit-university';
UPDATE universities SET latitude = 27.3300, longitude = 84.3620, elevation = 150, vice_chancellor = 'Prof. Dr. Pashupati Nath Khatiwada', ward_id = 1101, ward_name = 'Ward 2', image_url = 'https://images.knownepal.com/universities/agriculture-forestry.jpg' WHERE slug = 'agriculture-and-forestry-university';
UPDATE universities SET latitude = 28.9580, longitude = 80.3390, elevation = 175, vice_chancellor = 'Prof. Dr. Jagat Mohan Bhatta', ward_id = 1201, ward_name = 'Ward 1', image_url = 'https://images.knownepal.com/universities/far-western.jpg' WHERE slug = 'far-western-university';
UPDATE universities SET latitude = 29.2747, longitude = 82.1830, elevation = 2640, vice_chancellor = 'Prof. Dr. Damodar Prasad Yadav', ward_id = 1301, ward_name = 'Ward 3', image_url = 'https://images.knownepal.com/universities/mid-western.jpg' WHERE slug = 'mid-western-university';
