-- V2: Seed data for know-nepal-history
-- Insert order: eras → figures → dynasties → events (FK resolution)

-- ============================================================
-- HISTORICAL ERAS (10 records)
-- ============================================================
INSERT INTO historical_eras (slug, name, description, start_year, end_year, key_characteristics, is_featured) VALUES
('prehistoric-period', 'Prehistoric Period', 'Stone Age settlements, cave paintings, and early Himalayan civilization in Nepal. Evidence of human habitation dating back to 30,000 years.', -10000, -600, 'Stone tools, cave paintings at Armala and Khuibari, early hunter-gatherer societies, Tharu and other indigenous origins', true),
('kirat-period', 'Kirat Period', 'First organized kingdoms in Nepal. The Kirat dynasty ruled for approximately 800 years with 29 kings. Linked to Mahabharata legends.', -600, 300, 'First political confederation, 29 Kirat kings, Yalamber legendary warrior, eastern Nepal origin, Mundhum oral tradition', true),
('licchavi-period', 'Licchavi Period', 'Golden age of Nepal. Stone inscriptions, Hindu-Buddhist synthesis, trade expansion, and remarkable art/architecture.', 400, 879, 'Stone inscriptions, Hindu-Buddhist synthesis, Manadeva I, Amshuverma, Bhrikuti, Araniko, Nepal Sambat era begins', true),
('thakuri-period', 'Thakuri Period', 'Post-Licchavi era. Kasthamandap wooden pavilion built, Indra Jatra festival started, Nepal Era calendar initiated.', 879, 1120, 'Kasthamandap origin of Kathmandu name, Indra Jatra festival, Nepal Sambat calendar, Gunakama Deva', true),
('malla-period', 'Malla Period', 'Art and architecture golden age. Three rival kingdoms, magnificent Durbar Squares, cultural zenith of Newari civilization.', 1200, 1769, 'Durbar Squares, 3 rival kingdoms, Pratap Malla, Nyatapola Temple, cultural golden age, caste codification', true),
('gorkha-unification', 'Gorkha Unification', 'Prithvi Narayan Shah unified 50+ kingdoms into modern Nepal. Conquered Kathmandu Valley during Indra Jatra festival.', 1743, 1816, 'Prithvi Narayan Shah, valley conquest, Dibya Upadesh, Battle of Kirtipur, Anglo-Nepalese War, Treaty of Sugauli', true),
('rana-oligarchy', 'Rana Oligarchy', '104 years of hereditary Rana Prime Ministers. Shah kings reduced to figureheads. Nepal isolated from the world.', 1846, 1951, 'Kot Massacre, hereditary PMs, isolation, abolition of Sati and Slavery, Singha Durbar, modernization begins', true),
('panchayat-era', 'Panchayat Era', 'Partyless system under absolute monarchy. Mahendra''s coup dissolved parliament. 30 years of centralized authoritarian rule.', 1960, 1990, 'Partyless pyramid, Mahendra Highway, malaria eradication, 1980 referendum, political repression', true),
('constitutional-monarchy-civil-war', 'Constitutional Monarchy & Civil War', 'Jana Andolan I restored multiparty democracy. Royal massacre killed King Birendra. Maoist insurgency lasted 10 years.', 1990, 2008, 'Jana Andolan I, multiparty democracy, Maoist civil war, Royal Massacre, Jana Andolan II, monarchy abolished', true),
('federal-democratic-republic', 'Federal Democratic Republic', 'Nepal became a federal democratic republic. 2015 constitution. Gen Z revolution of September 2025 transformed politics.', 2008, NULL, 'Republic declared, 7 provinces, 2015 constitution, Gen Z revolution 2025, Balen Shah era, youth awakening', true);

-- ============================================================
-- HISTORICAL FIGURES (70 records)
-- ============================================================
INSERT INTO historical_figures (slug, name, description, figure_type, birth_year, death_year, birth_place, known_for, key_achievements, dynasty_affiliation, era_name, is_featured) VALUES
-- Ancient & Medieval (10)
('yalamber', 'Yalamber', 'Legendary first Kirat king and warrior. Said to have participated in the Mahabharata war from the Nepali side. Founded the Kirat dynasty.', 'KING', -600, -520, 'Eastern Nepal', 'First Kirat king, legendary warrior, Mahabharata connection', 'First major political confederation in Nepal, founded 29-king dynasty', 'Kirat Dynasty', 'Kirat Period', true),
('manadeva-i', 'Manadeva I', 'Earliest historically verified king of Nepal. His stone inscription at Changu Narayan (464 CE) is the oldest surviving inscription in Nepal.', 'KING', 420, 464, 'Kathmandu Valley', 'Earliest verified king, Changu Narayan inscription', 'Established Licchavi rule, stone inscription legacy', 'Licchavi Dynasty', 'Licchavi Period', true),
('amshuverma', 'Amshuverma', 'Greatest Licchavi king. Expanded trade routes to Tibet and India. Married his daughter Bhrikuti to Tibetan king Songtsen Gampo.', 'KING', 580, 621, 'Kathmandu Valley', 'Trade expansion, Bhrikuti marriage, cultural golden age', 'Opened trade routes, cultural diplomacy, Licchavi zenith', 'Licchavi Dynasty', 'Licchavi Period', true),
('bhrikuti', 'Bhrikuti', 'Nepali princess married to Tibetan king Songtsen Gampo. Spread Buddhism to Tibet. Cultural bridge between Nepal and Tibet.', 'SCHOLAR', 600, 650, 'Kathmandu Valley', 'Spread Buddhism to Tibet, cultural bridge', 'Marriage alliance, Buddhist mission to Tibet', 'Licchavi Dynasty', 'Licchavi Period', true),
('araniko', 'Araniko', 'Nepali architect sent to Beijing by Kublai Khan. Built the White Stupa (White Pagoda) in Beijing. Bridged Nepali and Chinese cultures.', 'SCHOLAR', 1245, 1306, 'Kathmandu Valley', 'White Stupa in Beijing, cultural ambassador', 'Built White Stupa, bridged cultures, architectural genius', 'Malla Dynasty (Kantipur)', 'Malla Period', false),
('gunakama-deva', 'Gunakama Deva', 'Thakuri king who built the Kasthamandap wooden pavilion, giving Kathmandu its name (Kastha=wood, Mandap=pavilion).', 'KING', 920, 994, 'Kathmandu Valley', 'Built Kasthamandap, origin of Kathmandu name', 'Kasthamandap construction, city naming', 'Thakuri Dynasty', 'Thakuri Period', true),
('sankhadhar-sakhwa', 'Sankhadhar Sakhwa', 'Beloved folk hero who started the Nepal Sambat era in 879 CE. Freed debtors and helped the poor. Celebrated annually.', 'SCHOLAR', 750, 820, 'Kathmandu Valley', 'Started Nepal Sambat era, freed debtors', 'Created Nepal Sambat calendar, freed debtors', 'Thakuri Dynasty', 'Thakuri Period', true),
('jayasthiti-malla', 'Jayasthiti Malla', 'Malla king who codified the Hindu caste system in Nepal, classifying 64 castes. Unified Kathmandu Valley temporarily.', 'KING', 1350, 1395, 'Kathmandu Valley', 'Caste codification, 64 castes classified', 'Formalized caste system, temporary valley unification', 'Malla Dynasty (Kantipur)', 'Malla Period', false),
('yakshamalla', 'Yakshamalla', 'Last Malla king to unite all three kingdoms of Kathmandu Valley. Cultural patron and builder.', 'KING', 1420, 1482, 'Kathmandu Valley', 'Last king to unite all three kingdoms', 'Valley unification, cultural patronage', 'Malla Dynasty (Kantipur)', 'Malla Period', false),
('bhupatindra-malla', 'Bhupatindra Malla', 'Builder of the Nyatapola Temple in Bhaktapur, the tallest pagoda in Nepal. Masterpiece of Nepali architecture.', 'KING', 1653, 1705, 'Bhaktapur', 'Nyatapola Temple builder', 'Built Nyatapola Temple, architectural masterpiece', 'Malla Dynasty (Bhaktapur)', 'Malla Period', true),

-- Shah Dynasty & Unification (12)
('dravya-shah', 'Dravya Shah', 'Founded Gorkha Kingdom in 1559 by defeating local Magar king Dalsur Ghale with the help of 6 accomplices.', 'KING', 1530, 1570, 'Lamjung', 'Founded Gorkha Kingdom', 'Conquered Gorkha, established dynasty', 'Shah Dynasty (Gorkha)', 'Gorkha Unification', false),
('ram-shah', 'Ram Shah', 'Called Ram Shah The Just. Created Nepal''s first judicial system. Famous proverb: If you seek justice, go to Gorkha.', 'KING', 1580, 1636, 'Gorkha', 'First judicial system, justice proverb', 'Created justice system, standardized weights and measures', 'Shah Dynasty (Gorkha)', 'Gorkha Unification', false),
('nar-bhupal-shah', 'Nar Bhupal Shah', 'Father of Prithvi Narayan Shah. Lost the battle of Nuwakot which motivated his son to begin unification.', 'KING', 1697, 1743, 'Gorkha', 'Father of Prithvi Narayan Shah', 'Lost Nuwakot battle, inspired unification movement', 'Shah Dynasty (Gorkha)', 'Gorkha Unification', false),
('prithvi-narayan-shah', 'Prithvi Narayan Shah', 'Founder of modern Nepal. Unified over 50 small kingdoms into one nation. Wrote Dibya Upadesh political treatise. Nepal is a garden of 4 castes and 36 ethnic groups.', 'KING', 1723, 1775, 'Gorkha', 'Founder of modern Nepal, unified 50+ kingdoms', 'Unified Nepal, wrote Dibya Upadesh, established capital at Kathmandu', 'Shah Dynasty (Nepal)', 'Gorkha Unification', true),
('abhaya-rajya-lakshmi', 'Abhaya Rajya Lakshmi', 'Wife of Prithvi Narayan Shah. Managed Kathmandu Valley campaigns while Prithvi Narayan was conquering.', 'DIPLOMAT', 1740, 1800, 'Kathmandu Valley', 'Managed valley campaigns', 'Political management during unification', 'Shah Dynasty (Nepal)', 'Gorkha Unification', false),
('pratap-singh-shah', 'Pratap Singh Shah', 'Son of Prithvi Narayan Shah. Died young at 26. Maintained father''s policies during brief reign.', 'KING', 1751, 1777, 'Kathmandu', 'Maintained unification policies', 'Continued father''s work, brief reign', 'Shah Dynasty (Nepal)', 'Gorkha Unification', false),
('rana-bahadur-shah', 'Rana Bahadur Shah', 'Became king as infant. First Shah king to voluntarily abdicate. Married Brahman widow. Murdered by his own brother in 1806.', 'KING', 1775, 1806, 'Kathmandu', 'Voluntary abdication, married Brahman widow', 'Abdicated throne, progressive marriage', 'Shah Dynasty (Nepal)', 'Gorkha Unification', false),
('girvan-yuddha-bikram-shah', 'Girvan Yuddha Bikram Shah', 'Child king who lost one-third of Nepal in the Treaty of Sugauli during the Anglo-Nepalese War. Died at just 19.', 'KING', 1797, 1816, 'Kathmandu', 'Anglo-Nepalese War, Treaty of Sugauli', 'Lost territory in Sugauli Treaty', 'Shah Dynasty (Nepal)', 'Gorkha Unification', false),
('balbhadra-kunwar', 'Balbhadra Kunwar', 'Led 600 Nepalis against 30,000 British at Battle of Nalapani. Legendary last stand. Symbol of Nepali courage.', 'WARRIOR', 1789, 1823, 'Gorkha', 'Battle of Nalapani last stand', 'Legendary defense with 600 vs 30,000', 'Shah Dynasty (Nepal)', 'Gorkha Unification', true),
('amar-singh-thapa', 'Amar Singh Thapa', 'Called Singh of Nepal. Commanded western front in Anglo-Nepalese War. One of Nepal''s greatest warriors.', 'WARRIOR', 1759, 1816, 'Western Nepal', 'Singh of Nepal, western front commander', 'Defended western Nepal, military genius', 'Shah Dynasty (Nepal)', 'Gorkha Unification', false),
('bhimsen-thapa', 'Bhimsen Thapa', 'First PM of Nepal. Modernizer who tried to reform the military and state. Eventually imprisoned and died in captivity.', 'DIPLOMAT', 1775, 1839, 'Kathmandu', 'First PM of Nepal, modernizer', 'Military reform, diplomatic efforts', 'Shah Dynasty (Nepal)', 'Gorkha Unification', false),
('mathabar-singh-thapa', 'Mathabar Singh Thapa', 'PM before the Kot Massacre. Assassinated by Jung Bahadur Rana''s allies in 1845.', 'DIPLOMAT', 1806, 1845, 'Kathmandu', 'PM before Kot Massacre', 'Last PM before Rana takeover', 'Shah Dynasty (Nepal)', 'Gorkha Unification', false),

-- Rana Dynasty (11)
('jung-bahadur-rana', 'Jung Bahadur Rana', 'Founded the Rana dynasty after the Kot Massacre of 1846. First Nepalese leader to visit Europe. Introduced the Muluki Ain legal code.', 'KING', 1817, 1877, 'Kathmandu', 'Founded Rana dynasty, Kot Massacre, visited Europe', 'Established hereditary premiership, Muluki Ain legal code', 'Rana Dynasty', 'Rana Oligarchy', true),
('bam-bahadur-kunwar', 'Bam Bahadur Kunwar', 'Brother of Jung Bahadur Rana. Briefly served as PM for 11 months before Jung Bahadur returned to power.', 'KING', 1826, 1858, 'Kathmandu', 'Brief 11-month rule', 'Transitional rule, administrative continuity', 'Rana Dynasty', 'Rana Oligarchy', false),
('ranodip-singh-kunwar', 'Ranodip Singh Kunwar', 'Jung Bahadur''s brother. Maintained stability for 8 years. Assassinated in the Shumsher family coup of 1885.', 'KING', 1825, 1885, 'Kathmandu', 'Assassinated in Shumsher coup', 'Maintained stability, victim of coup', 'Rana Dynasty', 'Rana Oligarchy', false),
('bir-shumsher-rana', 'Bir Shumsher Rana', 'Took power after assassinating Ranodip Singh. Founded Bir Hospital. Established anti-corruption system.', 'KING', 1852, 1901, 'Kathmandu', 'Founded Bir Hospital, anti-corruption', 'Hospital establishment, anti-corruption measures', 'Rana Dynasty', 'Rana Oligarchy', false),
('dev-shumsher-rana', 'Dev Shumsher Rana', 'Reformist PM who ruled for only 114 days. Founded Gorkhapatra newspaper. Issued first slavery abolition proclamation. Deposed by brother Chandra.', 'REFORM', 1862, 1914, 'Kathmandu', 'Founded Gorkhapatra, first slavery abolition', 'Newspaper founding, slavery proclamation', 'Rana Dynasty', 'Rana Oligarchy', true),
('chandra-shumsher-rana', 'Chandra Shumsher Rana', 'Greatest reformer Rana PM. Abolished Sati (1920), abolished slavery (1924), built Singha Durbar, founded Tri-Chandra College.', 'DIPLOMAT', 1863, 1929, 'Kathmandu', 'Abolished Sati and slavery, built Singha Durbar', 'Abolished Sati 1920, slavery 1924, first college, Singha Durbar', 'Rana Dynasty', 'Rana Oligarchy', true),
('bhim-shumsher-rana', 'Bhim Shumsher Rana', 'Focused on palace construction during his 3-year rule. Died in office.', 'KING', 1865, 1932, 'Kathmandu', 'Palace construction', 'Architectural projects', 'Rana Dynasty', 'Rana Oligarchy', false),
('juddha-shumsher-rana', 'Juddha Shumsher Rana', 'Rebuilt Dharahara after 1934 earthquake. Established Nepal Bank. Supported Britain in WWII with 250,000 troops. Voluntarily abdicated.', 'KING', 1875, 1952, 'Kathmandu', 'Rebuilt Dharahara, Nepal Bank, WWII support', 'Banking, industrialization, 250,000 troops in WWII', 'Rana Dynasty', 'Rana Oligarchy', true),
('padma-shumsher-rana', 'Padma Shumsher Rana', 'Promulgated Nepal''s first written constitution in 1948. Established girls'' schools. Progressive but resigned under family pressure.', 'REFORM', 1882, 1961, 'Kathmandu', 'First constitution of Nepal', 'First written constitution, girls schools, US relations', 'Rana Dynasty', 'Rana Oligarchy', true),
('mohan-shumsher-rana', 'Mohan Shumsher Rana', 'Last Rana PM. Signed the Delhi Accord ending 104 years of Rana rule. Stepped down in November 1951.', 'KING', 1885, 1967, 'Kathmandu', 'Last Rana PM, Delhi Accord', 'Ended Rana rule, signed peace accord', 'Rana Dynasty', 'Rana Oligarchy', true),

-- Democracy Activists (12)
('bhanubhakta-acharya', 'Bhanubhakta Acharya', 'Called Adikavi (first poet). Translated the Ramayana into Nepali, making it accessible to common people.', 'SCHOLAR', 1814, 1868, 'Tanahu', 'Adikavi, Ramayana translation', 'First Nepali poet, translated Ramayana', NULL, 'Constitutional Monarchy & Civil War', false),
('laxmi-prasad-devkota', 'Laxmi Prasad Devkota', 'Called Mahakavi (great poet). Wrote Muna Madan and other masterpieces. Greatest poet in Nepali literature.', 'SCHOLAR', 1909, 1959, 'Kathmandu', 'Mahakavi, Muna Madan', 'Literary genius, Muna Madan, national treasure', NULL, 'Constitutional Monarchy & Civil War', true),
('tribhuvan-bir-bikram-shah', 'Tribhuvan Bir Bikram Shah', 'Father of the Nation. Dramatically escaped to Indian Embassy in 1950, ending 104 years of Rana rule. Restored democracy.', 'KING', 1906, 1955, 'Kathmandu', 'Father of the Nation, ended Rana rule', 'Fled to Indian Embassy, restored monarchy, ended Rana oligarchy', 'Shah Dynasty (Nepal)', 'Rana Oligarchy', true),
('tanka-prasad-acharya', 'Tanka Prasad Acharya', 'Founder of Nepal Praja Parishad, first political party. Imprisoned by Ranas. First republican-minded political leader.', 'ACTIVIST', 1912, 1992, 'Kathmandu', 'Nepal Praja Parishad founder', 'Founded first political party, anti-Rana activism', NULL, 'Rana Oligarchy', false),
('bp-koirala', 'BP Koirala', 'First democratically elected PM of Nepal (1959). Nepali Congress founder. Imprisoned multiple times. Democratic icon.', 'ACTIVIST', 1914, 1982, 'Varanasi, India', 'First elected PM, Nepali Congress founder', 'Won 1959 elections, land reform, democratic leadership', 'Nepali Congress', 'Constitutional Monarchy & Civil War', true),
('subarna-shamsher-rana', 'Subarna Shamsher Rana', 'Rana prince who joined the democracy movement. Progressive reformer who challenged his own family.', 'REFORM', 1910, 1977, 'Kathmandu', 'Rana prince turned democrat', 'Crossed class lines for democracy', NULL, 'Constitutional Monarchy & Civil War', false),
('mahendra-bir-bikram-shah', 'Mahendra Bir Bikram Shah', 'King who staged the 1960 royal coup, dissolved parliament, and introduced the Panchayat system lasting 30 years.', 'KING', 1920, 1972, 'Kathmandu', '1960 coup, Panchayat system', 'Dissolved democracy, built Mahendra Highway, partyless system', 'Shah Dynasty (Nepal)', 'Panchayat Era', true),
('matrika-prasad-koirala', 'Matrika Prasad Koirala', 'First non-Rana PM in 104 years (1951). Served twice as PM. Moderate politician during transition.', 'DIPLOMAT', 1912, 2002, 'Kathmandu', 'First non-Rana PM', 'First democratic PM after Rana era', 'Nepali Congress', 'Constitutional Monarchy & Civil War', false),
('girija-prasad-koirala', 'Girija Prasad Koirala', 'PM 4 times. Led Jana Andolan II in 2006. Democratic icon who served across decades of Nepali politics.', 'ACTIVIST', 1925, 2010, 'Kathmandu', 'PM 4 times, Jana Andolan II leader', 'Multiple terms as PM, peace accord, democratic leadership', 'Nepali Congress', 'Constitutional Monarchy & Civil War', true),
('krishna-prasad-bhattarai', 'Krishna Prasad Bhattarai', 'Interim PM after Jana Andolan I (1990). Known as Bhatter Dai. Respected elder statesman.', 'ACTIVIST', 1924, 2011, 'Kathmandu', 'Interim PM 1990, Bhatter Dai', 'Transitional leadership, respected statesman', 'Nepali Congress', 'Constitutional Monarchy & Civil War', false),
('man-mohan-adhikari', 'Man Mohan Adhikari', 'First communist PM of Nepal (1994-95). Moderate left leader who worked within democratic framework.', 'ACTIVIST', 1920, 1999, 'Kathmandu', 'First communist PM', 'First communist PM, moderate governance', 'CPN (UML)', 'Constitutional Monarchy & Civil War', false),
('surya-bahadur-thapa', 'Surya Bahadur Thapa', 'PM 5 times across Panchayat and democracy eras. Lasted from 1960s to 2000s in Nepali politics.', 'DIPLOMAT', 1928, 2015, 'Dang', 'PM 5 times', 'Longest-serving political figure across eras', 'RPP', 'Panchayat Era', false),

-- Shah Kings Modern (6)
('birendra-bir-bikram-shah', 'Birendra Bir Bikram Shah', 'Most beloved king of Nepal. Educated at Eton. Accepted constitutional monarchy in 1990. Assassinated in Royal Massacre 2001.', 'KING', 1945, 2001, 'Kathmandu', 'Most beloved king, accepted democracy', 'Constitutional monarchy, modernization, beloved by people', 'Shah Dynasty (Nepal)', 'Constitutional Monarchy & Civil War', true),
('dipendra-bir-bikram-shah', 'Dipendra Bir Bikram Shah', 'Crown Prince who massacred royal family on June 1, 2001. Became king while in a coma. Died 3 days later.', 'KING', 1971, 2001, 'Kathmandu', 'Royal Massacre, king in a coma', 'Killed 10 royals including father, reigned 3 days comatose', 'Shah Dynasty (Nepal)', 'Constitutional Monarchy & Civil War', true),
('gyanendra-bir-bikram-shah', 'Gyanendra Bir Bikram Shah', 'Last king of Nepal. Staged two coups (2002, 2005). Monarchy abolished in 2008. Only person to be king twice.', 'KING', 1947, NULL, 'Kathmandu', 'Last king, two coups, monarchy abolished', 'Seized power twice, lost monarchy, forced to leave palace', 'Shah Dynasty (Nepal)', 'Constitutional Monarchy & Civil War', true),
('aishwarya-rajya-lakshmi-devi', 'Aishwarya Rajya Lakshmi Devi', 'Queen of Nepal. Killed in the Royal Massacre of June 1, 2001 along with King Birendra.', 'SCHOLAR', 1950, 2001, 'Kathmandu', 'Queen killed in Royal Massacre', 'Royal consort, victim of massacre', 'Shah Dynasty (Nepal)', 'Constitutional Monarchy & Civil War', false),
('paras-bir-bikram-shah', 'Paras Bir Bikram Shah', 'Gyanendra''s son. Controversial figure. Involved in 2001 events. Widely despised by the public.', 'DIPLOMAT', 1971, NULL, 'Kathmandu', 'Controversial prince', 'Son of last king, controversial legacy', 'Shah Dynasty (Nepal)', 'Constitutional Monarchy & Civil War', false),

-- Civil War & Modern Politics (10)
('pushpa-kamal-dahal-prachanda', 'Pushpa Kamal Dahal (Prachanda)', 'Maoist insurgency leader. First PM of republican Nepal after monarchy abolished. Served multiple terms.', 'ACTIVIST', 1954, NULL, 'Kaski', 'Maoist leader, first republican PM', 'Led 10-year insurgency, became PM, peace process', 'CPN (Maoist)', 'Constitutional Monarchy & Civil War', true),
('baburam-bhattarai', 'Baburam Bhattarai', 'Maoist ideologue and finance minister. Later formed new political party. Intellectual leader of insurgency.', 'ACTIVIST', 1954, NULL, 'Khurkot', 'Maoist ideologue, new party founder', 'Insurgency theory, governance, political reform', 'CPN (Maoist)', 'Constitutional Monarchy & Civil War', false),
('sher-bahadur-deuba', 'Sher Bahadur Deuba', 'PM 5 times. Beaten by protesters in his home during Gen Z revolution 2025. Nepali Congress leader.', 'DIPLOMAT', 1946, NULL, 'Darchula', 'PM 5 times, Gen Z victim', 'Multiple terms, peace process, beaten in 2025', 'Nepali Congress', 'Federal Democratic Republic', true),
('kp-sharma-oli', 'KP Sharma Oli', 'PM 4 times. Banned social media in Sept 2025 triggering Gen Z revolution. Resigned Sept 9, arrested April 2026.', 'DIPLOMAT', 1952, NULL, 'Jhapa', 'PM 4 times, social media ban, resigned 2025', 'Banned social media, triggered revolution, arrested 2026', 'CPN (UML)', 'Federal Democratic Republic', true),
('ram-chandra-paudel', 'Ram Chandra Paudel', 'President of Nepal. Accepted PM Oli''s resignation during Gen Z revolution. Appointed Sushila Karki as interim PM.', 'DIPLOMAT', 1944, NULL, 'Kaski', 'President, accepted resignation, appointed Karki', 'Presidential leadership during crisis', NULL, 'Federal Democratic Republic', true),
('loendra-bahadur-chand', 'Lokendra Bahadur Chand', 'PM 4 times. Panchayat loyalist who later adapted to democratic politics.', 'DIPLOMAT', 1939, NULL, 'Darchula', 'PM 4 times, Panchayat survivor', 'Crossed political systems, ambassador', 'RPP', 'Panchayat Era', false),
('marich-man-singh-shrestha', 'Marich Man Singh Shrestha', 'PM under Panchayat system. Later became ambassador to US. Represented Panchayat era politics.', 'DIPLOMAT', 1942, 2001, 'Kathmandu', 'Panchayat PM, ambassador', 'Panchayat governance, diplomatic service', NULL, 'Panchayat Era', false),
('pasang-lhamu-sherpa', 'Pasang Lhamu Sherpa', 'First Nepali woman to summit Everest. Died on the descent. National hero and inspiration.', 'WARRIOR', 1961, 1993, 'Lukla', 'First Nepali woman to summit Everest', 'Historic Everest summit, national hero', NULL, 'Constitutional Monarchy & Civil War', true),
('ang-rita-sherpa', 'Ang Rita Sherpa', 'First person to summit Everest 10 times without supplemental oxygen. Known as the Snow Leopard.', 'WARRIOR', 1948, 2020, 'Solukhumbu', '10 Everest summits without oxygen', 'Record holder, Snow Leopard legacy', NULL, 'Constitutional Monarchy & Civil War', true),
('mingma-gyalje-sherpa', 'Mingma Gyalje Sherpa', 'Summited all 14 peaks over 8,000m without supplemental oxygen. One of the greatest mountaineers.', 'WARRIOR', 1978, NULL, 'Rolwaling', 'All 14 eight-thousanders without oxygen', 'Complete 8000er collection, mountaineering legend', NULL, 'Federal Democratic Republic', false),

-- Gen Z Revolution (11)
('sushila-karki', 'Sushila Karki', 'First female PM of Nepal. Former Chief Justice (2016-2017). Anti-corruption icon. Sworn in Sept 12, 2025.', 'ACTIVIST', 1952, NULL, 'Kathmandu', 'First female PM, former Chief Justice', 'Anti-corruption record, first female PM, interim leadership', NULL, 'Federal Democratic Republic', true),
('balen-shah', 'Balendra (Balen) Shah', 'Rapper turned structural engineer turned Kathmandu Mayor. Became PM in March 2026 after RSP won elections.', 'ACTIVIST', 1990, NULL, 'Kathmandu', 'Rapper/PM, Kathmandu Mayor', 'Youth icon, became PM, 100-point reform agenda', 'RSP', 'Federal Democratic Republic', true),
('sudan-gurung', 'Sudan Gurung', 'Founder of Hami Nepal NGO. Primary organizer of Gen Z revolution. Used Discord for coordination.', 'ACTIVIST', 1995, NULL, 'Kathmandu', 'Primary Gen Z organizer', 'Organized Sept 8 protests, Discord coordination', NULL, 'Federal Democratic Republic', true),
('tanuja-pandey', 'Tanuja Pandey', '24-year-old environmental campaigner. Uploaded video about Chure mining. Helped create non-violence guidelines.', 'ACTIVIST', 2001, NULL, 'Kathmandu', 'Environmental campaigner', 'Chure mining activism, non-violence guidelines', NULL, 'Federal Democratic Republic', false),
('binod-maharjan', 'Binod Maharjan', 'First protester killed during Gen Z revolution. Age 34. Shot in head by police fire on Sept 8, 2025.', 'WARRIOR', 1991, 2025, 'Kathmandu', 'First protester killed', 'First martyr of Gen Z revolution', NULL, 'Federal Democratic Republic', true),
('shreeyam-chaulagain', 'Shreeyam Chaulagain', 'Youngest victim of Gen Z revolution. Age 17. Shot in back of head while walking away from protests.', 'WARRIOR', 2008, 2025, 'Kathmandu', 'Youngest victim of revolution', 'Youngest martyr, 17 years old', NULL, 'Federal Democratic Republic', true),
('yogendra-nyaupane', 'Yogendra Nyaupane', '24-year-old fatally wounded on first day of Gen Z protests. One of the 76 killed.', 'WARRIOR', 2001, 2025, 'Kathmandu', 'First day casualty', 'Martyr of September 8 protests', NULL, 'Federal Democratic Republic', true),
('ramesh-lekhak', 'Ramesh Lekhak', 'Home Minister who resigned on Sept 8 evening. Passport seized. Later arrested alongside Oli.', 'DIPLOMAT', 1970, NULL, 'Kathmandu', 'Resigned during crisis, arrested', 'Resigned as Home Minister, arrested April 2026', 'CPN (UML)', 'Federal Democratic Republic', false),
('general-ashok-raj-sigdel', 'General Ashok Raj Sigdel', 'Army Chief who brokered negotiations between protesters and government. Advised Oli to resign.', 'DIPLOMAT', 1970, NULL, 'Kathmandu', 'Brokered peace negotiations', 'Military mediation, advised resignation', NULL, 'Federal Democratic Republic', true),
('om-prakash-aryal', 'Om Prakash Aryal', 'Balen Shah''s legal adviser. Appointed Home Minister in Karki interim cabinet.', 'ACTIVIST', 1985, NULL, 'Kathmandu', 'Home Minister in Karki cabinet', 'Legal adviser to Balen, cabinet position', 'RSP', 'Federal Democratic Republic', false),
('durga-prasai', 'Durga Prasai', 'Right-wing activist arrested for pro-monarchy protests in March 2025. Met army chief during revolution.', 'ACTIVIST', 1970, NULL, 'Kathmandu', 'Pro-monarchy activist', 'March 2025 protests, army meeting', NULL, 'Federal Democratic Republic', false);

-- ============================================================
-- DYNASTIES & POLITICAL SYSTEMS (20 records)
-- ============================================================
INSERT INTO dynasties (slug, name, description, era_id, founder_id, start_year, end_year, capital, key_achievements, number_of_rulers, is_featured) VALUES
-- Prehistoric (2)
('gopala-dynasty', 'Gopala Dynasty', 'First known rulers of Kathmandu Valley. Buffalo-herding kingdom from approximately 300 BCE.', (SELECT id FROM historical_eras WHERE slug='prehistoric-period'), NULL, -300, -250, 'Kathmandu Valley', 'First rulers of valley, buffalo-herding civilization', 2, false),
('mahisapala-dynasty', 'Mahisapala Dynasty', 'Second dynasty of Kathmandu Valley. Agricultural kingdom following the Gopala dynasty.', (SELECT id FROM historical_eras WHERE slug='prehistoric-period'), NULL, -250, -185, 'Kathmandu Valley', 'Agricultural civilization, second dynasty', 3, false),

-- Kirat (2)
('kirat-dynasty', 'Kirat Dynasty', 'First major organized kingdom in Nepal. 29 kings ruling for approximately 800 years. Linked to Mahabharata legends.', (SELECT id FROM historical_eras WHERE slug='kirat-period'), (SELECT id FROM historical_figures WHERE slug='yalamber'), -600, 200, 'Eastern Nepal', 'First political confederation, 29 kings, Mahabharata connection', 29, true),
('soma-lunar-dynasty', 'Soma/Lunar Dynasty', 'Lunar dynasty rulers who continued Kirat tradition in eastern Nepal.', (SELECT id FROM historical_eras WHERE slug='kirat-period'), NULL, 205, 305, 'Eastern Nepal', 'Continued Kirat rule, lunar calendar', 5, false),

-- Licchavi (1)
('licchavi-dynasty', 'Licchavi Dynasty', 'Golden age of Nepal. Stone inscriptions, Hindu-Buddhist synthesis, trade expansion. Manadeva I, Amshuverma, Bhrikuti.', (SELECT id FROM historical_eras WHERE slug='licchavi-period'), (SELECT id FROM historical_figures WHERE slug='manadeva-i'), 400, 879, 'Kathmandu Valley', 'Stone inscriptions, cultural golden age, trade expansion', 15, true),

-- Thakuri (1)
('thakuri-dynasty', 'Thakuri Dynasty', 'Post-Licchavi era. Kasthamandap built, Indra Jatra festival started, Nepal Era calendar initiated.', (SELECT id FROM historical_eras WHERE slug='thakuri-period'), (SELECT id FROM historical_figures WHERE slug='gunakama-deva'), 879, 1120, 'Kathmandu Valley', 'Kasthamandap origin, Indra Jatra, Nepal Sambat', 12, true),

-- Medieval (1)
('khasa-malla-kingdom', 'Khasa Malla Kingdom', 'Western Nepal empire from Sinja valley. Major power in medieval Nepal before Malla period.', (SELECT id FROM historical_eras WHERE slug='malla-period'), NULL, 954, 1400, 'Sinja Valley', 'Western Nepal empire, Khas language origin', 10, false),

-- Malla (3)
('malla-dynasty-kantipur', 'Malla Dynasty (Kantipur)', 'Kathmandu Malla kingdom. Pratap Malla, Hanuman Dhoka, Indra Jatra. Cultural zenith.', (SELECT id FROM historical_eras WHERE slug='malla-period'), (SELECT id FROM historical_figures WHERE slug='yakshamalla'), 1201, 1768, 'Kathmandu', 'Hanuman Dhoka, Indra Jatra, cultural zenith', 20, true),
('malla-dynasty-lalitpur', 'Malla Dynasty (Lalitpur)', 'Patan Malla kingdom. Known for metal crafts, 35+ courtyards, Hiranya Varna Mahavihar.', (SELECT id FROM historical_eras WHERE slug='malla-period'), NULL, 1201, 1769, 'Lalitpur', 'Metal crafts, courtyards, architectural gems', 15, false),
('malla-dynasty-bhaktapur', 'Malla Dynasty (Bhaktapur)', 'Bhaktapur Malla kingdom. Nyatapola Temple, 55 Window Palace, Pottery Square.', (SELECT id FROM historical_eras WHERE slug='malla-period'), (SELECT id FROM historical_figures WHERE slug='bhupatindra-malla'), 1201, 1769, 'Bhaktapur', 'Nyatapola Temple, 55 Window Palace', 12, true),

-- Shah Dynasty (3)
('shah-dynasty-gorkha', 'Shah Dynasty (Gorkha)', 'Gorkha principality for 210 years before unification. 10 kings from Dravya Shah to Prithvi Narayan Shah.', (SELECT id FROM historical_eras WHERE slug='gorkha-unification'), (SELECT id FROM historical_figures WHERE slug='dravya-shah'), 1559, 1768, 'Gorkha', 'Founded Gorkha, justice system, unification movement', 10, true),
('shah-dynasty-nepal', 'Shah Dynasty (Nepal)', 'Kings of unified Nepal. 240 years from Prithvi Narayan Shah to Gyanendra. Unified nation.', (SELECT id FROM historical_eras WHERE slug='gorkha-unification'), (SELECT id FROM historical_figures WHERE slug='prithvi-narayan-shah'), 1768, 2008, 'Kathmandu', 'Unified Nepal, modernized nation, abolished 2008', 12, true),

-- Rana (1)
('rana-dynasty', 'Rana Dynasty', 'Hereditary Prime Ministers for 104 years. 11 Rana PMs from Jung Bahadur to Mohan Shumsher.', (SELECT id FROM historical_eras WHERE slug='rana-oligarchy'), (SELECT id FROM historical_figures WHERE slug='jung-bahadur-rana'), 1846, 1951, 'Kathmandu', 'Hereditary rule, isolation, modernization beginning', 11, true),

-- Panchayat (1)
('panchayat-system', 'Panchayat System', 'Partyless pyramid system under Mahendra. Village to national assemblies. 30 years of authoritarian rule.', (SELECT id FROM historical_eras WHERE slug='panchayat-era'), (SELECT id FROM historical_figures WHERE slug='mahendra-bir-bikram-shah'), 1960, 1990, 'Kathmandu', 'Partyless pyramid, Mahendra Highway, centralized power', NULL, true),

-- Democracy (2)
('nepali-congress-government', 'Nepali Congress Government', 'First democratic experiment 1951-1960. BP Koirala as first elected PM. Land reform.', (SELECT id FROM historical_eras WHERE slug='panchayat-era'), (SELECT id FROM historical_figures WHERE slug='bp-koirala'), 1951, 1960, 'Kathmandu', 'First elections, BP Koirala PM, land reform', NULL, false),
('multi-party-democracy', 'Multi-party Democracy', 'Post-1990 multiparty system. 14 governments in 18 years. Coalition instability.', (SELECT id FROM historical_eras WHERE slug='constitutional-monarchy-civil-war'), NULL, 1990, 2008, 'Kathmandu', 'Multiparty democracy, coalition governments', NULL, true),

-- Republic (1)
('federal-republic', 'Federal Democratic Republic', 'Current political system. 7 provinces, new constitution, Gen Z revolution transformed governance.', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2008, NULL, 'Kathmandu', 'Federal structure, constitution, Gen Z awakening', NULL, true);

-- ============================================================
-- HISTORICAL EVENTS (60 records)
-- ============================================================
INSERT INTO historical_events (slug, name, description, event_type, era_id, dynasty_id, event_year, end_year, location, significance, key_figures_involved, outcome, is_featured) VALUES

-- Ancient & Pre-Medieval (5)
('birth-of-gautama-buddha', 'Birth of Gautama Buddha', 'Siddhartha Gautama born in Lumbini, Nepal. Later became the founder of Buddhism, one of the world''s major religions.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='prehistoric-period'), NULL, -563, NULL, 'Lumbini', 'Origin of Buddhism, world religion birthplace', 'Siddhartha Gautama', 'Buddhism spread across Asia', true),
('kirat-confederation-founded', 'Kirat Confederation Founded', 'Yalamber establishes the first major political confederation in Nepal, uniting eastern hill tribes.', 'CORONATION', (SELECT id FROM historical_eras WHERE slug='kirat-period'), (SELECT id FROM dynasties WHERE slug='kirat-dynasty'), -600, NULL, 'Eastern Nepal', 'First organized political entity in Nepal', 'Yalamber', 'First confederation of eastern Nepal', false),
('manadeva-stone-inscription', 'Manadeva I Stone Inscription', 'Earliest surviving inscription in Nepal at Changu Narayan (464 CE). Establishes Licchavi rule historically.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='licchavi-period'), (SELECT id FROM dynasties WHERE slug='licchavi-dynasty'), 464, NULL, 'Changu Narayan', 'Earliest verified historical record in Nepal', 'Manadeva I', 'Historical documentation begins', false),
('gunakama-deva-builds-kasthamandap', 'Gunakama Deva Builds Kasthamandap', 'Construction of the wooden pavilion (Kastha=wood, Mandap=pavilion) that gave Kathmandu its name.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='thakuri-period'), (SELECT id FROM dynasties WHERE slug='thakuri-dynasty'), 949, NULL, 'Kathmandu', 'Origin of Kathmandu city name', 'Gunakama Deva', 'City naming, architectural legacy', true),
('nepal-sambat-era-begins', 'Nepal Sambat Era Begins', 'Sankhadhar Sakhwa starts the Nepal Sambat calendar in 879 CE. Unique to Nepal, started by freeing debtors.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='thakuri-period'), (SELECT id FROM dynasties WHERE slug='thakuri-dynasty'), 879, NULL, 'Kathmandu', 'Nepal unique calendar, social welfare', 'Sankhadhar Sakhwa', 'Calendar era started, debtors freed', true),

-- Malla Period (5)
('jayasthiti-malla-caste-code', 'Jayasthiti Malla Caste Code', 'Formalization of Hindu caste system in Nepal, classifying 64 castes. Lasted for centuries.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='malla-period'), (SELECT id FROM dynasties WHERE slug='malla-dynasty-kantipur'), 1382, NULL, 'Kathmandu', 'Caste system formalized, social stratification', 'Jayasthiti Malla', 'Hindu caste system institutionalized', false),
('pratap-malla-cultural-golden-age', 'Pratap Malla Cultural Golden Age', 'Peak of Kathmandu Valley arts and architecture under Pratap Malla. Poetry, dance, Indra Jatra expansion.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='malla-period'), (SELECT id FROM dynasties WHERE slug='malla-dynasty-kantipur'), 1641, NULL, 'Kathmandu', 'Cultural zenith of Malla period', 'Pratap Malla', 'Arts, poetry, architecture flourished', false),
('construction-of-nyatapola-temple', 'Construction of Nyatapola Temple', 'Five-story pagoda built by Bhupatindra Malla in Bhaktapur. Tallest temple in Nepal.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='malla-period'), (SELECT id FROM dynasties WHERE slug='malla-dynasty-bhaktapur'), 1702, NULL, 'Bhaktapur', 'Tallest pagoda in Nepal, architectural masterpiece', 'Bhupatindra Malla', 'Architectural masterpiece built', false),
('sino-nepalese-war', 'Sino-Nepalese War', 'Nepal invades Tibet, capturing trade routes. Chinese intervention forces Nepal to retreat.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='malla-period'), NULL, 1788, 1792, 'Kathmandu-Tibet', 'First major international conflict', 'Prithvi Narayan Shah successors', 'Treaty of Betrawati, tributary relationship', false),
('treaty-of-betrawati', 'Treaty of Betrawati', 'Nepal forced to accept Chinese suzerainty after Sino-Nepalese War.', 'TREATY', (SELECT id FROM historical_eras WHERE slug='malla-period'), NULL, 1792, NULL, 'Betrawati', 'Chinese suzerainty established', 'Girvan Yuddha Bikram Shah', 'Nepal becomes Chinese tributary', false),

-- Gorkha Unification (10)
('founding-of-gorkha-kingdom', 'Founding of Gorkha Kingdom', 'Dravya Shah conquers Gorkha from Magar king Dalsur Ghale with 6 accomplices.', 'CORONATION', (SELECT id FROM historical_eras WHERE slug='gorkha-unification'), (SELECT id FROM dynasties WHERE slug='shah-dynasty-gorkha'), 1559, NULL, 'Gorkha', 'Foundation of future Nepal', 'Dravya Shah', 'Gorkha Kingdom established', true),
('prithvi-narayan-begins-unification', 'Prithvi Narayan Shah Begins Unification', 'Prithvi Narayan Shah begins campaign to unite 50+ kingdoms. Nepal is a garden of 4 castes and 36 ethnic groups.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='gorkha-unification'), (SELECT id FROM dynasties WHERE slug='shah-dynasty-nepal'), 1743, 1769, 'Gorkha', 'Start of Nepal unification', 'Prithvi Narayan Shah', '50+ kingdoms conquered', true),
('battle-of-nuwakot', 'Battle of Nuwakot', 'Strategic victory opening route to Kathmandu Valley. Key early conquest.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='gorkha-unification'), (SELECT id FROM dynasties WHERE slug='shah-dynasty-nepal'), 1744, NULL, 'Nuwakot', 'Route to valley opened', 'Prithvi Narayan Shah', 'Valley access gained', false),
('battle-of-kirtipur-1st', 'Battle of Kirtipur (1st)', 'First failed assault on Kirtipur. Heavy Gorkha losses. General Kalu Pande killed.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='gorkha-unification'), NULL, 1766, NULL, 'Kirtipur', 'Gorkha setback, learning experience', 'Kalu Pande (killed)', 'Gorkha defeat', false),
('battle-of-kirtipur-3rd', 'Battle of Kirtipur (3rd)', 'Successful siege after two failures. Kirtipur conquered by Gorkha forces.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='gorkha-unification'), NULL, 1768, NULL, 'Kirtipur', 'Valley entry point secured', 'Prithvi Narayan Shah', 'Kirtipur conquered', false),
('fall-of-kathmandu', 'Fall of Kathmandu', 'Conquered during Indra Jatra festival when city was undefended. Malla rule ends.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='gorkha-unification'), (SELECT id FROM dynasties WHERE slug='shah-dynasty-nepal'), 1768, NULL, 'Kathmandu', 'Capital conquered, end of Malla rule', 'Prithvi Narayan Shah', 'Kathmandu falls to Gorkha', true),
('declaration-of-kingdom-of-nepal', 'Declaration of Kingdom of Nepal', 'Prithvi Narayan Shah declared King of unified Nepal.', 'CORONATION', (SELECT id FROM historical_eras WHERE slug='gorkha-unification'), (SELECT id FROM dynasties WHERE slug='shah-dynasty-nepal'), 1768, NULL, 'Kathmandu', 'Kingdom of Nepal formally declared', 'Prithvi Narayan Shah', 'Unified kingdom established', true),
('battle-of-nalapani', 'Battle of Nalapani', '600 Nepalis vs 30,000 British. Balbhadra Kunwar''s legendary last stand. Symbol of Nepali courage.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='gorkha-unification'), NULL, 1814, NULL, 'Nalapani', 'Legendary last stand, national courage symbol', 'Balbhadra Kunwar', 'Nepali resistance immortalized', true),
('battle-of-jaithak', 'Battle of Jaithak', 'Major battle in Anglo-Nepalese War. Heavy casualties on both sides.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='gorkha-unification'), NULL, 1814, NULL, 'Jaithak', 'Decisive battle of Anglo-Nepalese War', 'Amar Singh Thapa', 'British advance continues', false),
('treaty-of-sugauli', 'Treaty of Sugauli', 'Nepal cedes Sikkim, Darjeeling, and much of Terai. Loses one-third of territory. Boundaries permanently set.', 'TREATY', (SELECT id FROM historical_eras WHERE slug='gorkha-unification'), (SELECT id FROM dynasties WHERE slug='shah-dynasty-nepal'), 1816, NULL, 'Sugauli, India', 'Lost 1/3 of territory, boundaries set', 'Girvan Yuddha Bikram Shah', 'Nepal loses territory permanently', true),

-- Rana Era (10)
('kot-massacre', 'Kot Massacre', 'Jung Bahadur Rana kills 30-40 nobles at Kot courtyard. Seizes power and establishes hereditary premiership.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='rana-oligarchy'), (SELECT id FROM dynasties WHERE slug='rana-dynasty'), 1846, NULL, 'Kathmandu', 'Start of 104 years of Rana rule', 'Jung Bahadur Rana', 'Rana dynasty founded', true),
('jung-bahadurs-european-tour', 'Jung Bahadur''s European Tour', 'First Nepalese leader to visit Europe (Britain and France). Brought back modern ideas.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='rana-oligarchy'), (SELECT id FROM dynasties WHERE slug='rana-dynasty'), 1850, 1851, 'London/Paris', 'First European contact by Nepali leader', 'Jung Bahadur Rana', 'Modern ideas introduced', false),
('muluki-ain-introduced', 'Muluki Ain Introduced', 'Nepal''s first comprehensive legal code. Parts endured until 1963.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='rana-oligarchy'), (SELECT id FROM dynasties WHERE slug='rana-dynasty'), 1854, NULL, 'Kathmandu', 'First legal code, lasted 100+ years', 'Jung Bahadur Rana', 'Legal system established', true),
('ranodip-singh-assassinated', 'Ranodip Singh Assassinated', 'Shumsher family coup. Bir Shumsher takes power after killing Ranodip Singh.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='rana-oligarchy'), (SELECT id FROM dynasties WHERE slug='rana-dynasty'), 1885, NULL, 'Kathmandu', 'Power shift within Rana family', 'Bir Shumsher Rana', 'Shumsher branch takes power', false),
('dev-shumshers-114-day-reform', 'Dev Shumsher''s 114-Day Reform', 'Founded Gorkhapatra newspaper. First slavery abolition proclamation. Deposed by brother Chandra.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='rana-oligarchy'), (SELECT id FROM dynasties WHERE slug='rana-dynasty'), 1901, NULL, 'Kathmandu', 'First newspaper, first slavery proclamation', 'Dev Shumsher Rana', 'Reforms reversed, deposed', true),
('chandra-shumsher-abolishes-sati', 'Chandra Shumsher Abolishes Sati', 'Widow immolation on husband''s funeral pyre banned. Violators charged with murder.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='rana-oligarchy'), (SELECT id FROM dynasties WHERE slug='rana-dynasty'), 1920, NULL, 'Kathmandu', 'Abolition of cruel practice', 'Chandra Shumsher Rana', 'Sati abolished permanently', true),
('nepal-britain-treaty-1923', 'Nepal-Britain Treaty 1923', 'Nepal''s full sovereignty formally recognized by Britain. Independence confirmed.', 'TREATY', (SELECT id FROM historical_eras WHERE slug='rana-oligarchy'), (SELECT id FROM dynasties WHERE slug='rana-dynasty'), 1923, NULL, 'Kathmandu', 'Sovereignty recognized internationally', 'Chandra Shumsher Rana', 'Full independence recognized', true),
('chandra-shumsher-abolishes-slavery', 'Chandra Shumsher Abolishes Slavery', '60,000 slaves freed. Land allocated, owners compensated. Completed by 1926.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='rana-oligarchy'), (SELECT id FROM dynasties WHERE slug='rana-dynasty'), 1924, 1926, 'Kathmandu', '60,000 freed, end of human bondage', 'Chandra Shumsher Rana', 'Slavery abolished in Nepal', true),
('padma-shumshers-constitution', 'Padma Shumsher''s Constitution', 'Nepal''s first written constitution. Established bicameral legislature and fundamental rights.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='rana-oligarchy'), (SELECT id FROM dynasties WHERE slug='rana-dynasty'), 1948, NULL, 'Kathmandu', 'First written constitution in Nepal', 'Padma Shumsher Rana', 'Constitutional framework established', true),
('1951-nepalese-revolution', '1951 Nepalese Revolution', 'King Tribhuvan flees to Indian Embassy. Rana rule ends. Democracy begins.', 'REVOLUTION', (SELECT id FROM historical_eras WHERE slug='rana-oligarchy'), NULL, 1951, NULL, 'Kathmandu', 'End of 104 years of Rana rule', 'Tribhuvan, BP Koirala', 'Rana rule ends, democracy begins', true),

-- Democracy & Panchayat (8)
('bp-koirala-becomes-first-elected-pm', 'BP Koirala Becomes First Elected PM', 'Nepali Congress wins 74/109 seats. First democratic PM in Nepali history.', 'CORONATION', (SELECT id FROM historical_eras WHERE slug='panchayat-era'), (SELECT id FROM dynasties WHERE slug='nepali-congress-government'), 1959, NULL, 'Kathmandu', 'First democratic government', 'BP Koirala', 'Democracy established briefly', true),
('king-mahendras-royal-coup', 'King Mahendra''s Royal Coup', 'Dissolves elected parliament, imprisons PM BP Koirala, bans political parties.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='panchayat-era'), (SELECT id FROM dynasties WHERE slug='panchayat-system'), 1960, NULL, 'Kathmandu', 'End of first democratic experiment', 'Mahendra Bir Bikram Shah', 'Democracy crushed, Panchayat begins', true),
('panchayat-system-introduced', 'Panchayat System Introduced', 'Partyless pyramid system. Village to national assemblies. Ek Raja, Ek Bhesh, Ek Bhasa.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='panchayat-era'), (SELECT id FROM dynasties WHERE slug='panchayat-system'), 1961, NULL, 'Kathmandu', '30 years of partyless rule', 'Mahendra Bir Bikram Shah', 'Authoritarian system established', true),
('1979-student-movement', '1979 Student Movement', 'Students protest across 37 districts. 11 killed. Leads to national referendum on Panchayat system.', 'REVOLUTION', (SELECT id FROM historical_eras WHERE slug='panchayat-era'), (SELECT id FROM dynasties WHERE slug='panchayat-system'), 1979, NULL, 'Nationwide', 'Student uprising, referendum triggered', 'Students', 'Referendum held 1980', false),
('jana-andolan-i', 'Jana Andolan I (People''s Movement)', '49 days of mass protests. 50+ killed. Multiparty democracy restored. 1990 Constitution adopted.', 'REVOLUTION', (SELECT id FROM historical_eras WHERE slug='constitutional-monarchy-civil-war'), NULL, 1990, NULL, 'Nationwide', 'End of Panchayat, democracy restored', 'BP Koirala, Girija Prasad Koirala', 'Multiparty democracy restored', true),
('nepalese-civil-war-begins', 'Nepalese Civil War Begins', 'Maoist insurgency launches People''s War. 17,000-19,000 killed over 10 years.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='constitutional-monarchy-civil-war'), NULL, 1996, 2006, 'Rolpa/Rukum', 'Decade-long civil war', 'Prachanda, Baburam Bhattarai', '17,000+ dead, peace eventually', true),
('nepalese-royal-massacre', 'Nepalese Royal Massacre', 'Crown Prince Dipendra kills King Birendra, Queen Aishwarya, and 8 others. 10 dead.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='constitutional-monarchy-civil-war'), (SELECT id FROM dynasties WHERE slug='shah-dynasty-nepal'), 2001, NULL, 'Narayanhiti Royal Palace', 'Death of beloved king, dynasty weakened', 'Dipendra, Birendra', 'Gyanendra becomes king', true),
('jana-andolan-ii', 'Jana Andolan II (Loktantra Andolan)', '19-day movement. PM Oli resigns. Parliament restored. Monarchy powers stripped.', 'REVOLUTION', (SELECT id FROM historical_eras WHERE slug='constitutional-monarchy-civil-war'), NULL, 2006, NULL, 'Nationwide', 'End of royal autocracy, democracy restored', 'Seven Party Alliance, Maoists', 'Parliament restored, king stripped of power', true),

-- Modern Republic (6)
('nepal-becomes-republic', 'Nepal Becomes Republic', 'Constituent Assembly votes 560-4 to abolish 240-year-old monarchy. Federal democratic republic declared.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), (SELECT id FROM dynasties WHERE slug='federal-republic'), 2008, NULL, 'Kathmandu', 'End of monarchy, republic born', 'Constituent Assembly', 'Republic declared, monarchy abolished', true),
('2015-earthquake', '2015 April Earthquake', '7.8 magnitude earthquake kills 8,964, injures 22,000+. UNESCO sites damaged. Massive rebuilding needed.', 'OTHER', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2015, NULL, 'Gorkha/Sindhupalchok', 'Worst natural disaster in decades', NULL, '8,964 dead, massive destruction', true),
('2015-constitution-promulgated', '2015 Constitution Promulgated', '35 parts, 308 articles. 7 provinces. Secular federal democratic republic.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), (SELECT id FROM dynasties WHERE slug='federal-republic'), 2015, NULL, 'Kathmandu', 'New constitution, federal structure', 'Constituent Assembly', 'Federal republic constitution', true),
('2015-india-nepal-blockade', '2015 India-Nepal Blockade', '5-month border blockade causes fuel shortage and humanitarian crisis.', 'OTHER', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2015, 2016, 'Nepal-India border', 'Humanitarian crisis, fuel shortage', NULL, 'Blockade lasting 5 months', false),
('2022-federal-elections', '2022 Federal Elections', 'Coalition government formed. Balen Shah elected Kathmandu Mayor as independent.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), (SELECT id FROM dynasties WHERE slug='federal-republic'), 2022, NULL, 'Nationwide', 'Youth participation, Balen elected', 'Balen Shah', 'Coalition government, youth mayor', false),

-- Gen Z Revolution (15)
('social-media-ban-announced', 'Social Media Ban Announced', '26 platforms banned for not registering. Ban seen as attempt to silence anti-corruption campaigns.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2025, NULL, 'Kathmandu', 'Triggered Gen Z revolution', 'KP Sharma Oli government', 'Ban enforced Sept 4', true),
('gen-z-protests-begin', 'Gen Z Protests Begin at Maitighar', 'Thousands gather at Maitighar Mandala. Many in school uniforms. Wake Up Nepal banner.', 'REVOLUTION', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2025, NULL, 'Maitighar Mandala, Kathmandu', 'Start of youth revolution', 'Sudan Gurung, Gen Z protesters', 'Protests begin', true),
('police-open-fire', 'Police Open Fire on Protesters', '19 killed on first day. 347+ injured. Live ammunition used. Schoolchildren among dead.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2025, NULL, 'New Baneshwor, Kathmandu', 'First bloodshed, outrage spreads', 'Police, protesters', '19 dead, 347 injured', true),
('parliament-set-on-fire', 'Parliament Building Set on Fire', 'Protesters storm parliament, Singha Durbar, Shital Niwas. Multiple buildings burned.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2025, NULL, 'Kathmandu', 'State machinery collapses', 'Gen Z protesters', 'Parliament, offices destroyed', true),
('pm-oli-resigns', 'PM KP Sharma Oli Resigns', 'Resigns letter to President Paudel. Flees to army barracks. 4th time leaving office.', 'REVOLUTION', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2025, NULL, 'Kathmandu', 'Government falls', 'KP Sharma Oli', 'PM resigns, army takes control', true),
('army-takes-control', 'Army Takes Control of Security', 'General Sigdel orders indefinite curfew. Armed patrols. ID checks every few hundred yards.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2025, NULL, 'Kathmandu', 'Military rule begins', 'General Ashok Raj Sigdel', 'Curfew enforced', false),
('discord-vote-for-interim-pm', 'Discord Vote for Interim PM', '7,586 young Nepalis vote on Discord for interim PM. Sushila Karki wins. First online PM selection.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2025, NULL, 'Online (Discord)', 'First online PM vote in history', '7,586 Gen Z voters', 'Sushila Karki selected', true),
('sushila-karki-sworn-in', 'Sushila Karki Sworn In as PM', 'First female PM in Nepal''s history. 73 years old. Former Chief Justice. Anti-corruption icon.', 'CORONATION', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2025, NULL, 'Kathmandu', 'First female PM', 'Sushila Karki', 'Historic milestone', true),
('death-toll-reaches-76', 'Death Toll Reaches 76', '76 killed, 2,113 injured. 54/76 districts affected. 45 declared martyrs.', 'OTHER', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2025, NULL, 'Nationwide', 'Human cost of revolution', NULL, '76 dead, 2,113 injured', true),
('ten-point-reform-accord', '10-Point Reform Accord', 'Karki government and Gen Z sign agreement recognizing uprising as Jana Andolan.', 'TREATY', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2025, NULL, 'Kathmandu', 'Reform agenda established', 'Sushila Karki, Gen Z representatives', 'Constitutional reforms agreed', false),
('2026-snap-elections', '2026 Snap Elections', 'RSP wins 182/275 seats. First party majority since 1999. Balen Shah becomes PM.', 'REFORM', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), (SELECT id FROM dynasties WHERE slug='federal-republic'), 2026, NULL, 'Nationwide', 'First majority government since 1999', 'Balen Shah, RSP', 'RSP wins massive majority', true),
('balen-shah-sworn-in-as-pm', 'Balen Shah Sworn In as PM', 'First PM from Gen Z revolution. 100-point reform agenda. Anti-corruption focus.', 'CORONATION', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), (SELECT id FROM dynasties WHERE slug='federal-republic'), 2026, NULL, 'Kathmandu', 'Youth becomes PM, new era', 'Balen Shah', 'Reform era begins', true),
('oli-and-lekhak-arrested', 'Oli and Lekhak Arrested', 'Criminal negligence charges for ordering crackdown. Later released on bail.', 'BATTLE', (SELECT id FROM historical_eras WHERE slug='federal-democratic-republic'), NULL, 2026, NULL, 'Kathmandu', 'Accountability for violence', 'KP Sharma Oli, Ramesh Lekhak', 'Arrested, later released', true);
