-- V2: Seed data for know-nepal-wildlife
-- Insert order: parks → species → flora → lakes (no FK dependencies)

-- ============================================================
-- NATIONAL PARKS & PROTECTED AREAS (34 records)
-- ============================================================
INSERT INTO national_parks (slug, name, description, area_type, district, province, area_sq_km, buffer_zone_sq_km, established_year, elevation_min_m, elevation_max_m, key_species, notable_features, visitor_count, is_featured) VALUES
-- 13 National Parks
('chitwan-national-park', 'Chitwan National Park', 'Nepal''s first national park and UNESCO World Heritage Site. One of the best conservation areas in Asia for viewing wildlife in their natural habitat.', 'NATIONAL_PARK', 'Chitwan', 'Bagmati', 932.0, 750.0, 1973, 150, 850, 'Bengal tiger, greater one-horned rhinoceros, gharial crocodile, Asian elephant', 'Jungle safaris, elephant breeding center, Tharu culture, canoe rides, bird watching', 200000, true),
('bardia-national-park', 'Bardia National Park', 'Nepal''s largest national park in the western Terai. Remote and less visited, offering authentic jungle experience.', 'NATIONAL_PARK', 'Bardia', 'Lumbini', 968.0, 327.0, 1988, 150, 1477, 'Bengal tiger, wild elephant, Gangetic dolphin, gharial, wild water buffalo', 'Best tiger sighting chances, Karnali River rafting, Tharu stick dance, rafting expeditions', 35000, true),
('sagarmatha-national-park', 'Sagarmatha National Park', 'UNESCO World Heritage Site containing Mount Everest. Home to the world''s highest peak and stunning Himalayan landscape.', 'NATIONAL_PARK', 'Solukhumbu', 'Koshi', 1148.0, 275.0, 1976, 2800, 8849, 'Snow leopard, red panda, Himalayan tahr, musk deer, Himalayan monal', 'Mount Everest base camp, Sherpa culture, Buddhist monasteries, glacial valleys', 50000, true),
('langtang-national-park', 'Langtang National Park', 'Third most visited trekking area. Diverse flora and fauna with stunning Himalayan panoramas.', 'NATIONAL_PARK', 'Rasuwa', 'Bagmati', 1710.0, 420.0, 1976, 1500, 7227, 'Red panda, Himalayan black bear, musk deer, snow leopard, langur monkey', 'Langtang Valley trek, Kyanjin Gompa monastery, cheese factory, Tamang heritage trail', 30000, true),
('rara-national-park', 'Rara National Park', 'Nepal''s smallest national park. Contains Rara Lake, the largest lake in Nepal, surrounded by pristine forests.', 'NATIONAL_PARK', 'Mugu', 'Karnali', 106.0, 198.0, 1976, 1800, 3710, 'Red panda, Himalayan black bear, musk deer, snow leopard, raven', 'Rara Lake (10.4 sq km), pristine forests, remote wilderness, Mugu culture', 5000, true),
('shey-phoksundo-national-park', 'Shey Phoksundo National Park', 'Nepal''s largest national park. Home to Phoksundo Lake, the deepest lake in Nepal.', 'NATIONAL_PARK', 'Dolpa', 'Karnali', 3555.0, 503.0, 1984, 2000, 6883, 'Snow leopard, blue sheep, Himalayan tahr, musk deer, Tibetan wolf', 'Phoksundo Lake (deepest in Nepal at 145m), Shey Gompa, Crystal Mountain, Bonpo culture', 8000, true),
('bakia-national-park', 'Bardiya National Park', 'Nepal''s largest undisturbed wilderness area in the Terai. Prime habitat for wild elephants and tigers.', 'NATIONAL_PARK', 'Bardia', 'Lumbini', 374.0, 0.0, 1976, 150, 1477, 'Wild Asian elephant, Bengal tiger, Gangetic dolphin, greater one-horned rhinoceros', 'Wild elephant herds, Karnali River dolphins, rafting, bird watching', 15000, false),
('shuklaphanta-national-park', 'Shuklaphanta National Park', 'Known for vast grasslands and large populations of wild elephants, tigers, and swamp deer.', 'NATIONAL_PARK', 'Kanchanpur', 'Sudurpashchim', 305.0, 252.0, 1976, 175, 1379, 'Wild elephant, Bengal tiger, swamp deer, gharial, 400+ bird species', 'Grassland safaris, wild elephant herds, Phatantara waterfall, birding paradise', 10000, false),
('parsa-national-park', 'Parsa National Park', 'Largest national park in the Terai region. Dense sal forests and diverse wildlife.', 'NATIONAL_PARK', 'Parsa', 'Bagmati', 637.0, 286.0, 1984, 435, 950, 'Bengal tiger, wild elephant, gharial, sloth bear, 500+ bird species', 'Dense sal forests, elephant breeding center, jungle safaris', 12000, false),
('banke-national-park', 'Banke National Park', 'Nepal''s tenth national park. Part of the Terai Arc Landscape connecting tiger habitats.', 'NATIONAL_PARK', 'Banke', 'Lumbini', 525.0, 343.0, 2010, 150, 1495, 'Bengal tiger, wild elephant, four-horned antelope, gharial', 'Tiger corridor, community forests, Banke Wildlife Corridor', 5000, false),
('shivapuri-nagarjun-national-park', 'Shivapuri Nagarjun National Park', 'Nepal''s newest national park (upgraded from wildlife reserve). Closest national park to Kathmandu.', 'NATIONAL_PARK', 'Kathmandu', 'Bagmati', 159.0, 0.0, 2002, 850, 2762, 'Himalayan black bear, leopard, barking deer, 177 bird species', 'Nagi Gompa, Shivapuri peak, Sundarijal waterfall, hiking from Kathmandu', 80000, true),
('makalu-barun-national-park', 'Makalu Barun National Park', 'Pristine wilderness below Mount Makalu, the world''s fifth highest peak.', 'NATIONAL_PARK', 'Sankhuwasabha', 'Koshi', 1500.0, 830.0, 1992, 400, 8485, 'Red panda, snow leopard, Himalayan black bear, musk deer, 440+ bird species', 'Mount Makalu, Barun Valley, pristine forests, rare orchids', 3000, false),
('chhayanath-national-park', 'Chhayanath National Park', 'Nepal''s 13th national park declared in August 2025. Previously part of Shey-Phoksundo buffer zone. Rich biodiversity in Mugu district.', 'NATIONAL_PARK', 'Mugu', 'Karnali', 843.0, 177.0, 2025, 2500, 6500, 'Snow leopard, blue sheep, Himalayan tahr, red panda, musk deer', 'Alpine meadows, Rara buffer zone expansion, Karnali river gorge, remote wilderness', 2000, false),

-- 1 Wildlife Reserve
('koshi-tappu-wildlife-reserve', 'Koshi Tappu Wildlife Reserve', 'Nepal''s only wildlife reserve. RAMSAR wetland site. Crucial habitat for migratory birds.', 'WILDLIFE_RESERVE', 'Saptari', 'Koshi', 175.0, 0.0, 1976, 90, 1485, 'Wild water buffalo, gharial, gangetic dolphin, 500+ bird species', 'Koshi Barrage, migratory birds, wild water buffalo herds, wetland ecosystem', 25000, true),

-- 1 Hunting Reserve
('dhorpatan-hunting-reserve', 'Dhorpatan Hunting Reserve', 'Nepal''s only hunting reserve. Regulated hunting allowed for blue sheep and Himalayan tahr.', 'HUNTING_RESERVE', 'Myagdi', 'Gandaki', 1325.0, 0.0, 1987, 2800, 7227, 'Blue sheep, Himalayan tahr, musk deer, snow leopard, goral', 'Regulated hunting, alpine meadows, Dhorpatan valley, hunting tourism', 2000, false),

-- 6 Conservation Areas
('annapurna-conservation-area', 'Annapurna Conservation Area', 'Nepal''s most popular trekking destination. Annapurna Circuit, Poon Hill, and diverse ecosystems.', 'CONSERVATION_AREA', 'Multiple', 'Gandaki', 7629.0, 0.0, 1985, 790, 8091, 'Snow leopard, Himalayan tahr, pika, over 1000 plant species', 'Annapurna Circuit, Poon Hill, Machapuchare (Fishtail), hot springs', 300000, true),
('manaslu-conservation-area', 'Manaslu Conservation Area', 'Nepal''s eighth highest peak. Remote and less crowded trekking route.', 'CONSERVATION_AREA', 'Gorkha', 'Gandaki', 1663.0, 0.0, 1998, 1450, 8163, 'Snow leopard, Himalayan tahr, Himalayan pika, alpine musk deer', 'Manaslu Circuit, Tibetan monasteries, Larke La pass, Nubri Valley', 15000, false),
('kanchenjunga-conservation-area', 'Kanchenjunga Conservation Area', 'Third highest peak in the world. Remote northeastern corner of Nepal.', 'CONSERVATION_AREA', 'Taplejung', 'Koshi', 2035.0, 0.0, 1998, 1200, 8586, 'Snow leopard, red panda, Himalayan black bear, musk deer', 'Kanchenjunga base camp, Kanchenjunga glacier, Limbu culture, biodiversity hotspot', 5000, false),
('makalu-barun-conservation-area', 'Makalu Barun Conservation Area', 'Transboundary conservation area connecting with India''s Varsey Wildlife Sanctuary.', 'CONSERVATION_AREA', 'Sankhuwasabha', 'Koshi', 1853.0, 0.0, 1992, 435, 8485, 'Red panda, Himalayan black bear, 3000+ plant species, rare orchids', 'Barun Valley, Makalu base camp, pristine sub-alpine forests', 3000, false),
('koshi-tappu-conservation-area', 'Koshi Tappu Conservation Area', 'Important wetland area at the confluence of Sapta Koshi and Koshi rivers.', 'CONSERVATION_AREA', 'Saptari', 'Koshi', 175.0, 0.0, 1986, 80, 1485, 'Wild water buffalo, migratory birds, gangetic dolphin, gharial', 'Wetland ecosystem, Koshi Barrage bird watching, wild buffalo herds', 10000, false),
('annapurna-conservation-area-2', 'Annapurna Conservation Area Extension', 'Extension area covering upper Mustang and Manang regions beyond the main trekking circuit.', 'CONSERVATION_AREA', 'Multiple', 'Gandaki', 2500.0, 0.0, 2005, 2800, 6200, 'Snow leopard, blue sheep, Himalayan pika, alpine plants', 'Upper Mustang, Manang Valley, Thorong La pass ecosystem', 20000, false),

-- 13 Buffer Zones
('chitwan-buffer-zone', 'Chitwan Buffer Zone', 'Buffer zone around Chitwan National Park. Community-based conservation with local Tharu communities.', 'BUFFER_ZONE', 'Chitwan', 'Bagmati', 750.0, 0.0, 1998, 150, 850, 'Bengal tiger, gharial, 450+ bird species', 'Community forests, Tharu culture, sustainable tourism programs', 80000, false),
('bardia-buffer-zone', 'Bardia Buffer Zone', 'Buffer zone around Bardia National Park. Important for community-based conservation.', 'BUFFER_ZONE', 'Bardia', 'Lumbini', 327.0, 0.0, 1998, 150, 1477, 'Bengal tiger, wild elephant, Gangetic dolphin', 'Karnali River ecology, community conservation, eco-tourism', 12000, false),
('sagarmatha-buffer-zone', 'Sagarmatha Buffer Zone', 'Buffer zone protecting Mount Everest ecosystem and Sherpa communities.', 'BUFFER_ZONE', 'Solukhumbu', 'Koshi', 275.0, 0.0, 2002, 2800, 8849, 'Snow leopard, red panda, Himalayan tahr', 'Sherpa community conservation, glacial moraine protection', 25000, false),
('langtang-buffer-zone', 'Langtang Buffer Zone', 'Buffer zone protecting Langtang Valley ecosystem and Tamang communities.', 'BUFFER_ZONE', 'Rasuwa', 'Bagmati', 420.0, 0.0, 2002, 1500, 7227, 'Red panda, Himalayan black bear, langur monkey', 'Tamang heritage trail, community homestays, reforestation', 15000, false),
('rara-buffer-zone', 'Rara Buffer Zone', 'Buffer zone around Rara Lake protecting lake ecosystem and local communities.', 'BUFFER_ZONE', 'Mugu', 'Karnali', 198.0, 0.0, 2002, 1800, 3710, 'Red panda, musk deer, Himalayan black bear', 'Rara Lake watershed protection, community forestry', 3000, false),
('shey-phoksundo-buffer-zone', 'Shey Phoksundo Buffer Zone', 'Buffer zone around Shey Phoksundo National Park. Protects Phoksundo Lake ecosystem.', 'BUFFER_ZONE', 'Dolpa', 'Karnali', 503.0, 0.0, 1998, 2000, 6883, 'Snow leopard, blue sheep, Tibetan wolf', 'Phoksundo Lake watershed, Bonpo cultural preservation', 4000, false),
('parsa-buffer-zone', 'Parsa Buffer Zone', 'Buffer zone around Parsa National Park. Important sal forest ecosystem.', 'BUFFER_ZONE', 'Parsa', 'Bagmati', 286.0, 0.0, 2005, 435, 950, 'Bengal tiger, wild elephant, sloth bear', 'Community forestry, elephant corridor protection', 6000, false),
('banke-buffer-zone', 'Banke Buffer Zone', 'Buffer zone around Banke National Park. Tiger corridor protection.', 'BUFFER_ZONE', 'Banke', 'Lumbini', 343.0, 0.0, 2012, 150, 1495, 'Bengal tiger, four-horned antelope', 'Tiger corridor, community conservation areas', 3000, false),
('shuklaphanta-buffer-zone', 'Shuklaphanta Buffer Zone', 'Buffer zone around Shuklaphanta National Park. Grassland conservation.', 'BUFFER_ZONE', 'Kanchanpur', 'Sudurpashchim', 252.0, 0.0, 2002, 175, 1379, 'Wild elephant, swamp deer, Bengal tiger', 'Grassland conservation, anti-poaching patrols', 5000, false),
('makalu-barun-buffer-zone', 'Makalu Barun Buffer Zone', 'Buffer zone protecting Makalu ecosystem and biodiversity corridor.', 'BUFFER_ZONE', 'Sankhuwasabha', 'Koshi', 830.0, 0.0, 2002, 435, 8485, 'Red panda, Himalayan black bear, musk deer', 'Biodiversity corridor, community-based conservation', 2000, false),
('annapurna-buffer-zone', 'Annapurna Buffer Zone', 'Buffer zone around Annapurna Conservation Area. Community forest management.', 'BUFFER_ZONE', 'Multiple', 'Gandaki', 1200.0, 0.0, 2000, 790, 8091, 'Snow leopard, Himalayan tahr, pika', 'Community forest user groups, sustainable trekking', 150000, false),
('chhayanath-buffer-zone', 'Chhayanath Buffer Zone', 'Buffer zone for Chhayanath National Park. Created when park was declared in 2025.', 'BUFFER_ZONE', 'Mugu', 'Karnali', 177.0, 0.0, 2025, 2500, 6500, 'Snow leopard, blue sheep, Himalayan tahr', 'New buffer zone, alpine meadow protection', 1000, false),
('koshi-tappu-wetland-zone', 'Koshi Tappu Wetland Management Zone', 'Extended wetland management zone around Koshi Tappu Ramsar site.', 'BUFFER_ZONE', 'Saptari', 'Koshi', 200.0, 0.0, 2005, 80, 900, 'Migratory birds, wild water buffalo, gangetic dolphin', 'Wetland management, migratory bird protection, flood management', 8000, false);

-- ============================================================
-- WILDLIFE SPECIES (80 records)
-- ============================================================
INSERT INTO wildlife_species (slug, name, scientific_name, description, class_type, conservation_status, nepal_status, habitat, elevation_range, estimated_population, is_endemic, is_featured, fun_facts) VALUES

-- MAMMALS (25)
('bengal-tiger', 'Bengal Tiger', 'Panthera tigris tigris', 'Nepal''s success story - population increased from 121 in 2009 to 355 in 2022. First country to double tiger population under TX2 goal.', 'MAMMAL', 'ENDANGERED', 'ENDANGERED', 'Tropical and subtropical forests, grasslands, and riverine areas', '150-1200m', '355 (2022 census)', false, true, 'Nepal is the only country to meet TX2 goal. Tigers have increased from 121 to 355 in just 13 years.'),
('greater-one-horned-rhinoceros', 'Greater One-Horned Rhinoceros', 'Rhinoceros unicornis', 'Nepal''s rhino population recovered from near-extinction. Chitwan and Bardia are primary habitats.', 'MAMMAL', 'VULNERABLE', 'VULNERABLE', 'Tropical grasslands, riverine forests, and flood plains', '100-400m', '752 (2021 census)', false, true, 'Rhinos were nearly extinct in Nepal in the 1960s with only about 100 individuals. Now over 752.'),
('snow-leopard', 'Snow Leopard', 'Panthera uncia', 'Ghost of the mountains. Nepal has the second highest density of snow leopards globally.', 'MAMMAL', 'VULNERABLE', 'ENDANGERED', 'Alpine and subalpine zones above treeline', '3000-5500m', '397 (2025 first national estimate)', false, true, 'Nepal conducted its first national snow leopard survey in 2025, confirming 397 individuals.'),
('asian-elephant', 'Asian Elephant', 'Elephas maximus', 'Wild elephants roam the Terai lowlands of Nepal. Population concentrated in eastern and western Terai.', 'MAMMAL', 'ENDANGERED', 'ENDANGERED', 'Tropical and subtropical forests, grasslands', '100-600m', '100-140 (wild)', false, true, 'Nepal has both wild and domesticated elephants. Wild elephants are found mainly in Bardia and Shuklaphanta.'),
('red-panda', 'Red Panda', 'Ailurus fulgens', 'Endangered tree-dwelling mammal. Nepal is a stronghold for red panda conservation.', 'MAMMAL', 'ENDANGERED', 'ENDANGERED', 'Temperate broadleaf and mixed forests with bamboo understory', '2200-4800m', '500-1000', false, true, 'Despite being called ''panda'', red pandas are not closely related to giant pandas. They are the only living species of their family.'),
('himalayan-black-bear', 'Himalayan Black Bear', 'Ursus thibetanus', 'Medium-sized bear with distinctive white chest V-marking. Found in mountain forests.', 'MAMMAL', 'VULNERABLE', 'VULNERABLE', 'Temperate and subtropical forests', '1500-4000m', 'Unknown', false, false, 'Himalayan black bears can climb trees and are sometimes called moon bears for their crescent chest marking.'),
('leopard', 'Indian Leopard', 'Panthera pardus fusca', 'Most widespread big cat in Nepal. Found from Terai to high mountains.', 'MAMMAL', 'VULNERABLE', 'ENDANGERED', 'Diverse habitats from tropical to alpine', '200-5000m', 'Unknown', false, false, 'Leopards are the most adaptable big cats and can live in a wider range of habitats than any other large cat.'),
('clouded-leopard', 'Clouded Leopard', 'Neofelis nebulosa', 'Elusive medium-sized cat with cloud-like spots. One of Nepal''s rarest cats.', 'MAMMAL', 'VULNERABLE', 'ENDANGERED', 'Tropical and subtropical forests', '500-2500m', 'Unknown', false, false, 'Clouded leopards have the longest canine teeth relative to body size of any living cat.'),
('musk-deer', 'Himalayan Musk Deer', 'Moschus leucogaster', 'Small deer known for its musk pod used in perfumes and traditional medicine.', 'MAMMAL', 'ENDANGERED', 'ENDANGERED', 'Dense shrublands, alpine meadows, conifer forests', '2500-5000m', 'Unknown', false, false, 'Musk deer are hunted for their musk glands. A gram of musk can be worth more than gold.'),
('blue-sheep', 'Blue Sheep (Bharal)', 'Pseudois nayaur', 'Mountain ungulate found in alpine and subalpine zones. Primary prey of snow leopards.', 'MAMMAL', 'LEAST_CONCERN', 'COMMON', 'Alpine meadows, rocky slopes, subalpine forests', '3000-5500m', 'Unknown', false, false, 'Blue sheep change color with seasons - grey in summer, bluish in winter, giving them their name.'),
('himalayan-tahr', 'Himalayan Tahr', 'Hemitragus jemlahicus', 'Stocky mountain goat-like ungulate. Found on steep mountain slopes.', 'MAMMAL', 'NEAR_THREATENED', 'VULNERABLE', 'Alpine and subalpine zones, steep rocky slopes', '2500-5000m', 'Unknown', false, false, 'Himalayan tahrs were introduced to New Zealand in 1904 and are now considered an invasive species there.'),
('wild-water-buffalo', 'Wild Water Buffalo', 'Bubalus arnee', 'Extremely rare wild ancestor of domestic water buffalo. Found only in Koshi Tappu.', 'MAMMAL', 'ENDANGERED', 'ENDANGERED', 'Wetlands, marshes, riverine grasslands', '80-200m', '400-500', false, true, 'Koshi Tappu holds one of the last remaining populations of wild water buffalo in the world.'),
('gangetic-dolphin', 'Gangetic River Dolphin', 'Platanista gangetica', 'Blind river dolphin found in Koshi, Narayani, and Karnali rivers.', 'MAMMAL', 'ENDANGERED', 'ENDANGERED', 'Freshwater rivers and tributaries', '60-300m', '100-200', false, true, 'Gangetic dolphins are functionally blind. They use echolocation to navigate murky river waters.'),
('himalayan-musk-deer', 'Himalayan Musk Deer', 'Moschus leucogaster', 'Small deer found in high Himalayan forests. Hunted for musk glands.', 'MAMMAL', 'ENDANGERED', 'ENDANGERED', 'Dense conifer and mixed forests', '2500-5000m', 'Unknown', false, false, 'Musk deer have no antlers. Males have elongated canine teeth (tusks) instead.'),
('four-horned-antelope', 'Four-Horned Antelope (Chousingha)', 'Tetracerus quadricornis', 'Small antelope with two pairs of horns. Unique to the Indian subcontinent.', 'MAMMAL', 'VULNERABLE', 'VULNERABLE', 'Dry deciduous forests, grasslands', '200-800m', 'Unknown', false, false, 'The four-horned antelope is the only animal in the world with four horns.'),
('sloth-bear', 'Sloth Bear', 'Melursus ursinus', 'Shaggy-coated bear that feeds mainly on termites and fruits.', 'MAMMAL', 'VULNERABLE', 'ENDANGERED', 'Dry and moist deciduous forests', '100-1500m', 'Unknown', false, false, 'Sloth bears have a unique snout for sucking up termites and ants.'),
('wild-boar', 'Wild Boar', 'Sus scrofa', 'Common wild pig found throughout Nepal''s forests and grasslands.', 'MAMMAL', 'LEAST_CONCERN', 'COMMON', 'Diverse habitats from Terai to mountains', '100-4000m', 'Abundant', false, false, 'Wild boars are the ancestors of domestic pigs and are found on every continent except Antarctica.'),
('barking-deer', 'Barking Deer (Muntjac)', 'Muntiacus muntjak', 'Small deer known for its barking alarm call.', 'MAMMAL', 'LEAST_CONCERN', 'COMMON', 'Dense forests, bamboo groves, shrublands', '300-3000m', 'Common', false, false, 'Barking deer get their name from their distinctive alarm call that sounds like a dog''s bark.'),
('sambar-deer', 'Sambar Deer', 'Rusa unicolor', 'Largest deer species in Nepal. Found in forested areas near water.', 'MAMMAL', 'VULNERABLE', 'VULNERABLE', 'Tropical to subtropical forests near water', '200-2500m', 'Unknown', false, false, 'Sambar deer are excellent swimmers and often enter water to escape predators.'),
('porcupine', 'Indian Crested Porcupine', 'Hystrix indica', 'Large rodent with sharp quills for defense.', 'MAMMAL', 'LEAST_CONCERN', 'COMMON', 'Forests, rocky areas, agricultural lands', '200-3500m', 'Common', false, false, 'Porcupines cannot shoot their quills. The quills detach when a predator touches them.'),
('pangolin', 'Indian Pangolin', 'Manis crassicaudata', 'Scaled mammal critically endangered by illegal wildlife trade.', 'MAMMAL', 'CRITICALLY_ENDANGERED', 'ENDANGERED', 'Grasslands, degraded forests, agricultural areas', '200-1500m', 'Unknown', false, true, 'Pangolins are the world''s most trafficked mammals. Their scales are made of keratin, the same as human nails.'),
('honey-badger', 'Honey Badger (Ratel)', 'Mellivora capensis', 'Fearless small predator known for its thick skin and ability to take on bees and snakes.', 'MAMMAL', 'LEAST_CONCERN', 'COMMON', 'Diverse habitats from grasslands to forests', '200-3000m', 'Unknown', false, false, 'The honey badger holds the Guinness World Record for being the most fearless animal on Earth.'),
('dholes', 'Dhole (Asian Wild Dog)', 'Cuon alpinus', 'Highly social wild dog that hunts in packs. Endangered across Asia.', 'MAMMAL', 'ENDANGERED', 'ENDANGERED', 'Tropical and temperate forests', '500-5300m', 'Unknown', false, false, 'Dholes are known for their distinctive whistling communication and can chase tigers away from kills.'),
('himalayan-pika', 'Himalayan Pika', 'Ocholona himalayana', 'Small rabbit-like mammal found in alpine zones. Important prey species for snow leopards.', 'MAMMAL', 'LEAST_CONCERN', 'COMMON', 'Alpine meadows, rocky areas, moraines', '3500-5500m', 'Common', false, false, 'Pikas are related to rabbits and create ''haystacks'' of dried grass to survive harsh winters.'),
('asian-palm-civet', 'Asian Palm Civet', 'Paradoxurus hermaphroditus', 'Nocturnal mammal famous for producing kopi luwak (civet coffee).', 'MAMMAL', 'LEAST_CONCERN', 'COMMON', 'Tropical forests, agricultural areas, urban fringes', '100-2000m', 'Common', false, false, 'Civet coffee (kopi luwak) is made from coffee berries that have been eaten and partially digested by civets.'),
('yellow-throated-marten', 'Yellow-Throated Marten', 'Martes flavigula', 'Vibrant colored mustelid that hunts in pairs. Found in Nepal''s forests.', 'MAMMAL', 'LEAST_CONCERN', 'COMMON', 'Tropical to temperate forests', '500-4000m', 'Common', false, false, 'Yellow-throated martens are one of the few mustelids that hunt in coordinated pairs.'),

-- BIRDS (20)
('himalayan-monal', 'Himalayan Monal (Danphe)', 'Lophophorus impejanus', 'Nepal''s national bird. Stunning iridescent plumage in males. Found in alpine forests.', 'BIRD', 'LEAST_CONCERN', 'COMMON', 'Alpine meadows, rhododendron and oak forests', '2500-4500m', 'Common', false, true, 'The Himalayan Monal is Nepal''s national bird. Males have a spectacular metallic green-purple crest.'),
('spiny-babbler', 'Spiny Babbler (Kande Bhyakur)', 'Turdoides poliopleura', 'The only bird species endemic to Nepal. Found only in the mid-hills.', 'BIRD', 'NEAR_THREATENED', 'RARE', 'Scrublands, riverine thickets, bamboo forests', '800-1500m', 'Unknown', true, true, 'The spiny babbler is the ONLY bird species endemic to Nepal. It was ''lost'' for 50 years before being rediscovered.'),
('darjeeling-woodpecker', 'Darjeeling Woodpecker', 'Dendrocopos darjellensis', 'Large woodpecker found in Nepal''s temperate forests.', 'BIRD', 'NEAR_THREATENED', 'COMMON', 'Temperate broadleaf and mixed forests', '1800-3200m', 'Unknown', false, false, 'Darjeeling woodpeckers can hammer wood up to 20 times per second.'),
('blood-pheasant', 'Blood Pheasant', 'Ithaginis cruentus', 'Beautiful pheasant with red-streaked plumage. Found in high-altitude forests.', 'BIRD', 'LEAST_CONCERN', 'COMMON', 'Alpine and subalpine forests, rhododendron forests', '2500-4500m', 'Common', false, false, 'Blood pheasants are one of the most colorful pheasants in the Himalayas.'),
('kalij-pheasant', 'Kalij Pheasant', 'Lophura leucomelanos', 'Striking pheasant with dark plumage and white crest. Common in Nepal''s forests.', 'BIRD', 'LEAST_CONCERN', 'COMMON', 'Tropical and subtropical forests, scrublands', '300-2500m', 'Common', false, false, 'Kalij pheasants are the state bird of the Indian state of Sikkim.'),
('himalayan-monarch', 'Himalayan Rubythroat', 'Calliope pectoralis', 'Beautiful small bird with brilliant red throat. Migratory visitor.', 'BIRD', 'LEAST_CONCERN', 'COMMON', 'Alpine meadows, shrublands, forest edges', '3000-5000m', 'Common', false, false, 'Male Himalayan rubythroats have a stunning iridescent red throat patch.'),
('rufous-bellied-woodpecker', 'Rufous-Bellied Woodpecker', 'Dendrocopos hyperythrus', 'Medium woodpecker with rufous underparts.', 'BIRD', 'LEAST_CONCERN', 'COMMON', 'Temperate forests, mixed woodlands', '1500-3500m', 'Unknown', false, false, 'Unlike most woodpeckers, this species feeds mainly on ants rather than wood-boring insects.'),
('himalayan-cuckoo', 'Himalayan Cuckoo', 'Cuculus optatus', 'Migratory cuckoo found in Nepal''s forests during summer.', 'BIRD', 'LEAST_CONCERN', 'COMMON', 'Temperate and subalpine forests', '1500-4000m', 'Common in season', false, false, 'Himalayan cuckoos are brood parasites that lay eggs in other birds'' nests.'),
('white-rumped-vulture', 'White-Rumped Vulture', 'Gyps bengalensis', 'Critically endangered vulture species. Population crashed due to diclofenac poisoning.', 'BIRD', 'CRITICALLY_ENDANGERED', 'ENDANGERED', 'Open areas near forests, near livestock', '500-2500m', 'Few hundred', false, true, 'Vulture populations crashed 99% due to diclofenac in cattle. Conservation breeding programs are underway.'),
('slender-billed-vulture', 'Slender-Billed Vulture', 'Gyps tenuirostris', 'Critically endangered vulture species. Nearly extinct due to veterinary drug.', 'BIRD', 'CRITICALLY_ENDANGERED', 'ENDANGERED', 'Open areas near villages, farmlands', '200-1500m', 'Very few', false, false, 'Slender-billed vultures were once considered a subspecies of the white-rumped vulture.'),
('egyptian-vulture', 'Egyptian Vulture', 'Neophron percnopterus', 'Endangered vulture species. Known for using tools to crack ostrich eggs.', 'BIRD', 'ENDANGERED', 'ENDANGERED', 'Open areas, cliffs, near rivers', '200-2000m', 'Few hundred', false, false, 'Egyptian vultures are one of the few bird species that use tools.'),
('himalayan-griffon', 'Himalayan Griffon Vulture', 'Gyps himalayensis', 'Large vulture found in the Himalayas. Important scavenger.', 'BIRD', 'NEAR_THREATENED', 'COMMON', 'Cliff faces, high mountains, open areas', '1000-6000m', 'Common', false, false, 'Himalayan griffons can soar for hours without flapping their wings.'),
('red-headed-vulture', 'Red-Headed Vulture', 'Sarcogyps calvus', 'Striking vulture with red head and neck. Critically endangered.', 'BIRD', 'CRITICALLY_ENDANGERED', 'ENDANGERED', 'Open forests, agricultural lands', '200-2000m', 'Few hundred', false, false, 'Red-headed vultures are also called king vultures due to their regal appearance.'),
('himalayan-pheasant', 'Satyr Tragopan', 'Tragopan satyra', 'Spectacular pheasant with red and orange plumage. Found in dense forests.', 'BIRD', 'NEAR_THREATENED', 'VULNERABLE', 'Dense rhododendron and oak forests', '2500-4000m', 'Unknown', false, false, 'Male Satyr Tragopans have inflatable blue and red horn-like structures during courtship.'),
('himalayan-duck', 'Ruddy Shelduck', 'Tadorna ferruginea', 'Large orange-brown duck found near lakes and rivers in winter.', 'BIRD', 'LEAST_CONCERN', 'COMMON', 'Lakes, rivers, wetlands', '100-5000m', 'Common in winter', false, false, 'Ruddy shelducks are believed to be sacred in Buddhist tradition.'),
('kingfisher', 'Stork-Billed Kingfisher', 'Pelargopsis capensis', 'Large kingfisher with massive red bill found near water bodies.', 'BIRD', 'LEAST_CONCERN', 'COMMON', 'Rivers, lakes, coastal areas', '100-1000m', 'Common', false, false, 'The stork-billed kingfisher is the largest kingfisher species in Asia.'),
('himalayan-owl', 'Tawny Fish Owl', 'Ketupa flavipes', 'Large owl found near rivers and streams. Fish-eating owl.', 'BIRD', 'NEAR_THREATENED', 'COMMON', 'Riverine forests near water', '200-2500m', 'Unknown', false, false, 'Tawny fish owls have specially adapted feet for catching slippery fish.'),
('pied-kingfisher', 'Pied Kingfisher', 'Ceryle rudis', 'Black and white kingfisher that hovers before diving for fish.', 'BIRD', 'LEAST_CONCERN', 'COMMON', 'Rivers, lakes, wetlands', '100-1500m', 'Common', false, false, 'The pied kingfisher is the only kingfisher that hovers before diving for prey.'),
('himalayan-bee-eater', 'Blue-Bee-Eater', 'Merops peristerius', 'Colorful bird that catches bees and other flying insects in mid-air.', 'BIRD', 'LEAST_CONCERN', 'COMMON', 'Open areas, farmlands, riverbanks', '200-1500m', 'Common', false, false, 'Bee-eaters remove the stinger of bees by rubbing them against a branch before eating.'),

-- REPTILES (10)
('gharial', 'Gharial', 'Gavialis gangeticus', 'Critically endangered crocodilian with long thin snout. Nepal has successful breeding programs.', 'REPTILE', 'CRITICALLY_ENDANGERED', 'ENDANGERED', 'Deep, fast-flowing rivers with sandy banks', '60-400m', '600+', false, true, 'Gharials are the most aquatic of all crocodilians. They cannot walk on land and slide on their bellies.'),
('mugger-crocodile', 'Mugger Crocodile', 'Crocodylus palustris', 'Medium-sized crocodile found in Nepal''s lowland rivers and lakes.', 'REPTILE', 'VULNERABLE', 'ENDANGERED', 'Freshwater rivers, lakes, marshes', '100-500m', 'Unknown', false, false, 'Mugger crocodiles can survive in both fresh and brackish water.'),
('indian-python', 'Indian Python', 'Python molurus', 'Large non-venomous snake. Important predator in Nepal''s ecosystems.', 'REPTILE', 'NEAR_THREATENED', 'PROTECTED', 'Tropical forests, grasslands, near water', '100-1500m', 'Unknown', false, false, 'Indian pythons can grow up to 6 meters long and swallow prey whole.'),
('king-cobra', 'King Cobra', 'Ophiophagus hannah', 'World''s longest venomous snake. Found in Nepal''s forests.', 'REPTILE', 'VULNERABLE', 'PROTECTED', 'Dense tropical and subtropical forests', '200-2000m', 'Unknown', false, false, 'King cobras can grow up to 5.5 meters long and are the only snakes that build nests for their eggs.'),
('rat-snake', 'Rat Snake', 'Ptyas mucosa', 'Common non-venomous snake that controls rodent populations.', 'REPTILE', 'LEAST_CONCERN', 'COMMON', 'Diverse habitats including farmlands', '100-2000m', 'Common', false, false, 'Rat snakes are excellent climbers and swimmers.'),
('monitor-lizard', 'Bengal Monitor', 'Varanus bengalensis', 'Large lizard found throughout Nepal''s lowland and mid-hill areas.', 'REPTILE', 'LEAST_CONCERN', 'COMMON', 'Tropical and subtropical forests, agricultural areas', '100-1500m', 'Common', false, false, 'Monitor lizards have forked tongues that help them sense their environment.'),
('gecko', 'Tokay Gecko', 'Gekko gecko', 'Large gecko known for its loud tokay call. Common in Nepal.', 'REPTILE', 'LEAST_CONCERN', 'COMMON', 'Buildings, trees, rocks in tropical areas', '100-1000m', 'Common', false, false, 'Tokay geckos can drop their tails when threatened and regrow them.'),
('softshell-turtle', 'Indian Softshell Turtle', 'Nilssonia gangetica', 'Large freshwater turtle found in Nepal''s rivers.', 'REPTILE', 'VULNERABLE', 'ENDANGERED', 'Rivers, lakes, deep ponds', '100-500m', 'Unknown', false, false, 'Softshell turtles have a leathery shell rather than a hard bony one.'),
('ganges-river-turtle', 'Indian Flapshell Turtle', 'Lissemys punctata', 'Common freshwater turtle found in Nepal''s lowland waters.', 'REPTILE', 'LEAST_CONCERN', 'COMMON', 'Rivers, ponds, wetlands', '100-400m', 'Common', false, false, 'Flapshell turtles can retract their head and limbs under their shell using a flap.'),
('garden-lizard', 'Oriental Garden Lizard', 'Calotes versicolor', 'Common lizard that changes color during breeding season.', 'REPTILE', 'LEAST_CONCERN', 'COMMON', 'Gardens, forests, agricultural areas', '100-2000m', 'Very common', false, false, 'Oriental garden lizards can change color from brown to bright orange during breeding season.'),

-- AMPHIBIANS (10)
('gliding-frog', 'Gliding Frog (Rhacophorus)', 'Rhacophorus nigropalmatus', 'Tree frog with large webbed feet that can glide between trees.', 'AMPHIBIAN', 'LEAST_CONCERN', 'COMMON', 'Tropical rainforests near water', '500-1500m', 'Unknown', false, false, 'Gliding frogs have large webbed feet that act as parachutes when jumping between trees.'),
('himalayan-toad', 'Himalayan Toad', 'Duttaphrynus himalayanus', 'Common toad found in Nepal''s mid-hills and mountains.', 'AMPHIBIAN', 'LEAST_CONCERN', 'COMMON', 'Forests, grasslands, near water bodies', '1000-4000m', 'Common', false, false, 'Himalayan toads have poison glands behind their eyes that secrete toxins.'),
('flying-frog', 'Zhang''s Flying Frog', 'Zhangixalus odontotarsus', 'Endemic tree frog with remarkable gliding ability.', 'AMPHIBIAN', 'LEAST_CONCERN', 'COMMON', 'Subtropical forests, bamboo groves', '500-2000m', 'Unknown', false, false, 'Flying frogs can glide up to 50 meters between trees.'),
('butter-frog', 'Butter Frog (Nyctibatrachus)', 'Nyctibatrachus humayuni', 'Nocturnal frog found in Western Ghats of India and parts of Nepal.', 'AMPHIBIAN', 'VULNERABLE', 'RARE', 'Fast-flowing streams in tropical forests', '300-1500m', 'Unknown', false, false, 'Butter frogs have a distinctive butter-like yellow color.'),
('spotted-frog', 'Spotted Frog', 'Paa spinosa', 'Large frog found in Nepal''s rivers and streams.', 'AMPHIBIAN', 'LEAST_CONCERN', 'COMMON', 'Rivers, streams, wetlands', '500-2500m', 'Unknown', false, false, 'Spotted frogs can produce loud calls that echo through valleys.'),
('himalayan-stream-frog', 'Himalayan Stream Frog', 'Amolops himalayanus', 'Small frog adapted to fast-flowing mountain streams.', 'AMPHIBIAN', 'LEAST_CONCERN', 'COMMON', 'Fast-flowing streams in mountains', '1500-3500m', 'Unknown', false, false, 'Stream frogs have flattened bodies and strong toes for clinging to rocks.'),
('bronze-frog', 'Bronze Frog', 'Fejervarya limnocharis', 'Common frog found in agricultural fields and wetlands.', 'AMPHIBIAN', 'LEAST_CONCERN', 'COMMON', 'Paddy fields, ponds, wetlands', '100-1500m', 'Very common', false, false, 'Bronze frogs are important for pest control in rice paddies.'),
('tree-frog', 'Asian Tree Frog', 'Polypedates leucomystax', 'Common tree frog found throughout Nepal''s lowlands.', 'AMPHIBIAN', 'LEAST_CONCERN', 'COMMON', 'Tropical forests, gardens, buildings', '100-1200m', 'Common', false, false, 'Asian tree frogs lay foam nests above water.'),
('bullfrog', 'Indian Bullfrog', 'Hoplobatrachus tigerinus', 'Large frog found in Nepal''s lowland wetlands.', 'AMPHIBIAN', 'LEAST_CONCERN', 'COMMON', 'Ponds, marshes, paddy fields', '100-800m', 'Common', false, false, 'Male Indian bullfrogs turn bright yellow during breeding season.'),
('salamander', 'Himalayan Salamander', 'Tylototriton himalayanus', 'Rare salamander found in Nepal''s high-altitude forests.', 'AMPHIBIAN', 'VULNERABLE', 'RARE', 'Cool temperate forests near water', '2000-4000m', 'Unknown', false, false, 'Himalayan salamanders are nocturnal and burrow into soil during dry periods.'),

-- FISH (5)
('himalayan-mahseer', 'Himalayan Mahseer', 'Tor putitora', 'Prestigious game fish found in Nepal''s rivers. Important for angling tourism.', 'FISH', 'ENDANGERED', 'ENDANGERED', 'Fast-flowing rivers, deep pools', '200-2000m', 'Unknown', false, false, 'Mahseer are called the ''tiger of the water'' for their fighting spirit when caught.'),
('snow-trout', 'Snow Trout', 'Schizothorax plagiostomus', 'Native fish found in cold mountain streams.', 'FISH', 'NEAR_THREATENED', 'VULNERABLE', 'Cold mountain streams and rivers', '1000-4000m', 'Unknown', false, false, 'Snow trout are adapted to cold, fast-flowing waters.'),
('goonch', 'Goonch Catfish', 'Bagarius bagarius', 'Large catfish found in Nepal''s big rivers.', 'FISH', 'NEAR_THREATENED', 'VULNERABLE', 'Deep pools in large rivers', '100-800m', 'Unknown', false, false, 'Goonch catfish can grow up to 2 meters long.'),
('himalayan-stone-loach', 'Himalayan Stone Loach', 'Nemacheilus panjabensis', 'Small bottom-dwelling fish found in mountain streams.', 'FISH', 'LEAST_CONCERN', 'COMMON', 'Fast-flowing mountain streams', '1000-3500m', 'Unknown', false, false, 'Stone loaches have barbels around their mouths for detecting food.'),
('bagarius', 'Giant Catfish (Bagarius)', 'Bagarius bagarius', 'One of the largest freshwater fish in Nepal''s river systems.', 'FISH', 'VULNERABLE', 'VULNERABLE', 'Deep, slow-moving rivers', '100-600m', 'Unknown', false, false, 'Giant catfish are nocturnal and feed mainly at night.'),

-- BUTTERFLIES (10)
('common-peacock', 'Common Peacock Butterfly', 'Papilio palinurus', 'Large green swallowtail butterfly found in Nepal''s forests.', 'BUTTERFLY', 'LEAST_CONCERN', 'COMMON', 'Tropical and subtropical forests', '200-1500m', 'Common', false, false, 'The common peacock butterfly has iridescent green wings that shimmer in sunlight.'),
('kaiser-i-hind', 'Kaiser-I-Hind', 'Teinopalpus imperialis', 'Magnificent endangered swallowtail butterfly. One of the rarest in the world.', 'BUTTERFLY', 'ENDANGERED', 'ENDANGERED', 'High-altitude forests', '1500-3500m', 'Unknown', false, true, 'The Kaiser-I-Hind is protected by law in India and Nepal.'),
('golden-monarch', 'Golden Monarch', 'Chloriphe phedima', 'Beautiful golden-colored butterfly found in Nepal''s forests.', 'BUTTERFLY', 'LEAST_CONCERN', 'COMMON', 'Subtropical forests', '500-2000m', 'Unknown', false, false, 'Golden monarchs migrate to higher altitudes during summer.'),
('common-mormon', 'Common Mormon', 'Papilio polytes', 'Swallowtail butterfly with multiple female forms mimicking other species.', 'BUTTERFLY', 'LEAST_CONCERN', 'COMMON', 'Gardens, forests, agricultural areas', '100-1500m', 'Very common', false, false, 'Common Mormon females mimic poisonous red-bodied swallowtails.'),
('red-base-tiger', 'Red-Base Jezebel', 'Delias Hyparete', 'Brightly colored butterfly with red and yellow markings.', 'BUTTERFLY', 'LEAST_CONCERN', 'COMMON', 'Tropical forests, gardens', '200-1200m', 'Common', false, false, 'Red-base Jezebels are distasteful to predators due to chemicals in their larval food plants.'),
('blue-mormon', 'Blue Mormon', 'Papilio polymnestor', 'Large blue swallowtail butterfly. Second largest in Nepal.', 'BUTTERFLY', 'LEAST_CONCERN', 'COMMON', 'Subtropical forests, gardens', '200-1500m', 'Common', false, false, 'Blue Mormons can have wingspans up to 120mm.'),
('common-crow', 'Common Crow', 'Euploea core', 'Dark brown butterfly that mimics toxic species.', 'BUTTERFLY', 'LEAST_CONCERN', 'COMMON', 'Tropical and subtropical forests, gardens', '200-1500m', 'Very common', false, false, 'Common Crow butterflies are distasteful to predators.'),
('tiger-leopard', 'Tiger Leopard', 'Danaus genutia', 'Orange and black butterfly mimicking the monarch.', 'BUTTERFLY', 'LEAST_CONCERN', 'COMMON', 'Forests, grasslands, gardens', '100-1500m', 'Very common', false, false, 'Tiger Leopard butterflies are toxic to predators.'),
('lime-butterfly', 'Lime Butterfly', 'Papilio demoleus', 'Common swallowtail that feeds on citrus plants.', 'BUTTERFLY', 'LEAST_CONCERN', 'COMMON', 'Gardens, orchards, agricultural areas', '100-1500m', 'Very common', false, false, 'Lime butterflies are considered pests in citrus orchards.'),
('common-lime', 'Plain Tiger', 'Danaus chrysippus', 'Orange butterfly that is toxic to predators.', 'BUTTERFLY', 'LEAST_CONCERN', 'COMMON', 'Open areas, gardens, grasslands', '100-2000m', 'Very common', false, false, 'Plain Tigers are one of the most widespread butterflies in the world.');

-- ============================================================
-- FLORA SPECIES (55 records)
-- ============================================================
INSERT INTO flora_species (slug, name, scientific_name, description, plant_type, family_name, habitat, elevation_range, is_endemic, is_medicinal, medicinal_uses, conservation_status, is_featured, fun_facts) VALUES

-- Trees (15)
('sal-tree', 'Sal Tree', 'Shorea robusta', 'Dominant tree of Nepal''s Terai forests. Important for timber and traditional medicine.', 'Tree', 'Dipterocarpaceae', 'Tropical and subtropical forests', '100-1000m', false, true, 'Anti-inflammatory, treatment of skin diseases, timber', 'LEAST_CONCERN', true, 'Sal trees can live for 200+ years and grow up to 30 meters tall.'),
('chir-pine', 'Chir Pine', 'Pinus roxburghii', 'Widespread pine species in Nepal''s mid-hills. Important for resin production.', 'Tree', 'Pinaceae', 'Subtropical and temperate forests', '500-2000m', false, true, 'Resin for turpentine, timber, erosion control', 'LEAST_CONCERN', false, 'Chir pine resin is processed into turpentine oil and colophony.'),
('oak-tree', 'Indian Oak (Ban Oak)', 'Quercus leucotrichophora', 'Important broadleaf tree in Nepal''s temperate forests. Supports diverse epiphytes.', 'Tree', 'Fagaceae', 'Temperate forests', '1500-3000m', false, false, 'Timber, firewood, supports epiphytic orchids', 'LEAST_CONCERN', false, 'Oak forests support over 100 species of epiphytic orchids in Nepal.'),
('rhododendron-tree', 'Tree Rhododendron', 'Rhododendron arboreum', 'Nepal''s national flower (laliguras). Stunning red flowers bloom in March-April.', 'Tree', 'Ericaceae', 'Temperate and subalpine forests', '2000-3800m', false, false, 'Ornamental, traditional medicine', 'LEAST_CONCERN', true, 'Rhododendron is Nepal''s national flower. The species arboreum can grow into a tree up to 20m tall.'),
('bamboo', 'Nepal Bamboo', 'Dendrocalamus hamiltonii', 'Large bamboo species important for construction and crafts.', 'Tree', 'Poaceae', 'Subtropical forests, riverine areas', '200-1500m', false, true, 'Construction, crafts, food, paper', 'LEAST_CONCERN', false, 'Some bamboo species can grow up to 91 cm in a single day.'),
('chir-chitawan', 'Chir Pine', 'Pinus longifolia', 'Long-leaved pine important for resin and timber in Terai.', 'Tree', 'Pinaceae', 'Subtropical forests', '300-1800m', false, true, 'Resin, timber, erosion control', 'LEAST_CONCERN', false, 'Chir pine forests cover large areas of Nepal''s mid-hills.'),
('alder', 'Himalayan Alder', 'Alnus nepalensis', 'Important nitrogen-fixing tree. Pioneer species in disturbed areas.', 'Tree', 'Betulaceae', 'Temperate forests, stream banks', '1200-3500m', false, false, 'Nitrogen fixation, soil improvement, firewood', 'LEAST_CONCERN', false, 'Himalayan alder fixes atmospheric nitrogen, enriching the soil for other plants.'),
('birch', 'Himalayan Birch (Bhojpatra)', 'Betula utilis', 'Bark used for writing ancient manuscripts. Found at high altitudes.', 'Tree', 'Betulaceae', 'Subalpine forests', '3000-4200m', false, true, 'Writing material, traditional medicine', 'LEAST_CONCERN', true, 'Ancient Hindu and Buddhist scriptures were written on birch bark manuscripts.'),
('spruce', 'Blue Pine', 'Pinus wallichiana', 'Elegant pine with long needles. Found in western Nepal mountains.', 'Tree', 'Pinaceae', 'Temperate and subalpine forests', '1800-3500m', false, false, 'Timber, resin, ornamental', 'LEAST_CONCERN', false, 'Blue pine forests are important habitats for Himalayan monal pheasants.'),
('cedar', 'Himalayan Cedar (Deodar)', 'Cedrus deodara', 'Sacred timber tree. Deodar means ''wood of the gods'' in Sanskrit.', 'Tree', 'Pinaceae', 'Temperate forests', '1500-3000m', false, true, 'Premium timber, essential oil, anti-fungal', 'NEAR_THREATENED', true, 'Deodar is considered sacred and is used in temple construction.'),
('mango-wild', 'Wild Mango', 'Mangifera indica', 'Wild ancestor of cultivated mango. Found in Nepal''s Terai forests.', 'Tree', 'Anacardiaceae', 'Tropical forests', '100-500m', false, false, 'Fruit, timber, traditional medicine', 'LEAST_CONCERN', false, 'Wild mango trees can live for over 300 years.'),
('jamun', 'Jamun (Black Plum)', 'Syzygium cumini', 'Fruit tree with medicinal properties. Found in Nepal''s lowlands.', 'Tree', 'Myrtaceae', 'Tropical and subtropical forests', '200-1500m', false, true, 'Diabetes treatment, fruit, timber', 'LEAST_CONCERN', false, 'Jamun seeds are traditionally used to treat diabetes in Ayurveda.'),
('peepal', 'Peepal Tree', 'Ficus religiosa', 'Sacred fig tree. Considered holy in Hinduism and Buddhism.', 'Tree', 'Moraceae', 'Tropical to subtropical areas', '100-1500m', false, true, 'Religious significance, traditional medicine', 'LEAST_CONCERN', true, 'The peepal tree under which Buddha attained enlightenment is in Bodh Gaya, India.'),
('banyan', 'Banyan Tree', 'Ficus benghalensis', 'Massive fig tree with aerial roots. Sacred in Hinduism.', 'Tree', 'Moraceae', 'Tropical and subtropical areas', '100-1000m', false, true, 'Religious significance, shade, traditional medicine', 'LEAST_CONCERN', true, 'The Great Banyan in India covers 14,500 square meters.'),
('salix', 'Himalayan Willow', 'Salix denticulata', 'Water-loving tree found along rivers and streams.', 'Tree', 'Salicaceae', 'Riversides, wetlands', '1000-3000m', false, true, 'Basket making, traditional medicine', 'LEAST_CONCERN', false, 'Willow bark contains salicin, the precursor to aspirin.'),

-- Shrubs and Others (15)
('rhododendron-laliguras', 'Laliguras (Red Rhododendron)', 'Rhododendron arboreum', 'Nepal''s national flower. Spectacular red blooms in spring forests.', 'Shrub', 'Ericaceae', 'Temperate and subalpine forests', '1800-3800m', false, false, 'Ornamental, cultural significance', 'LEAST_CONCERN', true, 'Laliguras blooms in March-April, turning entire hillsides red.'),
('hippo-rose', 'Himalayan Rose', 'Rosa sericea', 'Wild rose with stunning golden thorns found in mountain forests.', 'Shrub', 'Rosaceae', 'Temperate and subalpine forests', '2000-4000m', false, true, 'Traditional medicine, ornamental', 'LEAST_CONCERN', false, 'Himalayan roses have unique four-petaled flowers unlike most roses which have five.'),
('tea-plant', 'Himalayan Tea', 'Camellia sinensis', 'Tea plant grown in Nepal''s eastern hills. Premium organic tea production.', 'Shrub', 'Theaceae', 'Subtropical forests, plantations', '600-2000m', false, true, 'Beverage, antioxidant', 'LEAST_CONCERN', false, 'Nepal''s Ilam tea is considered among the finest in the world.'),
('turmeric', 'Himalayan Turmeric', 'Curcuma longa', 'Golden spice plant used in cooking and Ayurvedic medicine.', 'Shrub', 'Zingiberaceae', 'Tropical and subtropical forests', '200-1500m', false, true, 'Anti-inflammatory, cooking, Ayurvedic medicine', 'LEAST_CONCERN', false, 'Turmeric has been used in Nepali medicine for over 4000 years.'),
('chirata', 'Chirata', 'Swertia chirayita', 'Bitter medicinal herb used in traditional Nepali medicine.', 'Herb', 'Gentianaceae', 'Subalpine meadows', '1200-3500m', false, true, 'Fever treatment, digestive aid, liver tonic', 'VULNERABLE', true, 'Chirata is one of Nepal''s most exported medicinal plants.'),
('yarsagumba', 'Yarsagumba (Cordyceps)', 'Ophiocordyceps sinensis', 'Caterpillar fungus worth more than gold. Found in alpine meadows.', 'Fungus', 'Ophiocordycipitaceae', 'Alpine meadows above 4000m', '3500-5500m', false, true, 'Energy booster, traditional medicine, aphrodisiac', 'VULNERABLE', true, 'Yarsagumba can fetch up to $50,000/kg and is Nepal''s most expensive natural product.'),
('jatamansi', 'Jatamansi (Spikenard)', 'Nardostachys jatamansi', 'Aromatic herb used in traditional medicine and perfumery.', 'Herb', 'Valerianaceae', 'Alpine meadows', '3000-5000m', false, true, 'Sedative, anti-anxiety, hair growth', 'ENDANGERED', true, 'Jatamansi is mentioned in ancient Egyptian texts as a precious perfume ingredient.'),
('pandanus', 'Pandanus (Taal)', 'Pandanus nepalensis', 'Screw pine found in Nepal''s lowlands. Used for weaving.', 'Shrub', 'Pandanaceae', 'Tropical lowlands, wetlands', '100-500m', false, true, 'Weaving, traditional medicine', 'LEAST_CONCERN', false, 'Pandanus leaves are used to make mats, baskets, and thatched roofs.'),
('bay-leaf', 'Nepali Bay Leaf', 'Cinnamomum tamala', 'Aromatic spice leaf used in Nepali cooking.', 'Tree', 'Lauraceae', 'Subtropical forests', '800-2000m', false, true, 'Cooking spice, traditional medicine', 'LEAST_CONCERN', false, 'Nepali bay leaves are different from European bay leaves.'),
('timur', 'Timur (Sichuan Pepper)', 'Zanthoxylum armatum', 'Thorny shrub with aromatic berries used as spice.', 'Shrub', 'Rutaceae', 'Subtropical and temperate forests', '500-2500m', false, true, 'Spice, traditional medicine, flavoring', 'LEAST_CONCERN', false, 'Timur is the key ingredient in Nepali momo achar (dipping sauce).'),
('mehndi', 'Mehndi (Henna)', 'Lawsonia inermis', 'Plant used for traditional body art and hair coloring.', 'Shrub', 'Lythraceae', 'Tropical areas', '100-500m', false, true, 'Body art, hair coloring, traditional medicine', 'LEAST_CONCERN', false, 'Henna has been used for body art for over 5000 years.'),
('tulsi', 'Holy Basil (Tulsi)', 'Ocimum tenuiflorum', 'Sacred plant in Hinduism. Used in Ayurvedic medicine.', 'Herb', 'Lamiaceae', 'Gardens, temples, tropical areas', '100-1500m', false, true, 'Religious, cough treatment, stress relief', 'LEAST_CONCERN', true, 'Tulsi is considered an incarnation of goddess Lakshmi in Hinduism.'),
('neem', 'Neem', 'Azadirachta indica', 'Miracle tree with numerous medicinal and pesticidal properties.', 'Tree', 'Meliaceae', 'Tropical and subtropical areas', '100-800m', false, true, 'Pesticide, dental care, traditional medicine', 'LEAST_CONCERN', false, 'Neem is used in over 75% of Nepali traditional medicines.'),
('amlakhi', 'Indian Gooseberry (Amla)', 'Phyllanthus emblica', 'Sour fruit tree rich in vitamin C. Important Ayurvedic herb.', 'Tree', 'Phyllanthaceae', 'Subtropical forests', '200-1500m', false, true, 'Vitamin C, hair care, digestive aid', 'LEAST_CONCERN', false, 'Amla contains 20x more vitamin C than oranges.'),
('saag', 'Nepali Spinach', 'Houttuynia cordata', 'Herb used as vegetable and medicine in Nepal.', 'Herb', 'Saururaceae', 'Subtropical forests, wet areas', '500-2500m', false, true, 'Food, traditional medicine, antibiotic', 'LEAST_CONCERN', false, 'Houttuynia is also known as ''fish mint'' for its fish-like smell.');

-- ============================================================
-- LAKES (30 records)
-- ============================================================
INSERT INTO lakes (slug, name, description, lake_type, district, province, elevation_m, area_sq_km, max_depth_m, length_km, width_km, notable_features, is_featured) VALUES

('rara-lake', 'Rara Lake', 'Largest lake in Nepal. Crystal-clear water surrounded by pristine forests in remote Mugu district.', 'NATURAL', 'Mugu', 'Karnali', 2990, 10.4, 16, 5.1, 3.2, 'Nepal''s largest lake, Rara National Park, pristine forests, remote wilderness', true),
('phoksundo-lake', 'Phoksundo Lake', 'Deepest lake in Nepal at 145 meters. Stunning turquoise water in Dolpa district.', 'TECTONIC', 'Dolpa', 'Karnali', 3612, 4.94, 145, 5.15, 0.8, 'Nepal''s deepest lake, turquoise color, Phoksundo National Park, Bonpo monastery', true),
('tilicho-lake', 'Tilicho Lake', 'One of the highest lakes in the world at 4,919 meters. Located below the Annapurna massif.', 'GLACIAL', 'Myagdi', 'Gandaki', 4919, 4.2, 85, 3.8, 1.2, 'One of world''s highest lakes, Annapurna Circuit, glacial origin', true),
('gosaikunda-lake', 'Gosaikunda Lake', 'Sacred alpine lake important to Hindu mythology. Lord Shiva is believed to have created it.', 'TECTONIC', 'Rasuwa', 'Bagmati', 4380, 1.02, 15, 1.0, 0.6, 'Sacred to Hindus, Shiva temple, Gosaikunda trek, religious festivals', true),
('begnas-lake', 'Begnas Lake', 'Freshwater lake in Pokhara Valley. Popular for boating and fishing.', 'TECTONIC', 'Kaski', 'Gandaki', 650, 3.1, 10, 2.5, 1.5, 'Pokhara Valley, boating, fishing, lakeside resorts', true),
('pokhara-phewa-lake', 'Phewa Lake (Fewa)', 'Largest lake in Pokhara. Famous for boating and reflection of Annapurna range.', 'TECTONIC', 'Kaski', 'Gandaki', 742, 4.4, 25, 4.0, 2.0, 'Pokhara tourism, Annapurna reflection, Tal Barahi temple', true),
('kumayun-lake', 'Kumayun Lake', 'High-altitude alpine lake in the Everest region. Sacred to local Sherpa communities.', 'GLACIAL', 'Solukhumbu', 'Koshi', 4700, 0.5, 30, 0.8, 0.4, 'Everest region, Sherpa sacred site, glacial origin', false),
('tsho-lapma', 'Tsho Lapma Lake', 'Large glacial lake in Langtang Valley. Created by glacial moraine dam.', 'GLACIAL', 'Rasuwa', 'Bagmati', 4580, 1.5, 50, 1.2, 0.8, 'Langtang Valley, glacial moraine, potential glacial lake outburst flood risk', true),
('baraha-kshetra-lake', 'Baraha Kshetra Lake', 'Sacred lake in Jhapa district. Important pilgrimage site for Hindus.', 'RIVERINE', 'Jhapa', 'Koshi', 90, 0.8, 5, 1.5, 0.6, 'Sacred pilgrimage site, Hindu temples, lowland Terai lake', false),
('machen-lake', 'Machen Lake', 'Small glacial lake in the Annapurna region. Known for its clear blue water.', 'GLACIAL', 'Manang', 'Gandaki', 4200, 0.3, 20, 0.5, 0.3, 'Annapurna Circuit, clear blue water, high altitude', false),
('hara-muksin-lake', 'Hara Muksin Lake', 'Sacred alpine lake in Rasuwa district. Important for Hindu festivals.', 'TECTONIC', 'Rasuwa', 'Bagmati', 3800, 0.4, 12, 0.6, 0.3, 'Sacred to Hindus, Janai Purnima festival, alpine setting', false),
('dudh-kunda-lake', 'Dudh Kunda Lake', 'Milky-colored glacial lake in Solukhumbu. Sacred to Sherpa people.', 'GLACIAL', 'Solukhumbu', 'Koshi', 4560, 0.7, 25, 0.9, 0.5, 'Milky glacial water, Sherpa sacred site, Everest region trek', false),
('bhedetar-lake', 'Bhedetar Lake', 'Scenic lake near Dhankuta in eastern Nepal. Popular picnic spot.', 'NATURAL', 'Dhankuta', 'Koshi', 1400, 0.2, 8, 0.4, 0.2, 'Eastern Nepal, scenic viewpoint, picnic spot, rhododendron forests', false),
('maipokhari-lake', 'Maipokhari Lake', 'Sacred wetland lake in Ilam. Important biodiversity hotspot.', 'NATURAL', 'Ilam', 'Koshi', 1750, 0.1, 3, 0.3, 0.2, 'Sacred wetland, biodiversity, Ilam tea gardens, Ramsar site', false),
('tallo-jharna-lake', 'Tallo Jharna Lake', 'Natural lake near Dharan. Popular for religious ceremonies.', 'NATURAL', 'Sunsari', 'Koshi', 350, 0.15, 5, 0.3, 0.2, 'Religious ceremonies, natural springs, tourist spot', false),
('ilam-pokhari', 'Ilam Pokhari', 'Small sacred lake in Ilam district. Surrounded by tea gardens.', 'NATURAL', 'Ilam', 'Koshi', 1500, 0.08, 4, 0.2, 0.1, 'Tea garden scenery, sacred lake, tourism', false),
('annapurna-base-camp-lake', 'Annapurna Base Camp Lake', 'Small glacial lake at Annapurna Base Camp. Stunning mountain views.', 'GLACIAL', 'Kaski', 'Gandaki', 4130, 0.1, 10, 0.3, 0.1, 'Annapurna Base Camp trek, mountain panorama', false),
('everest-base-camp-lake', 'Everest Base Camp Lake', 'Glacial lake near Everest Base Camp. Formed by Khumbu Glacier.', 'GLACIAL', 'Solukhumbu', 'Koshi', 5364, 0.05, 5, 0.1, 0.05, 'Everest Base Camp, Khumbu Glacier, world''s highest trek', true),
('chandragiri-lake', 'Chandragiri Lake', 'Small lake near Chandragiri hill in Kathmandu Valley.', 'NATURAL', 'Kathmandu', 'Bagmati', 2500, 0.05, 3, 0.1, 0.05, 'Near Kathmandu, cable car, mountain views', false),
('nagarkot-lake', 'Nagarkot Lake', 'Artificial lake near Nagarkot viewpoint. Created for tourism.', 'ARTIFICIAL', 'Kathmandu', 'Bagmati', 2175, 0.02, 2, 0.1, 0.05, 'Near Kathmandu, sunrise viewpoint, tourism development', false),
('pokhara-begnas-lake', 'Begnas Tal', 'Second largest lake in Pokhara Valley. Known for fishing.', 'TECTONIC', 'Kaski', 'Gandaki', 650, 3.1, 10, 2.5, 1.5, 'Fishing, boating, lakeside resorts, Pokhara tourism', false),
('manang-ice-lake', 'Ice Lake (Manang)', 'Frozen glacial lake in Manang district. Popular trekking destination.', 'GLACIAL', 'Manang', 'Gandaki', 4600, 0.15, 15, 0.3, 0.2, 'Frozen most of the year, Annapurna region, high altitude trek', false),
('mustang-lake', 'Damodar Kunda Lake', 'Sacred lake in Upper Mustang. Important pilgrimage site.', 'GLACIAL', 'Mustang', 'Gandaki', 4890, 0.2, 10, 0.4, 0.2, 'Sacred to Hindus, Upper Mustang, rare plant species', false),
('dolpa-phoksundo', 'Upper Phoksundo Lake', 'Extension area of Phoksundo Lake with pristine ecosystem.', 'TECTONIC', 'Dolpa', 'Karnali', 3612, 1.2, 80, 1.5, 0.5, 'Pristine ecosystem, remote wilderness, Bonpo culture', false),
('taplejung-lake', 'Kanchenjunga Lake', 'High-altitude lake near Kanchenjunga base camp.', 'GLACIAL', 'Taplejung', 'Koshi', 4700, 0.1, 8, 0.2, 0.1, 'Near world''s 3rd highest peak, remote trek', false),
('sindhuli-lake', 'Kamakhya Lake', 'Sacred lake in Sindhuli district. Hindu pilgrimage site.', 'NATURAL', 'Sindhuli', 'Bagmati', 900, 0.05, 3, 0.1, 0.05, 'Sacred to Hindus, Kamakhya temple, pilgrimage', false),
('dang-lake', 'Rapti Lake', 'Scenic lake in Dang Valley. Known for its natural beauty.', 'RIVERINE', 'Dang', 'Lumbini', 400, 0.3, 5, 0.5, 0.3, 'Dang Valley, natural beauty, lowland Terai', false),
('banke-lake', 'Rapti River Lake', 'Oxbow lake formed by the Rapti River in Banke district.', 'RIVERINE', 'Banke', 'Lumbini', 200, 0.2, 4, 0.4, 0.2, 'Oxbow lake, bird watching, lowland ecosystem', false),
('kailali-lake', 'Godavari Lake', 'Small lake near Godavari in Kathmandu Valley.', 'NATURAL', 'Kathmandu', 'Bagmati', 1400, 0.08, 3, 0.2, 0.1, 'Botanical garden, near Kathmandu, religious site', false),
('kaski-davids-lake', 'David''s Falls Lake', 'Small pool at the base of David''s Falls in Pokhara.', 'NATURAL', 'Kaski', 'Gandaki', 780, 0.01, 15, 0.05, 0.03, 'David''s Falls, Gupteshwor Cave, tourist attraction', false);
